### ISSUE TITLE
SIGABRT caused by singular iterator dereference in process_item()

### ISSUE THREAD

**Issue by cambion** [CleverRaven/Cataclysm-DDA#10659]
Looks like this is happening quite infrequently now after #10654 but it still seems to be present in some cases.  I'm still working on getting a saved game to the point that it's easily reproducible.

http://pastebin.com/kws98N0t

Pastebin link as requested!

**Comment by hylkevds** [comment]
I'm not sure if it's the same problem, but the latest GIT (0.B-2105-gb41c47c) caused the following SIGABRT, and I have a save to reproduce it. I just need to find a place to upload the save.

```
#0  0x00007ffff6aecd27 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6aee418 in __GI_abort () at abort.c:89
#2  0x00007ffff74507e5 in __gnu_debug::_Error_formatter::_M_error() const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00000000004c2c53 in __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >::_Safe_iterator (this=0x7fffffffd690, __x=...) at /usr/include/c++/4.9/debug/safe_iterator.h:164
#4  0x000000000099d492 in map::process_items_in_vehicle<bool (*)(item_stack&, __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >&, point, vehicle*, int, std::string)> (this=0x35f38c8, cur_veh=0x5cf9110, current_submap=0x5d178c0, 
    processor=0x980fcd <process_vehicle_items(item_stack&, std::__debug::list<item, std::allocator<item> >::iterator&, point, vehicle*, int, std::string)>, signal="") at src/map.cpp:3176
#5  0x0000000000999c82 in map::process_items_in_vehicles<bool (*)(item_stack&, __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >&, point, vehicle*, int, std::string)> (this=0x35f38c8, current_submap=0x5d178c0, 
    processor=0x980fcd <process_vehicle_items(item_stack&, std::__debug::list<item, std::allocator<item> >::iterator&, point, vehicle*, int, std::string)>, signal="") at src/map.cpp:3165
#6  0x00000000009958e1 in map::process_items<bool (*)(item_stack&, __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >&, point, vehicle*, int, std::string), bool (*)(item_stack&, __gnu_debug::_Safe_iterator<std::__cxx1998::_List_iterator<item>, std::__debug::list<item, std::allocator<item> > >&, point, std::string)> (this=0x35f38c8, active=true, 
    veh_processor=0x980fcd <process_vehicle_items(item_stack&, std::__debug::list<item, std::allocator<item> >::iterator&, point, vehicle*, int, std::string)>, map_processor=0x980f32 <process_map_items(item_stack&, std::__debug::list<item, std::allocator<item> >::iterator&, point, std::string)>, 
    signal="") at src/map.cpp:3121
#7  0x00000000009813e7 in map::process_active_items (this=0x35f38c8) at src/map.cpp:3110
#8  0x000000000043ad86 in game::do_turn (this=0x35f3730) at src/game.cpp:1479
#9  0x0000000000a2ee11 in main (argc=0, argv=0x7fffffffdec0) at src/main.cpp:296
```

**Comment by cambion** [comment]
Have been away due to moving cross country.  I'll see if #10684 fixes this tonight.

**Comment by kevingranade** [comment]
I'm looking at the code for ripping parts off of vehicles, it looks like if you tear off a cargo part, the items in it are simply deleted instead of being removed, which means references to them remain in the active item processing list for the vehicle.
That may or may not be what's causing this.
