### ISSUE TITLE
Crash when pressing E in craft menu when no items are in the list.

### ISSUE THREAD

**Issue by adrianrieck** [CleverRaven/Cataclysm-DDA#10779]
Saw this issue in version 0B. 

To reproduce:

Open Craft menu.
Use find to search for something such as "blah", it brings up no results.
Press E
Game will crash and exit and any unsaved progress will be lost.

**Comment by namarrgon** [comment]
Still reproducible in 4c85534:

```
#0  0x00007ffff6b10a97 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6b11e6a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff74537b5 in __gnu_debug::_Error_formatter::_M_error() const () from /usr/lib/libstdc++.so.6
#3  0x0000555555f12603 in std::__debug::vector<recipe const*, std::allocator<recipe const*> >::operator[] (this=0x7fffffffbdf8, __n=0) at /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/debug/vector:357
#4  0x0000555555efda50 in select_crafting_recipe (batch_size=@0x7fffffffbed4: 0) at src/crafting.cpp:793
#5  0x0000555555efa086 in player::craft (this=0x555559cff0e8) at src/crafting.cpp:305
#6  0x00005555557e6cc2 in game::handle_action (this=0x555559cad790) at src/game.cpp:3797
#7  0x00005555557e18fc in game::do_turn (this=0x555559cad790) at src/game.cpp:1426
#8  0x0000555555cfe059 in main (argc=0, argv=0x7fffffffe310) at src/main.cpp:296
```

**Comment by KA101** [comment]
Folks, if we don't claim to have fixed a bug or crash, it's safe to assume it'll still be reproducible.  We appreciate the stack trace, though..
