### ISSUE TITLE
NPC-related (possibly?) crash

### ISSUE THREAD

**Issue by Griffinhart** [CleverRaven/Cataclysm-DDA#11720]
Version: 0.C-416-ge018aed

x86 Cygwin build.

Was wandering around in a lab (not ice) and crashed. Wasn't able to grab the exact crash error (screen was mangled, had to `!reset`), but did grab a backtrace (which is the only reason why I suspect it has anything to do with NPCs).

```
(gdb) bt
#0  0x00a6745a in std::_Rb_tree<std::string, std::string, std::_Identity<std::string>, std::less<std::string>, std::allocator<std::string> >::_M_begin (this=0x10) at /usr/lib/gcc/i686-pc-cygwin/4.9.2/include/c++/bits/stl_tree.h:524
#1  0x00a6731b in std::_Rb_tree<std::string, std::string, std::_Identity<std::string>, std::less<std::string>, std::allocator<std::string> >::find (this=0x10, __k=...) at /usr/lib/gcc/i686-pc-cygwin/4.9.2/include/c++/bits/stl_tree.h:1926
#2  0x00a58caa in std::set<std::string, std::less<std::string>, std::allocator<std::string> >::count (this=0x10, __x=...) at /usr/lib/gcc/i686-pc-cygwin/4.9.2/include/c++/bits/stl_set.h:684
#3  0x0097e9cf in Skill::is_combat_skill (this=0x0) at src/skill.cpp:101
#4  0x007af711 in npc::best_skill (this=0x830fc158) at src/npc.cpp:949
#5  0x007af843 in npc::starting_weapon (this=0x830fc158, type=NC_BOUNTY_HUNTER) at src/npc.cpp:980
#6  0x007ab259 in npc::randomize (this=0x830fc158, type=NC_BOUNTY_HUNTER) at src/npc.cpp:480
#7  0x00672e4a in game::spawn_mon (this=0xfff40008) at src/game.cpp:13300
#8  0x00670d56 in game::update_map (this=0xfff40008, x=@0x2898d0: 60, y=@0x2898cc: 60) at src/game.cpp:12960
#9  0x00669a90 in game::plmove (this=0xfff40008, dx=0, dy=1) at src/game.cpp:12153
#10 0x0062b0bf in game::handle_action (this=0xfff40008) at src/game.cpp:2935
#11 0x0061e5cd in game::do_turn (this=0xfff40008) at src/game.cpp:1429
#12 0x009831e8 in main (argc=0, argv=0x28ac30) at src/main.cpp:434
```

**Comment by BevapDin** [comment]
Your version is at least several days old, this specific bug might have already been fixed. The backtrace looks very much like the one KA101 linked in https://github.com/CleverRaven/Cataclysm-DDA/pull/11667#issuecomment-83236483, and which was by #11672 or #11638.
