### ISSUE TITLE
Crash changing NPC spawn scaling factor in game options (Cygwin)

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#13598]
In a newly-configured Cygwin environment I built 03ed82b, tried to configure options before starting a new game, and it crashed when tried to set the NPC spawn scaling factor to "0.05". It seems to be easily reproducible.

```
(gdb) bt
#0  0x00007ffbd88fa1c8 in RaiseException ()
   from /cygdrive/c/Windows/system32/KERNELBASE.dll
#1  0x00000003ffc3cba7 in cyggcc_s-seh-1!_Unwind_RaiseException ()
   from /usr/bin/cyggcc_s-seh-1.dll
#2  0x00000003fc4c41a1 in cygstdc++-6!.cxa_throw ()
   from /usr/bin/cygstdc++-6.dll
#3  0x00000003fc4bcacf in cygstdc++-6!_ZSt21__throw_runtime_errorPKc ()
   from /usr/bin/cygstdc++-6.dll
#4  0x00000003fc4b5a23 in cygstdc++-6!_ZNSt6locale5facet18_S_create_c_localeERPiPKcS1_ () from /usr/bin/cygstdc++-6.dll
#5  0x00000003fc4b3b86 in cygstdc++-6!_ZNSt6locale5_ImplC2EPKcm ()
   from /usr/bin/cygstdc++-6.dll
#6  0x00000003fc4b6363 in cygstdc++-6!_ZNSt6localeC2EPKc ()
   from /usr/bin/cygstdc++-6.dll
#7  0x00000001007686bb in show_options (ingame=false) at src/options.cpp:1419
#8  0x000000010042c6cc in game::opening_screen (this=0x600191bb0)
    at src/main_menu.cpp:350
#9  0x0000000100a25323 in main (argc=0, argv=0x24cb68) at src/main.cpp:436
(gdb) frame 7
#7  0x00000001007686bb in show_options (ingame=false) at src/options.cpp:1419
1419                            ssTemp.imbue(std::locale(""));
(gdb) l
1414                    const std::string opt_val = string_input_popup(
1415                                                    cur_opt.getMenuText(), 80, old_opt_val, "", "", -1, is_int);
1416                    if (!opt_val.empty() && opt_val != old_opt_val) {
1417                        if (is_float) {
1418                            std::istringstream ssTemp(opt_val);
1419                            ssTemp.imbue(std::locale(""));
1420                            // This uses the current locale, to allow the users
1421                            // to use their own decimal format.
1422                            float tmpFloat;
1423                            ssTemp >> tmpFloat;
```
##

**Comment by mugling** [comment]
@dholmes215 can you reproduce this in any recent version?

**Comment by dholmes215** [comment]
@mugling yes, I just reproduced it on 2f03a5c from earlier today.

It took me quite some time to do so though because I missed an important detail when I originally found the problem:  the crash only happens when you hit Enter over NPC Spawn Rate Scaling Factor and type in the number.  It does NOT crash when adjusting the number with the left/right arrow keys.

**Comment by mugling** [comment]
Most probably duplicated by #18605
