### ISSUE TITLE
Crash browsing crafting menu

### ISSUE THREAD

**Issue by dholmes215** [CleverRaven/Cataclysm-DDA#13916]
I was in the crafting menu, using [F]ind for the string "S:fabr", and hitting the down arrow.  When "pipe bomb" was selected, I hit down which would have selected "shoulder strap", when it crashed.

I'm running 534a656 (Cygwin).

```
(gdb) bt
#0  0x0000000100a4034a in item::get_covered_body_parts (this=0x24aab0)
    at src/item.cpp:256
#1  0x0000000100a4030f in item::covers (this=0x24aab0, bp=bp_head)
    at src/item.cpp:251
#2  0x0000000100a4ad83 in item::info (this=0x24aab0, showtext=true,
    dump_ref=...) at src/item.cpp:900
#3  0x0000000100a4188a in item::info (this=0x24aab0, showtext=true)
    at src/item.cpp:547
#4  0x0000000100940b09 in select_crafting_recipe (batch_size=@0x24b504: 0)
    at src/crafting.cpp:828
#5  0x000000010093d2bb in player::craft (this=0x60019a5a0)
    at src/crafting.cpp:319
#6  0x000000010065d2e7 in game::handle_action (this=0x600188d50)
    at src/game.cpp:2693
#7  0x0000000100651ba7 in game::do_turn (this=0x600188d50) at src/game.cpp:1253
#8  0x0000000100a30302 in main (argc=0, argv=0x24cb68) at src/main.cpp:439
(gdb) l
251         return get_covered_body_parts().test(bp);
252     }
253
254     std::bitset<num_bp> item::get_covered_body_parts() const
255     {
256         auto res = type->armor->covers;
257
258         switch (get_side()) {
259             case LEFT:
260                 res.reset(bp_arm_r);
```

**Comment by dholmes215** [comment]
git blame points to commit 33a7b15 being where this was introduced.

**Comment by romkuma** [comment]
Confirmed. Same build, linux, tiles, I get a crash when opening the crafting menu, but only in some circumstances (close to a vehicle - maybe specific tools/components within the crafting radius?).

I have a save with the crash repeatable - if you move within a few squares of the vehicle, and open the crafting menu, it will crash.

Zipped save folder here:
https://www.sendspace.com/file/ubdgky
