### ISSUE TITLE
Crash on map load from corrupt tea shop

### ISSUE THREAD

**Issue by rluddy** [CleverRaven/Cataclysm-DDA#14406]
When I select "Play now" in one of my new worlds, I immediately crash:
```
#7  raise (sig=sig@entry=6) at /usr/src/debug/cygwin-2.0.2-1/winsup/cygwin/signal.cc:288
#8  0x610eccc3 in abort () at /usr/src/debug/cygwin-2.0.2-1/winsup/cygwin/signal.cc:375
#9  0x6d243fea in cygstdc++-6!_ZN9__gnu_cxx27__verbose_terminate_handlerEv () from /usr/bin/cygstdc++-6.dll
#10 0x6d23d5b9 in cygstdc++-6!_ZN10__cxxabiv111__terminateEPFvvE () from /usr/bin/cygstdc++-6.dll
#11 0x6d298260 in cygstdc++-6!_ZSt9terminatev () from /usr/bin/cygstdc++-6.dll
#12 0x6d29e092 in cygstdc++-6!.cxa_throw () from /usr/bin/cygstdc++-6.dll
#13 0x004d8b61 in mapgen_function_json::setup_setmap (this=this@entry=0x80c2d0d0, parray=...) at src/mapgen.cpp:537
#14 0x004dc260 in mapgen_function_json::setup (this=0x80c2d0d0) at src/mapgen.cpp:1402
#15 0x004d9f74 in calculate_mapgen_weights () at src/mapgen.cpp:253
#16 0x006b5256 in DynamicDataLoader::finalize_loaded_data (this=0xdfbfe8 <DynamicDataLoader::get_instance()::theDynamicDataLoader>) at src/init.cpp:363
#17 0x00647429 in game::load_world_modfiles (this=this@entry=0x801492e8, world=0x80314840) at src/game.cpp:3438
#18 0x0065c0f5 in game::setup (this=0x801492e8) at src/game.cpp:608
#19 0x00437d36 in game::opening_screen (this=<optimized out>) at src/main_menu.cpp:414
#20 0x00a5c568 in main (argc=0, argv=0x28cc60) at src/main.cpp:431
```

This turned out to be from it trying to place f_mutpoppy, a terrain, as a furniture. Pull request that fixes crash and seems correct to me is attached.

This may be related to #14399 as I see the same symptoms, but I can't be sure from the information available.

**Comment by rluddy** [comment]
This was a duplicate of #14399 as I did not look closely enough to see the pull request referenced in that which fixes the same issue.
