### ISSUE TITLE
Launchpad Translation Auto-update is broken.

### ISSUE THREAD

**Issue by cainiaowu** [CleverRaven/Cataclysm-DDA#15474]
2016-02-19 07:20:44 INFO    Starting job.
2016-02-19 07:20:44 INFO    Getting exising bzr branch from central store.
2016-02-19 07:20:44 INFO    [chan bzr SocketAsChannelAdapter] Opened sftp connection (server version 3)
2016-02-19 07:20:44 INFO    35 bytes transferred
2016-02-19 07:21:04 INFO    [chan bzr SocketAsChannelAdapter] Opened sftp connection (server version 3)
2016-02-19 07:21:08 INFO    Importing branch.
2016-02-19 07:21:12 INFO    Counting objects: 33645, done. 0
2016-02-19 07:22:12 INFO    182777164 bytes transferred | Compressing objects 10/10
2016-02-19 07:22:20 INFO    finding revisions to fetch:generating index 0/33645
2016-02-19 07:22:54 INFO    finding revisions to fetch:generating index 0/33645
2016-02-19 07:23:18 INFO    finding revisions to fetch 1/10
2016-02-19 07:23:18 INFO    
Traceback (most recent call last):
  File "/srv/importd.launchpad.net/production/launchpad-rev-17925/scripts/code-import-worker.py", line 96, in <module>
    sys.exit(script.main())
  File "/srv/importd.launchpad.net/production/launchpad-rev-17925/scripts/code-import-worker.py", line 91, in main
    return import_worker.run()
  File "/srv/importd.launchpad.net/production/launchpad-rev-17925/lib/lp/codehosting/codeimport/worker.py", line 583, in run
    return self._doImport()
  File "/srv/importd.launchpad.net/production/launchpad-rev-17925/lib/lp/codehosting/codeimport/worker.py", line 737, in _doImport
    inter_branch.fetch(limit=revision_limit)
  File "/srv/importd.launchpad.net/production/launchpad-rev-17925/bzrplugins/git/branch.py", line 722, in fetch
    self.fetch_objects(stop_revision, fetch_tags=fetch_tags, limit=limit)
  File "/srv/importd.launchpad.net/production/launchpad-rev-17925/bzrplugins/git/branch.py", line 745, in fetch_objects
    determine_wants, self.source.mapping, limit=limit)
  File "/srv/importd.launchpad.net/production/launchpad-rev-17925/bzrplugins/git/fetch.py", line 718, in fetch_objects
    limit)
  File "/srv/importd.launchpad.net/production/launchpad-rev-17925/bzrplugins/git/fetch.py", line 484, in import_git_objects
    mapping.revision_id_foreign_to_bzr)
  File "/srv/importd.launchpad.net/production/launchpad-rev-17925/bzrplugins/git/mapping.py", line 334, in import_commit
    raise UnknownCommitExtra(commit, [item[0] for item in commit.extra])
bzrlib.plugins.git.errors.UnknownCommitExtra: Unknown extra fields in <Commit 92371cdbde119b18b0fcb16df684260f2cec5277>: ['gpgsig'].
Import failed:
Traceback (most recent call last):
Failure: twisted.internet.error.ProcessTerminated: A process has ended with a probable error condition: process ended with exit code 1.

**Comment by VlasovVitaly** [comment]
This is problem on launchpad side.
btw we are(almost all) translating on transifex
