### ISSUE TITLE
Crash when breaking a hairpin while picking a lock

### ISSUE THREAD

**Issue by Maeyanie** [CleverRaven/Cataclysm-DDA#15529]
This is on version 0.C-11142-gfba15ef. After reloading my latest autosave and trying again, the crash repeated itself. But, I've broken them before without a crash, so it's not all the time.

```
Program received signal SIGSEGV, Segmentation fault.
item::is_null (this=this@entry=0x67f67f70) at src/item.cpp:218
218         return (type == nullptr || type == nullitem() || type->id == s_null);
(gdb) print type
$1 = (const itype *) 0xfeeefeeefeeefeee
(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size (this=0xfeeefeeefeeefef6)
    at D:/msys64/mingw64/include/c++/5.3.0/bits/basic_string.h:717
#1  std::operator==<char> (__rhs=..., __lhs=...)
    at D:/msys64/mingw64/include/c++/5.3.0/bits/basic_string.h:4915
#2  item::is_null (this=this@entry=0x67f67f70) at src/item.cpp:218
#3  0x0000000000cc42df in item::is_tool (this=this@entry=0x67f67f70)
    at src/item.cpp:3451
#4  0x0000000000afeaa2 in player::invoke_item (this=this@entry=0x43d12090,
    used=used@entry=0x67f67f70, method=..., pt=...) at src/player.cpp:11029
#5  0x0000000000afeb16 in player::invoke_item (this=0x43d12090,
    used=0x67f67f70, method=...) at src/player.cpp:11008
#6  0x0000000000bd54b6 in game::item_action_menu (this=this@entry=0x619674d0)
    at src/item_action.cpp:261
#7  0x00000000009839c8 in game::handle_action (this=this@entry=0x619674d0)
    at src/game.cpp:3169
#8  0x000000000098517a in game::do_turn (this=0x619674d0) at src/game.cpp:1395
#9  0x0000000000c9aa63 in main (argc=0, argv=0x1750c8) at src/main.cpp:434
(gdb)
```

**Comment by player0981234** [comment]
Fixed in 11144.
