### ISSUE TITLE
Deadlock in SIGINT handler

### ISSUE THREAD

**Issue by lucianposton** [CleverRaven/Cataclysm-DDA#16022]
If the thread is interrupted while holding the message queue lock, it's deadlocked since the signal handler blocks on user input for the "Are you sure? (y/n)" prompt.

I've encountered it 3-4 times in the last few weeks.

```
#0  0x00007f77f4e7458c in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f77f4e6e8d5 in pthread_mutex_lock () from /lib64/libpthread.so.0
#2  0x00007f77f2ba7a93 in _XLockDisplay () from /usr/lib64/libX11.so.6
#3  0x00007f77f2b9b652 in XFlush () from /usr/lib64/libX11.so.6
#4  0x00007f77f51311a2 in X11_PumpEvents () from /usr/lib64/libSDL2-2.0.so.0
#5  0x00007f77f50c82c7 in SDL_PumpEvents_REAL () from /usr/lib64/libSDL2-2.0.so.0
#6  0x00007f77f50c8314 in SDL_WaitEventTimeout_REAL () from /usr/lib64/libSDL2-2.0.so.0
#7  0x000000000049ac4e in CheckMessages () at src/sdltiles.cpp:1117
#8  0x000000000049addb in input_manager::get_input_event (this=0x1496bc0 <inp_mngr>, win=<optimized out>, win@entry=0xdc3b260) at src/sdltiles.cpp:1735
#9  0x000000000049b095 in curses_getch (win=0xdc3b260) at src/sdltiles.cpp:1614
#10 0x00000000009693e6 in wgetch (win=<optimized out>) at src/cursesport.cpp:295
#11 0x00000000009693fb in getch () at src/cursesport.cpp:290
#12 0x0000000000f58b97 in internal_query_yn (mes=<optimized out>, ap=ap@entry=0x7ffe38d51f00) at src/output.cpp:693
#13 0x0000000000f59148 in query_yn (mes=<optimized out>) at src/output.cpp:606
#14 0x0000000000a4dd84 in exit_handler (s=<optimized out>) at src/main.cpp:511
#15 <signal handler called>
#16 0x00007f77f2b93dd0 in pthread_mutex_unlock@plt () from /usr/lib64/libX11.so.6
#17 0x00007f77f2b9b66c in XFlush () from /usr/lib64/libX11.so.6
#18 0x00007f77f51311a2 in X11_PumpEvents () from /usr/lib64/libSDL2-2.0.so.0
#19 0x00007f77f50c82c7 in SDL_PumpEvents_REAL () from /usr/lib64/libSDL2-2.0.so.0
#20 0x00007f77f50c8314 in SDL_WaitEventTimeout_REAL () from /usr/lib64/libSDL2-2.0.so.0
#21 0x000000000049ac4e in CheckMessages () at src/sdltiles.cpp:1117
#22 0x000000000049addb in input_manager::get_input_event (this=this@entry=0x1496bc0 <inp_mngr>, win=<optimized out>, win@entry=0x0) at src/sdltiles.cpp:1735
#23 0x00000000008654ea in input_context::handle_input (this=this@entry=0x7ffe38d53c20) at src/input.cpp:711
#24 0x00000000007a367b in game::handle_mouseview (this=this@entry=0xdd5c130, ctxt=..., action="TIMEOUT") at src/game.cpp:1939
#25 0x00000000007a6491 in game::get_player_input (this=this@entry=0xdd5c130, action="TIMEOUT") at src/game.cpp:2135
#26 0x00000000007ebc4e in game::handle_action (this=this@entry=0xdd5c130) at src/game.cpp:2362
#27 0x00000000007f10f8 in game::do_turn (this=0xdd5c130) at src/game.cpp:1409
#28 0x0000000000a504e4 in main (argc=0, argv=0x7ffe38d54af0) at src/main.cpp:451

```

**Comment by Leland** [comment]
Likely was fixed by #20063. At any rate, we haven't seen any other corroborating reports in the intervening year.
