### ISSUE TITLE
Soldering Iron(UPS) debug message

### ISSUE THREAD

**Issue by Ygdrad** [CleverRaven/Cataclysm-DDA#16287]
I crafted some UPS conversion mods using a ups-modified soldering iron and each time I get the following debug message:

```
DEBUG: Tried to set invalid ammo of none for soldering iron (UPS)
FUNCTION: item& item::ammo_set(const itype_id&, long int)
FILE: src/item.cpp
LINE: 245
```

Edit: I'm also getting it on other ups-powered tools.

**Comment by nanovad** [comment]
Is this related to #16276?

**Comment by codemime** [comment]
It also looks like a variation of #16160.

**Comment by mugling** [comment]
Yes I suspect they're related. Will look into

**Comment by WizardOfOoo** [comment]
Verified.

**Comment by kevingranade** [comment]
Still happening as of 0.C-21858-g9ed9a26

**Comment by Toothspit** [comment]
Can't repro locally, anyone got a save or has this been accidental-fix'd?

**Comment by BrettDong** [comment]
Still reproducible. Attach an UPS conversion mod to a welder, and repair a vehicle part, then the debug message will pop up.

**Comment by kevingranade** [comment]
Grabbed a backtrace from when it's displaying the error:
```
(gdb) bt
#0  0x00007f0864319010 in __read_nocancel () from /usr/lib/libc.so.6
#1  0x00007f0864eb0c3a in _nc_wgetch () from /usr/lib/libncursesw.so.6
#2  0x00007f0864eb1527 in wgetch () from /usr/lib/libncursesw.so.6
#3  0x0000000000765a0c in input_manager::get_input_event (this=0x1764480 <inp_mngr>) at src/input.cpp:1126
#4  0x0000000000766182 in input_manager::get_input_event (this=<optimized out>) at src/input.cpp:1118
#5  0x0000000000f068a9 in realDebugmsg (filename=<optimized out>, filename@entry=0x124dba6 "src/item.cpp", line=<optimized out>, line@entry=0x124e15f "283", funcname=<optimized out>, 
    funcname@entry=0x1250a40 <item::ammo_set(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long)::__PRETTY_FUNCTION__> "item& item::ammo_set(const itype_id&, long int)", mes=mes@entry=0x124c358 "Tried to set invalid ammo of %s for %s") at src/debug.cpp:93
#6  0x0000000000929866 in item::ammo_set (this=this@entry=0x7fff9e665bd0, ammo="null", qty=<optimized out>, qty@entry=300) at src/item.cpp:283
#7  0x000000000092c7ad in item::<lambda(item*)>::operator()(item *) const (__closure=0x9fe5640, e=<optimized out>) at src/item.cpp:5167
#8  0x000000000092c9b1 in std::_Function_handler<VisitResponse(item*), item::use_charges(const itype_id&, long int&, std::__debug::list<item>&, const tripoint&)::<lambda(item*)> >::_M_invoke(const std::_Any_data &, item *&&) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/7.1.1/bits/std_function.h:302
#9  0x0000000000d3f64c in std::function<VisitResponse (item*)>::operator()(item*) const (this=<optimized out>, __args#0=<optimized out>) at /usr/include/c++/7.1.1/bits/std_function.h:706
#10 0x0000000000d3f665 in visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}::operator()(item*, item*) const (it=<optimized out>, __closure=<optimized out>) at src/visitable.cpp:336
#11 std::_Function_handler<VisitResponse (item*, item*), visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}>::_M_invoke(std::_Any_data const&, item*&&, std::_Any_data const&) (__functor=..., __args#0=<optimized out>, __args#1=<optimized out>)
    at /usr/include/c++/7.1.1/bits/std_function.h:302
#12 0x0000000000d3ea81 in std::function<VisitResponse (item*, item*)>::operator()(item*, item*) const (this=this@entry=0x7fff9e665f40, __args#0=<optimized out>, __args#0@entry=0x7718bb0, __args#1=<optimized out>, __args#1@entry=0x0) at /usr/include/c++/7.1.1/bits/std_function.h:706
#13 0x0000000000d32175 in visit_internal(const std::function<VisitResponse(item*, item*)> &, item *, item *) (func=..., node=node@entry=0x7718bb0, parent=parent@entry=0x0) at src/visitable.cpp:344
#14 0x0000000000d32297 in visitable<item>::visit_items(std::function<VisitResponse (item*, item*)> const&) (this=this@entry=0x7718bb0, func=...) at src/visitable.cpp:375
#15 0x0000000000d3f71f in visitable<item>::visit_items(std::function<VisitResponse (item*)> const&) (this=this@entry=0x7718bb0, func=...) at src/visitable.cpp:336
#16 0x00000000008f9c40 in item::use_charges (this=this@entry=0x7718bb0, what="welder", qty=@0x7fff9e6665a8: 0, used=empty std::__debug::list, pos=...) at src/item.cpp:5156
#17 0x0000000000c42f38 in player::<lambda(item*)>::operator() (e=<optimized out>, __closure=0x957a6d0) at src/player.cpp:6985
#18 std::_Function_handler<VisitResponse(item*), player::use_charges(const itype_id&, long int)::<lambda(item*)> >::_M_invoke(const std::_Any_data &, item *&&) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/7.1.1/bits/std_function.h:302
#19 0x0000000000d3f64c in std::function<VisitResponse (item*)>::operator()(item*) const (this=<optimized out>, __args#0=<optimized out>) at /usr/include/c++/7.1.1/bits/std_function.h:706
#20 0x0000000000d3f68d in visitable<Character>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}::operator()(item*, item*) const (it=<optimized out>, __closure=<optimized out>) at src/visitable.cpp:336
#21 std::_Function_handler<VisitResponse (item*, item*), visitable<Character>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}>::_M_invoke(std::_Any_data const&, item*&&, std::_Any_data const&) (__functor=..., __args#0=<optimized out>, __args#1=<optimized out>)
    at /usr/include/c++/7.1.1/bits/std_function.h:302
#22 0x0000000000d3ea81 in std::function<VisitResponse (item*, item*)>::operator()(item*, item*) const (this=this@entry=0x7fff9e666570, __args#0=<optimized out>, __args#0@entry=0x7718bb0, __args#1=<optimized out>, __args#1@entry=0x0) at /usr/include/c++/7.1.1/bits/std_function.h:706
#23 0x0000000000d32175 in visit_internal(const std::function<VisitResponse(item*, item*)> &, item *, item *) (func=..., node=0x7718bb0, parent=parent@entry=0x0) at src/visitable.cpp:344
#24 0x0000000000d326ec in visitable<inventory>::visit_items(std::function<VisitResponse (item*, item*)> const&) (this=this@entry=0x2d644e8, func=...) at src/visitable.cpp:386
#25 0x0000000000d32a21 in visitable<Character>::visit_items(std::function<VisitResponse (item*, item*)> const&) (this=this@entry=0x2d64310, func=...) at src/visitable.cpp:412
#26 0x0000000000d403cb in visitable<Character>::visit_items(std::function<VisitResponse (item*)> const&) (this=this@entry=0x2d64310, func=...) at src/visitable.cpp:336
#27 0x0000000000c49738 in player::use_charges (this=this@entry=0x2d64310, what="welder", qty=<optimized out>) at src/player.cpp:6984
#28 0x0000000000bdf11b in player::consume_tools (this=this@entry=0x2d64310, tool=..., batch=batch@entry=1) at src/crafting.cpp:914
#29 0x0000000000bea3ba in player::consume_tools (this=this@entry=0x2d64310, tools=std::__debug::vector of length 4, capacity 4 = {...}, batch=batch@entry=1, hotkeys="1234567890abcdefghijklmnopqrstuvwxyz") at src/crafting.cpp:932
#30 0x000000000056b099 in veh_utils::repair_part (veh=..., pt=..., who_c=...) at src/veh_utils.cpp:124
#31 0x00000000007a7634 in veh_interact::complete_vehicle () at src/veh_interact.cpp:2391
#32 0x0000000000f1af79 in activity_handlers::vehicle_finish (act=0x2d64f60, pl=<optimized out>) at src/activity_handlers.cpp:1371
#33 0x0000000000f2e9e2 in std::_Function_handler<void (player_activity*, player*), void (*)(player_activity*, player*)>::_M_invoke(std::_Any_data const&, player_activity*&&, player*&&) (__functor=..., __args#0=<optimized out>, __args#1=<optimized out>) at /usr/include/c++/7.1.1/bits/std_function.h:316
#34 0x0000000000421841 in std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const (this=<optimized out>, __args#0=<optimized out>, __args#0@entry=0x2d64f60, __args#1=<optimized out>, __args#1@entry=0x2d64310) at /usr/include/c++/7.1.1/bits/std_function.h:706
#35 0x000000000041f890 in activity_type::call_finish (this=<optimized out>, act=act@entry=0x2d64f60, p=p@entry=0x2d64310) at src/activity_type.cpp:94
#36 0x00000000005628bc in player_activity::do_turn (this=0x2d64f60, p=0x2d64310) at src/player_activity.cpp:131
#37 0x000000000047a6df in game::process_activity (this=this@entry=0x2d09140) at src/game.cpp:1668
#38 0x00000000004b5b0b in game::do_turn (this=0x2d09140) at src/game.cpp:1451
#39 0x000000000099f757 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:499
```

**Comment by kevingranade** [comment]
Normally the code recurses into inventory->item->contents until it reaches a stack of batteries.
With the UPS mod, the tool has a charge hacked in, but not an ammo type.
I'm looking into setting the ammotype when the mod is added.
