### ISSUE TITLE
Crash immediately after firing gun

### ISSUE THREAD

**Issue by mugling** [CleverRaven/Cataclysm-DDA#17372]
`Assertion failed: (!line.empty() && line.front() != line.back()), function slope_of, file src/line.cpp, line 321.`

**Comment by Coolthulhu** [comment]
Can't reproduce, needs instructions.

**Comment by mugling** [comment]
It's unfortunately not reproducible. Hopefully whoever added the assertion can point is towards constructing a suitable test case.

**Comment by Coolthulhu** [comment]
What is the stacktrace?

It most likely happened when range was `<=0`.

**Comment by mugling** [comment]
From the core dump
```
#3  0x0000000803a5df31 in __assert () from /lib/libc.so.7
#4  0x00000000006cf20c in slope_of (line=@0x7fffffff6190) at src/line.cpp:321
#5  0x00000000006cf988 in move_along_line (loc=@0x7fffffff7350, line=@0x7fffffff6190, distance=2) at src/line.cpp:350
#6  0x0000000001132969 in Creature::projectile_attack (this=0x804eafa00, proj_arg=@0x7fffffff7288, source=@0x804eb04e0, 
    target_arg=@0x7fffffff73f0, shot_dispersion=8026.666666666667) at src/ranged.cpp:304
#7  0x000000000112ff3d in Creature::projectile_attack (this=0x804eafa00, proj=@0x7fffffff7288, target=@0x7fffffff73f0, 
    shot_dispersion=8026.666666666667) at src/ranged.cpp:62
#8  0x0000000001137a0f in player::fire_gun (this=0x804eafa00, target=@0x7fffffff7e98, shots=1, gun=@0x804eafce8)
    at src/ranged.cpp:488
#9  0x00000000007aa34f in game::plfire (this=0x804cbb200, default_target=@0x7fffffffa8b8) at src/game.cpp:10805
#10 0x000000000076a598 in game::handle_action (this=0x804cbb200) at src/game.cpp:2875
#11 0x0000000000761876 in game::do_turn (this=0x804cbb200) at src/game.cpp:1407
#12 0x0000000001afa8df in main (argc=0, argv=0x7fffffffe950) at src/main.cpp:468
```

**Comment by Coolthulhu** [comment]
That shot dispersion is giant. Sounds like the miss trajectory recalculation caused the trajectory length to drop to 0 (or 1?), which would trigger the assertion.
