### ISSUE TITLE
"Tried to set invalid ammo of none for welder+ (UPS)"

### ISSUE THREAD

**Issue by mutability** [CleverRaven/Cataclysm-DDA#18931]
Debug error while repairing a car with a UPS welder.

stacktrace:

```
#0  realDebugmsg (filename=filename@entry=0x110533e "src/item.cpp", line=line@entry=0x1105914 "279", 
    funcname=funcname@entry=0x1107720 <item::ammo_set(std::string const&, long)::__PRETTY_FUNCTION__> "item& item::ammo_set(const itype_id&, long int)", 
    mes=mes@entry=0x1103b08 "Tried to set invalid ammo of %s for %s") at src/debug.cpp:51
#1  0x000000000084ba91 in item::ammo_set (this=this@entry=0x7fffffff5440, ammo="null", qty=qty@entry=100) at src/item.cpp:279
#2  0x000000000084cbc2 in item::__lambda62::operator() (__closure=0x237b3730, e=0x24919620) at src/item.cpp:4996
#3  0x000000000084ce27 in std::_Function_handler<VisitResponse(item*), item::use_charges(const itype_id&, long int&, std::__debug::list<item>&, const tripoint&)::__lambda62>::_M_invoke(const std::_Any_data &, item *) (__functor=..., __args#0=<optimised out>) at /usr/include/c++/4.8/functional:2057
#4  0x0000000001057e46 in std::function<VisitResponse (item*)>::operator()(item*) const (this=<optimised out>, __args#0=<optimised out>) at /usr/include/c++/4.8/functional:2471
#5  0x0000000001057e5a in operator() (it=<optimised out>, __closure=<optimised out>) at src/visitable.cpp:300
#6  std::_Function_handler<VisitResponse (item*, item*), visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}>::_M_invoke(std::_Any_data const&, item*, item*) (__functor=..., __args#0=<optimised out>, __args#1=<optimised out>) at /usr/include/c++/4.8/functional:2057
#7  0x0000000001056fb6 in std::function<VisitResponse (item*, item*)>::operator()(item*, item*) const (this=this@entry=0x7fffffff5bc0, __args#0=__args#0@entry=0x24919620, __args#1=__args#1@entry=0x0)
    at /usr/include/c++/4.8/functional:2471
#8  0x000000000104ad20 in visit_internal(const std::function<VisitResponse(item*, item*)> &, item *, item *) (func=..., node=node@entry=0x24919620, parent=parent@entry=0x0) at src/visitable.cpp:308
#9  0x000000000104af71 in visitable<item>::visit_items(std::function<VisitResponse (item*, item*)> const&) (this=this@entry=0x24919620, func=...) at src/visitable.cpp:339
#10 0x0000000001057f61 in visitable<item>::visit_items(std::function<VisitResponse (item*)> const&) (this=this@entry=0x24919620, func=...) at src/visitable.cpp:300
Python Exception <class 'IndexError'> list index out of range: 
#11 0x0000000000824c79 in item::use_charges (this=0x24919620, what="welder", qty=@0x7fffffff7c08: 0, used=empty std::__debug::list, pos=...) at src/item.cpp:5022
#12 0x0000000000e3cd2e in operator() (e=0x24919620, __closure=0x2351f290) at src/player.cpp:9203
#13 std::_Function_handler<VisitResponse(item*), player::use_charges(const itype_id&, long int)::__lambda42>::_M_invoke(const std::_Any_data &, item *) (__functor=..., __args#0=<optimised out>)
    at /usr/include/c++/4.8/functional:2057
#14 0x0000000001057e46 in std::function<VisitResponse (item*)>::operator()(item*) const (this=<optimised out>, __args#0=<optimised out>) at /usr/include/c++/4.8/functional:2471
#15 0x0000000001057e82 in operator() (it=<optimised out>, __closure=<optimised out>) at src/visitable.cpp:300
#16 std::_Function_handler<VisitResponse (item*, item*), visitable<Character>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}>::_M_invoke(std::_Any_data const&, item*, item*) (__functor=..., __args#0=<optimised out>, __args#1=<optimised out>) at /usr/include/c++/4.8/functional:2057
#17 0x0000000001056fb6 in std::function<VisitResponse (item*, item*)>::operator()(item*, item*) const (this=this@entry=0x7fffffff7ba0, __args#0=__args#0@entry=0x24919620, __args#1=__args#1@entry=0x0)
    at /usr/include/c++/4.8/functional:2471
#18 0x000000000104ad20 in visit_internal(const std::function<VisitResponse(item*, item*)> &, item *, item *) (func=..., node=0x24919620, parent=parent@entry=0x0) at src/visitable.cpp:308
#19 0x000000000104b5ff in visitable<inventory>::visit_items(std::function<VisitResponse (item*, item*)> const&) (this=this@entry=0x1685b9f8, func=...) at src/visitable.cpp:349
#20 0x000000000104ba0d in visitable<Character>::visit_items(std::function<VisitResponse (item*, item*)> const&) (this=this@entry=0x1685b850, func=...) at src/visitable.cpp:374
#21 0x0000000001058eb1 in visitable<Character>::visit_items(std::function<VisitResponse (item*)> const&) (this=this@entry=0x1685b850, func=...) at src/visitable.cpp:300
#22 0x0000000000df0d13 in player::use_charges (this=this@entry=0x1685b850, what="welder", qty=0) at src/player.cpp:9207
#23 0x00000000005dacac in player::consume_tools (this=this@entry=0x1685b850, tool=..., batch=batch@entry=1) at src/crafting.cpp:1011
#24 0x00000000005e055b in player::consume_tools (this=0x1685b850, tools=std::__debug::vector of length 4, capacity 4 = {...}, batch=batch@entry=1, hotkeys="1234567890abcdefghijklmnopqrstuvwxyz")
    at src/crafting.cpp:1029
#25 0x00000000010315de in veh_interact::complete_vehicle () at src/veh_interact.cpp:2326
#26 0x000000000041e41b in activity_handlers::vehicle_finish (act=0x1685c370, pl=<optimised out>) at src/activity_handlers.cpp:1219
#27 0x0000000000dc25fa in player_activity::finish (this=this@entry=0x1685c370, p=p@entry=0x1685b850) at src/player_activity.cpp:445
#28 0x0000000000dc38a6 in player_activity::do_turn (this=0x1685c370, p=0x1685b850) at src/player_activity.cpp:391
#29 0x000000000072a49e in game::process_activity (this=this@entry=0x13142e10) at src/game.cpp:1658
#30 0x000000000076767c in game::do_turn (this=0x13142e10) at src/game.cpp:1453
#31 0x00000000009858ad in main (argc=0, argv=0x7fffffffdbc0) at src/main.cpp:468
```

**Comment by Coolthulhu** [comment]
Probably related to how UPS is now a "magazine" rather than just a flag.

**Comment by illi-kun** [comment]
Welder with UPS mod works file for me. Maybe #18948 fixes that?
