### ISSUE TITLE
Segfault while batching clean water in vehicle

### ISSUE THREAD

**Issue by Hellrazor236** [CleverRaven/Cataclysm-DDA#19789]
See the attached save, the build is from sometime around 2016-12-08. I'll try it in a newer build tomorrow.
```
/usr/include/c++/6/debug/safe_iterator.h:298:
Error: attempt to increment a singular iterator.

Objects involved in the operation:
    iterator "this" @ 0x0x7fff4eaee130 {
      type = __gnu_debug::_Safe_iterator<std::__cxx1998::_List_const_iterator<item>, std::__debug::list<item, std::allocator<item> > > (constant iterator);
      state = singular;
      references sequence with type 'std::__debug::list<item, std::allocator<item> >' @ 0x0x55e1de0f4cc8
    }
Aborted
```
[Pyatts.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/658572/Pyatts.zip)

**Comment by Aivean** [comment]
I confirm. One note thought: to reproduce try crafting "clean water" batch of 20.  With smaller batch crash didn't happen.

**Comment by Hellrazor236** [comment]
I think what's happening is that it takes all the water from one tank, but doesn't properly switch over to the other one when the first runs out.

**Comment by Hellrazor236** [comment]
The newest commit (0.C-20251-g9cc82f1) exhibits the same behavior.
Backtrace from GDB:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff63ee40a in __GI_abort () at abort.c:89
#2  0x00007ffff6d2a3b3 in __gnu_debug::_Error_formatter::_M_error() const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000555555b9084c in __gnu_debug::_Safe_iterator<std::__cxx1998::_List_const_iterator<item>, std::__debug::list<item, std::allocator<item> > >::operator++ (this=0x7fffffffc080)
    at /usr/include/c++/6/debug/safe_iterator.h:296
#4  map::use_charges (this=<optimized out>, origin=..., range=range@entry=6, type="water", quantity=@0x7fffffffc748: 1) at src/map.cpp:5087
#5  0x0000555555f33db4 in player::consume_items (this=0x555563ad5ce0, is=..., batch=<optimized out>) at src/crafting.cpp:879
#6  0x0000555555fde33d in craft_command::consume_components (this=0x55556310fe10) at src/craft_command.cpp:151
#7  0x0000555555f36fe2 in player::complete_craft (this=0x555563ad5ce0) at src/crafting.cpp:629
#8  0x00005555562018a0 in activity_handlers::craft_finish (act=0x555563ad6928, p=<optimized out>) at src/activity_handlers.cpp:1910
#9  0x000055555620dd0a in std::_Function_handler<void (player_activity*, player*), void (*)(player_activity*, player*)>::_M_invoke(std::_Any_data const&, player_activity*&&, player*&&) (__functor=..., 
    __args#0=<optimized out>, __args#1=<optimized out>) at /usr/include/c++/6/functional:1740
#10 0x00005555557049e3 in std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const (this=<optimized out>, __args#0=<optimized out>, __args#0@entry=0x555563ad6928, 
    __args#1=<optimized out>, __args#1@entry=0x555563ad5ce0) at /usr/include/c++/6/functional:2136
#11 0x0000555555700a63 in activity_type::call_finish (this=<optimized out>, act=act@entry=0x555563ad6928, p=p@entry=0x555563ad5ce0) at src/player_activity.cpp:102
#12 0x0000555555703c79 in player_activity::do_turn (this=this@entry=0x555563ad6928, p=p@entry=0x555563ad5ce0) at src/player_activity.cpp:201
#13 0x0000555555c66a1a in game::process_activity (this=this@entry=0x55556306d550) at src/game.cpp:1655
#14 0x0000555555ca5767 in game::do_turn (this=0x55556306d550) at src/game.cpp:1449
#15 0x0000555555cdd463 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:491
```

It definitely gets caused by not switching to the other tank. Tank 5 has 1.75 liters of water (7 waters) and it runs fine if you batch 7 or fewer clean waters, but batching 8 or more requires switching to tank 6 and crashes hard.

**Comment by remyroy** [comment]
I'm looking into it right now.

**Comment by remyroy** [comment]
For some reason, this segfault comes from doing a for..each on an empty list. I'm not sure what is wrong here. I might check again later.

**Comment by keyspace** [comment]
Cause of segfault described in PR above. PR solves this issue, but not the underlying cause.
