### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by dvolk** [CleverRaven/Cataclysm-DDA#22553]
Game version: 39f6c7b549d79c531e3fb0aeac499ae9840fa5b6

Operating system: Ubuntu 17.04

Tiles or curses: tiles

Mods active: no

### Expected behavior
no crash
### Actual behavior
crash
### Steps to reproduce the behavior
build with CURSES=0 SOUND=1 TILES=1 USE_HOME_DIR=0 make
```
$ gdb ./cataclysm-tiles
GNU gdb (Ubuntu 7.12.50.20170314-0ubuntu1.1) 7.12.50.20170314-git
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./cataclysm-tiles...done.
(gdb) r
Starting program: /media/dv/games/Cataclysm-DDA/cataclysm-tiles 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffee201700 (LWP 1804)]
[New Thread 0x7ffff7ec2700 (LWP 1805)]
[New Thread 0x7ffff7e81700 (LWP 1806)]
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT
Failed to map mcs buffer into GTT

Thread 1 "cataclysm-tiles" received signal SIGSEGV, Segmentation fault.
0x00007fffebbd5fea in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
(gdb) bt
#0  0x00007fffebbd5fea in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#1  0x00007fffeb936a47 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#2  0x00007fffeb937840 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#3  0x00007ffff78c64e4 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#4  0x00007ffff78bf643 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#5  0x00007ffff78bf91b in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
#6  0x00005555556db991 in cata_tiles::load_tileset (this=this@entry=0x555558b16100, img_path="gfx//ChestHoleTileset/fallback.png", R=R@entry=-1, G=G@entry=-1, 
    B=B@entry=-1, sprite_width=sprite_width@entry=24, sprite_height=24) at src/cata_tiles.cpp:424
#7  0x00005555556e5b7d in cata_tiles::load_tilejson_from_file (this=this@entry=0x555558b16100, tileset_dir="gfx//ChestHoleTileset", f=..., 
    image_path="gfx//ChestHoleTileset/tiles.png") at src/cata_tiles.cpp:552
#8  0x00005555556e7005 in cata_tiles::load_tilejson (this=this@entry=0x555558b16100, tileset_root="gfx//ChestHoleTileset", json_conf="tile_config.json", 
    image_path="tiles.png") at src/cata_tiles.cpp:498
#9  0x00005555556e7a3d in cata_tiles::init (this=0x555558b16100) at src/cata_tiles.cpp:221
#10 0x00005555565416fa in catacurses::init_interface () at src/sdltiles.cpp:1543
#11 0x0000555555cff2fe in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:441
(gdb) bt full
#0  0x00007fffebbd5fea in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
No symbol table info available.
#1  0x00007fffeb936a47 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
No symbol table info available.
#2  0x00007fffeb937840 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
No symbol table info available.
#3  0x00007ffff78c64e4 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#4  0x00007ffff78bf643 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#5  0x00007ffff78bf91b in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0
No symbol table info available.
#6  0x00005555556db991 in cata_tiles::load_tileset (this=this@entry=0x555558b16100, img_path="gfx//ChestHoleTileset/fallback.png", R=R@entry=-1, G=G@entry=-1, 
    B=B@entry=-1, sprite_width=sprite_width@entry=24, sprite_height=24) at src/cata_tiles.cpp:424
        tile_surf = std::unique_ptr<SDL_Surface> containing 0x555560d615a0
        tile_tex = std::unique_ptr<SDL_Texture> containing 0x0
        shadow_tile_tex = std::unique_ptr<SDL_Texture> containing 0x0
        night_tile_tex = std::unique_ptr<SDL_Texture> containing 0x0
        overexposed_tile_tex = std::unique_ptr<SDL_Texture> containing 0x0
        x = 120
        y = 2616
        tile_atlas = std::unique_ptr<SDL_Surface> containing 0x5555590c0f00
        shadow_tile_atlas = std::unique_ptr<SDL_Surface> containing 0x55555953b850
        nightvision_tile_atlas = std::unique_ptr<SDL_Surface> containing 0x5555590c1ac0
        overexposed_tile_atlas = std::unique_ptr<SDL_Surface> containing 0x5555595405c0
        w = <optimized out>
        h = <optimized out>
        sx = 384
        sy = 6144
        source_rect = {x = 120, y = 2616, w = 24, h = 24}
        dest_rect = {x = 0, y = 0, w = 24, h = 24}
        tilecount = 1749
#7  0x00005555556e5b7d in cata_tiles::load_tilejson_from_file (this=this@entry=0x555558b16100, tileset_dir="gfx//ChestHoleTileset", f=..., 
    image_path="gfx//ChestHoleTileset/tiles.png") at src/cata_tiles.cpp:552
        G = <optimized out>
        tile_part_def = {positions = std::__debug::map with 6 elements = {["ascii"] = 1205742, ["file"] = 1205692, ["sprite_height"] = 0, ["sprite_width"] = 0, 
            ["tiles"] = 1205723, ["transparency"] = 0}, start = 1205677, end = 1207328, final_separator = false, jsin = 0x7fffffffcb40}
        R = <optimized out>
        B = -1
        sprite_width = <optimized out>
        newsize = <optimized out>
        sprite_offset_x = <optimized out>
        tileset_image_path = "gfx//ChestHoleTileset/fallback.png"
        sprite_height = <optimized out>
        sprite_offset_y = <optimized out>
---Type <return> to continue, or q <return> to quit---
        tiles_new = {positions = std::__debug::vector of length 4, capacity 4 = {95, 1188082, 1198011, 1205677}, start = 88, index = 4, end = 1207330, 
          final_separator = false, jsin = 0x7fffffffcb40}
        config_json = {stream = 0x7fffffffd1a0, ate_separator = true}
        config = {positions = std::__debug::map with 2 elements = {["tile_info"] = 16, ["tiles-new"] = 88}, start = 0, end = -1, final_separator = false, 
          jsin = 0x7fffffffcb40}
        info = {positions = std::__debug::vector of length 1, capacity 1 = {23}, start = 16, index = 1, end = 73, final_separator = true, jsin = 0x7fffffffcb40}
        offset = 6400
#8  0x00005555556e7005 in cata_tiles::load_tilejson (this=this@entry=0x555558b16100, tileset_root="gfx//ChestHoleTileset", json_conf="tile_config.json", 
    image_path="tiles.png") at src/cata_tiles.cpp:498
        json_path = "gfx//ChestHoleTileset/tile_config.json"
        img_path = "gfx//ChestHoleTileset/tiles.png"
        config_file = <incomplete type>
#9  0x00005555556e7a3d in cata_tiles::init (this=0x555558b16100) at src/cata_tiles.cpp:221
        default_json = "tile_config.json"
        default_tileset = "tinytile.png"
        current_tileset = "ChestHole"
        json_path = "tile_config.json"
        tileset_path = "tiles.png"
        config_path = "gfx//ChestHoleTileset"
#10 0x00005555565416fa in catacurses::init_interface () at src/sdltiles.cpp:1543
        fl = {fontblending = false, typeface = "unifont", map_typeface = "unifont", overmap_typeface = "unifont", fontwidth = 8, fontheight = 16, fontsize = 16, 
          map_fontwidth = 8, map_fontheight = 16, map_fontsize = 16, overmap_fontwidth = 8, overmap_fontheight = 16, overmap_fontsize = 16}
#11 0x0000555555cff2fe in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:441
        seed = 1512313350
        verifyexit = false
        check_mods = false
        dump = ""
        dmode = dump_mode::TSV
        opts = std::__debug::vector of length 0, capacity 0
        world = ""
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        sigIntHandler = {__sigaction_handler = {sa_handler = 0x5555566a548c, sa_sigaction = 0x5555566a548c}, sa_mask = {__val = {0, 93825010389304, 93825010390056, 
              93825006645769, 140737488345688, 93825000259363, 93825000260101, 93825010390168, 93825010390178, 93825010389352, 0, 93825006645792, 93825006645769, 
              93825000259395, 93825000266081, 93825010390195}}, sa_flags = 1449809058, sa_restorer = 0x5555566a54bd}
        lang = <error: Cannot access memory at address 0xb>
        v = <optimized out>
(gdb) 
```

**Comment by Zireael07** [comment]
Lemme guess, a Skylake Intel GPU?

**Comment by dvolk** [comment]
Oh, ok. I was sure this was a new problem so I didn't look that far back

dupe of #21317
