### ISSUE TITLE
basic_string::substr: appears in @ menu

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#22643]
![screenshot 458](https://user-images.githubusercontent.com/18560216/34143467-77427e8e-e452-11e7-87f6-6db0abe3779a.png)

There's also a blank line in the perception subscreen, though that is probably intended.

**Comment by AMurkin** [comment]
Next [source lines](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player_display.cpp#L699) after perception output:
```c++
mvwprintz( w_stats, 8, 1, c_magenta, _( "Throwing penalty per target's dodge: +%d" ) );
mvwprintz( w_stats, 8, 22, c_magenta, "%3d", throw_dispersion_per_dodge( false ) );
```
That is ` +%d`.

**Comment by woutershep** [comment]
This actually causes a crash on my system the moment i select dexterity in the @ menu.

```
>>> bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7a6c14a in __GI_abort () at abort.c:89
#2  0x0000555555edc008 in _Unwind_SetGR (context=<optimized out>, index=<optimized out>, val=<optimized out>) at /var/tmp/paludis/build/sys-devel-gcc-6.4.0/work/gcc-6.4.0/libgcc/unwind-dw2.c:271
#3  0x0000555555edf708 in __gcc_personality_v0 (version=<optimized out>, actions=<optimized out>, exception_class=<optimized out>, ue_header=0x5555569e3ab0, context=0x7fffffffb870) at /var/tmp/paludis/build/sys-devel-gcc-6.4.0/work/gcc-6.4.0/libgcc/unwind-c.c:230
#4  0x00007ffff732aef6 in _Unwind_RaiseException_Phase2 (exc=exc@entry=0x5555569e3ab0, context=context@entry=0x7fffffffb870) at /var/tmp/paludis/build/sys-devel-gcc-7.1.0-r1/work/gcc-7.1.0/libgcc/unwind.inc:62
#5  0x00007ffff732b6f1 in _Unwind_RaiseException (exc=0x5555569e3ab0) at /var/tmp/paludis/build/sys-devel-gcc-7.1.0-r1/work/gcc-7.1.0/libgcc/unwind.inc:131
#6  0x00007ffff726a2f6 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x5555569e3ad0, tinfo=0x7ffff756da58 <typeinfo for std::out_of_range>, dest=0x7ffff7285040 <std::out_of_range::~out_of_range()>) at /var/tmp/paludis/build/sys-libs-libstdc++-7.1.0/work/gcc-7.1.0/libstdc++-v3/libsupc++/eh_throw.cc:88
#7  0x00007ffff729dc1f in std::__throw_out_of_range_fmt (__fmt=__fmt@entry=0x7ffff7332978 "%s: __pos (which is %zu) > this->size() (which is %zu)") at /var/tmp/paludis/build/sys-libs-libstdc++-7.1.0/work/gcc-7.1.0/libstdc++-v3/src/c++11/functexcept.cc:96
#8  0x00007ffff72bcca2 in std::string::_M_check (__s=0x7ffff73363f0 "basic_string::substr", __pos=<optimized out>, this=<optimized out>) at /var/tmp/paludis/build/sys-libs-libstdc++-7.1.0/work/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:3230
#9  std::string::substr (this=<optimized out>, __pos=<optimized out>, __n=<optimized out>) at /var/tmp/paludis/build/sys-libs-libstdc++-7.1.0/work/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:5466
#10 0x0000555555d91635 in cata::string_formatter::throw_error (this=this@entry=0x7fffffffc030, msg=Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/lib/../../share/gdb/python/libstdcxx/v6/printers.py", line 756, in to_string
    ptr = self.val ['_M_dataplus']['_M_p']
gdb.error: There is no member named _M_dataplus.
) at src/string_formatter.cpp:106
#11 0x00005555556a77f5 in get_nth_arg_as (requested=0, this=0x7fffffffc030) at src/string_formatter.h:229
#12 read_conversion (format_arg_index=0, this=0x7fffffffc030) at src/string_formatter.h:268
#13 parse (this=0x7fffffffc030) at src/string_formatter.h:341
#14 string_format<>(std::string) (format=<incomplete type>) at src/string_formatter.h:379
#15 0x00005555556db75e in string_format<>(char const*) (format=0x555555f22ea8 "Throwing penalty per target's dodge: +%d") at src/string_formatter.h:388
#16 mvwprintz<>(void*, int, int, nc_color, char const*) (w=0x5555569e19c0, y=8, x=1, FG=..., mes=0x555555f22ea8 "Throwing penalty per target's dodge: +%d") at src/output.h:291
#17 0x00005555558f2d6d in player::disp_info (this=<optimized out>) at src/player_display.cpp:699
#18 0x0000555555920faa in game::handle_action (this=0x555556864bb0) at src/game.cpp:3338
#19 0x000055555592260d in game::do_turn (this=0x555556864bb0) at src/game.cpp:1474
#20 0x0000555555924436 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:522
```

Can confirm that PR #22651 fixes it. Althought i have to mention that the text doesn't even come close to actually fitting in the tiny box and is truncated gracefully.
