### ISSUE TITLE
Game crashes after random character creation 

### ISSUE THREAD

**Issue by BorkBorkGoesTheCode** [CleverRaven/Cataclysm-DDA#22828]
Game version:
0.C 26014

Operating system:
Windows

Mods active:
Dark Days Ahead
More Locations
Urban Development
Beta National Guard Camp
Mining Mod (The current version found here: https://github.com/DangerNoodle/mining-mod)
Craftable Gun Pack

I cannot recreate the initial crash, but whenever a character is generated in the attached world, the game stalls. A message referencing Microsoft Visual C appeared in addition to an ordinary debug message (I don't remember either messages).
[Turner Corner.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/1675365/Turner.Corner.zip)

**Comment by BorkBorkGoesTheCode** [comment]
Still can't get the first error message to repeat, but all random characters spawned in worlds with cities set to 0 stop responding after character generation regardless of mods.

**Comment by BrettDong** [comment]
Probably useful for someone:
The game freezes on Linux, and the back trace is:
```
^C
Program received signal SIGINT, Interrupt.
0x00007f249496567d in std::_Hash_bytes(void const*, unsigned long, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007f249496567d in std::_Hash_bytes(void const*, unsigned long, unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007f249498baf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f249498c5f9 in __gnu_debug::_Safe_sequence_base::_M_get_mutex() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f249498c8b7 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x000056483487494e in __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<overmap_special_placement*, std::__cxx1998::vector<overmap_special_placement, std::allocator<overmap_special_placement> > >, std::__debug::vector<overmap_special_placement, std::allocator<overmap_special_placement> > >::_M_attach (__seq=<optimized out>, this=0x7ffd8e9b1380)
    at /usr/include/c++/6/debug/safe_iterator.h:418
#5  __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<overmap_special_placement*, std::__cxx1998::vector<overmap_special_placement, std::allocator<overmap_special_placement> > >, std::__debug::vector<overmap_special_placement, std::allocator<overmap_special_placement> > >::_Safe_iterator (this=0x7ffd8e9b1380, __x={instances_placed = 0, special_details = 0x5648382129f0})
    at /usr/include/c++/6/debug/safe_iterator.h:150
#6  0x000056483485713c in std::random_shuffle<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<overmap_special_placement*, std::__cxx1998::vector<overmap_special_placement, std::allocator<overmap_special_placement> > >, std::__debug::vector<overmap_special_placement, std::allocator<overmap_special_placement> > > > (
    __last=<error reading variable: access outside bounds of object referenced via synthetic pointer>, __first={instances_placed = 999283184, special_details = 0x7ffd8e9b3cb0})
    at /usr/include/c++/6/bits/stl_algo.h:4453
#7  overmap::place_special_attempt (this=this@entry=0x7f24925d3010, enabled_specials=..., sector=..., place_optional=place_optional@entry=true) at src/overmap.cpp:4301
#8  0x0000564834857a9f in overmap::place_specials_pass (this=this@entry=0x7f24925d3010, enabled_specials=..., sectors=std::__debug::vector of length 144, capacity 144 = {...}, 
    place_optional=place_optional@entry=true) at src/overmap.cpp:4340
#9  0x00005648348589ae in overmap::place_specials (this=this@entry=0x7f24925d3010, enabled_specials=...) at src/overmap.cpp:4418
#10 0x000056483485de4e in overmap::generate (this=this@entry=0x7f24925d3010, north=<optimized out>, east=east@entry=0x0, south=south@entry=0x0, west=west@entry=0x0, enabled_specials=...)
    at src/overmap.cpp:1704
#11 0x000056483485e513 in overmap::open (this=this@entry=0x7f24925d3010, enabled_specials=...) at src/overmap.cpp:4547
#12 0x000056483485e605 in overmap::populate (this=this@entry=0x7f24925d3010, enabled_specials=...) at src/overmap.cpp:1177
#13 0x0000564834c5ec7c in overmapbuffer::create_custom_overmap (this=<optimized out>, x=<optimized out>, y=<optimized out>, specials=...) at src/overmapbuffer.cpp:96
#14 0x0000564834858df3 in overmap::place_specials (this=this@entry=0x7f24929b9010, enabled_specials=...) at src/overmap.cpp:4412
#15 0x000056483485de4e in overmap::generate (this=this@entry=0x7f24929b9010, north=<optimized out>, east=east@entry=0x0, south=south@entry=0x0, west=west@entry=0x7f2493739010, enabled_specials=...)
    at src/overmap.cpp:1704
#16 0x000056483485e513 in overmap::open (this=this@entry=0x7f24929b9010, enabled_specials=...) at src/overmap.cpp:4547
#17 0x000056483485e605 in overmap::populate (this=this@entry=0x7f24929b9010, enabled_specials=...) at src/overmap.cpp:1177
#18 0x0000564834c5ec7c in overmapbuffer::create_custom_overmap (this=<optimized out>, x=<optimized out>, y=<optimized out>, specials=...) at src/overmapbuffer.cpp:96
#19 0x0000564834858df3 in overmap::place_specials (this=this@entry=0x7f2493353010, enabled_specials=...) at src/overmap.cpp:4412
#20 0x000056483485de4e in overmap::generate (this=this@entry=0x7f2493353010, north=<optimized out>, east=east@entry=0x0, south=south@entry=0x7f2493739010, west=west@entry=0x0, enabled_specials=...)
    at src/overmap.cpp:1704
#21 0x000056483485e513 in overmap::open (this=this@entry=0x7f2493353010, enabled_specials=...) at src/overmap.cpp:4547
#22 0x000056483485e605 in overmap::populate (this=this@entry=0x7f2493353010, enabled_specials=...) at src/overmap.cpp:1177
#23 0x0000564834c5ec7c in overmapbuffer::create_custom_overmap (this=<optimized out>, x=<optimized out>, y=<optimized out>, specials=...) at src/overmapbuffer.cpp:96
#24 0x0000564834858df3 in overmap::place_specials (this=this@entry=0x7f2493739010, enabled_specials=...) at src/overmap.cpp:4412
#25 0x000056483485de4e in overmap::generate (this=this@entry=0x7f2493739010, north=<optimized out>, east=east@entry=0x0, south=south@entry=0x0, west=west@entry=0x0, enabled_specials=...)
---Type <return> to continue, or q <return> to quit---
    at src/overmap.cpp:1704
#26 0x000056483485e513 in overmap::open (this=this@entry=0x7f2493739010, enabled_specials=...) at src/overmap.cpp:4547
#27 0x000056483485e605 in overmap::populate (this=this@entry=0x7f2493739010, enabled_specials=...) at src/overmap.cpp:1177
#28 0x000056483486dc47 in overmap::populate (this=this@entry=0x7f2493739010) at src/overmap.cpp:1186
#29 0x0000564834c60ec6 in overmapbuffer::get (this=0x564835a34980 <overmap_buffer>, x=x@entry=0, y=y@entry=0) at src/overmapbuffer.cpp:76
#30 0x0000564834d767b2 in start_location::find_player_initial_location (this=this@entry=0x56483641b230) at src/start_location.cpp:208
#31 0x0000564834a274c8 in game::start_game (this=0x564835e37860, worldname="Turner Corner") at src/game.cpp:825
#32 0x00005648345d3f8d in main_menu::new_character_tab (this=this@entry=0x7ffd8e9c2510) at src/main_menu.cpp:707
#33 0x00005648345d7633 in main_menu::opening_screen (this=0x7ffd8e9c2510) at src/main_menu.cpp:390
#34 0x0000564834a858ed in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:517
```
Seems that the game got stuck in a recursive loop.

**Comment by ZhilkinSerg** [comment]
Probably  starting overmap location cannot be found.
