### ISSUE TITLE
Crash in used_weapon

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#23579]
Game version: master

Operating system: gentoo linux

Tiles or curses: curses

Mods active: bright nights

I was trying to sleep when some zombie was knocking my door when it segfaulted.
```
#0  __cxxabiv1::__dynamic_cast (src_ptr=src_ptr@entry=0x0, src_type=0x7810d28358 <typeinfo for Character>, dst_type=0x7810d1f648 <typeinfo for player>, src2dst=src2dst@entry=0)
    at /var/tmp/paludis/sys-devel-gcc-7.3.0-r1/work/gcc-7.3.0/libstdc++-v3/libsupc++/dyncast.cc:50
#1  0x000000780ffda83d in Character::used_weapon (this=this@entry=0x0) at src/melee.cpp:98
#2  0x000000780ffdc830 in player::unarmed_attack (this=this@entry=0x0) at src/melee.cpp:113
#3  0x000000781028d3ac in mdefense::zapback (m=..., source=0x781b45d3d0, proj=0x0) at src/mondefense.cpp:33
#4  0x000000781052196e in monster::on_hit (this=0x781c08f990, source=0x781b45d3d0, proj=0x0) at src/monster.cpp:2123
#5  0x00000078106a307b in Creature::deal_melee_hit (this=0x781c08f990, source=0x781b45d3d0, hit_spread=<optimized out>, critical_hit=<optimized out>, dam=..., dealt_dam=...) at src/creature.cpp:399
#6  0x0000007810535f14 in monster::melee_attack (this=this@entry=0x781b45d3d0, target=..., accuracy=<optimized out>) at src/monster.cpp:1053
#7  0x0000007810537401 in monster::melee_attack (this=this@entry=0x781b45d3d0, target=...) at src/monster.cpp:1014
#8  0x0000007810593849 in monster::attack_at (this=this@entry=0x781b45d3d0, p=...) at src/monmove.cpp:958
#9  0x000000781059e54a in monster::move (this=this@entry=0x781b45d3d0) at src/monmove.cpp:654
#10 0x000000780f8d5155 in game::monmove (this=this@entry=0x7811cc3ba0) at src/game.cpp:5534
#11 0x000000780f90ab23 in game::do_turn (this=0x7811cc3ba0) at src/game.cpp:1515
#12 0x000000780fb78a83 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:523
```

**Comment by l29ah** [comment]
Okay, got it again when i was just walking around some zombies.

**Comment by l29ah** [comment]
663d22767a41624b3919233b988ee27915d3f16d looks kinda strange

**Comment by Leland** [comment]
Any chance of a list of steps to reproduce?
