### ISSUE TITLE
Test failures/crash with gcc and LTO enabled

### ISSUE THREAD

**Issue by reinerh** [CleverRaven/Cataclysm-DDA#24506]
Game version: 2b2450e
Operating system: Linux (Debian)
Compiler: g++ 8.1.0

### Expected behavior

cata_test is running successfully (like it does without LTO=1).

### Actual behavior

test failures and core dump, see below.

### Steps to reproduce the behavior

Build and run the tests with the following command:

`make PREFIX=/usr RELEASE=1 USE_XDG_DIR=1 LANGUAGES=all DEBUG_SYMBOLS=1 LTO=1 TILES=1 SOUND=1 -j4 check`

### Test output
```
[...]

0.000 s: recipe_subset
Can't display menu options, 0 0 available screen rows are occupied
This is probably a bug.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cata_test is a Catch v1.9.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
charge_handling
  carver
-------------------------------------------------------------------------------
crafting_test.cpp:231
...............................................................................

crafting_test.cpp:231: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  basic_string::_M_create

0.004 s: carver
0.000 s: charge_handling
Can't display menu options, 0 0 available screen rows are occupied
This is probably a bug.

-------------------------------------------------------------------------------
charge_handling
  carver_split_charges
-------------------------------------------------------------------------------
crafting_test.cpp:248
...............................................................................

crafting_test.cpp:248: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  basic_string::_M_create

0.004 s: carver_split_charges
0.000 s: charge_handling
Can't display menu options, 0 0 available screen rows are occupied
This is probably a bug.

-------------------------------------------------------------------------------
charge_handling
  UPS_modded_carver
-------------------------------------------------------------------------------
crafting_test.cpp:267
...............................................................................

crafting_test.cpp:267: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  basic_string::_M_create

0.004 s: UPS_modded_carver

[...]

0.000 s: reload_gun_with_integral_magazine_using_speedloader
0.000 s: reload_gun_with_swappable_magazine
-------------------------------------------------------------------------------
zapback_npc_unarmed
-------------------------------------------------------------------------------
mondefense_test.cpp:25
...............................................................................

mondefense_test.cpp:25: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

0.000 s: zapback_npc_unarmed
===============================================================================
test cases:     35 |     33 passed | 2 failed
assertions: 631137 | 631133 passed | 4 failed

Segmentation fault (core dumped)
```

### Backtrace

```
Core was generated by `tests/cata_test -d yes'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005614502f0a53 in cata_tiles::init_draw_hit (this=0x0, p=..., name=...) at src/cata_tiles.cpp:2374
2374	    do_draw_hit = true;
(gdb) bt 
#0  0x00005614502f0a53 in cata_tiles::init_draw_hit (this=0x0, p=..., name="npc_male") at src/cata_tiles.cpp:2374
#1  0x0000561450400ca1 in game::draw_hit_player (dam=3, p=..., this=<optimized out>) at /usr/include/c++/8/bits/unique_ptr.h:342
#2  player::deal_damage (this=0x7ffeb13f0a50, source=0x7ffeb13f07f8, bp=bp_arm_l, d=...) at src/player.cpp:3355
#3  0x000056145045e76f in mdefense::zapback (m=..., source=<optimized out>, projectile=<optimized out>) at src/mondefense.cpp:59
#4  0x000056145063e175 in test_zapback (attacker=..., expect_damage=expect_damage@entry=true, proj=proj@entry=0x0) at mondefense_test.cpp:16
#5  0x000056145063ecb7 in ::____C_A_T_C_H____T_E_S_T__ () at mondefense_test.cpp:28
#6  0x0000561450669736 in Catch::TestCase::invoke (this=<optimized out>) at catch/catch.hpp:8291
#7  Catch::RunContext::invokeActiveTestCase (this=<optimized out>) at catch/catch.hpp:6852
#8  0x000056145067f5bf in Catch::runTests (config=...) at catch/catch.hpp:6819
#9  0x000056145024d124 in Catch::Session::run (this=0x7ffeb13f2fc0) at catch/catch.hpp:7126
#10 main (argc=<optimized out>, argv=<optimized out>) at test_main.cpp:162
(gdb) p tilecontext
$1 = std::unique_ptr<cata_tiles> = {
  get() = 0x0
}

```

**Comment by kevingranade** [comment]
What happens if you remove TILES=1?

**Comment by reinerh** [comment]
Without TILES=1 there is no segmentation fault, only test failures:

```
[...]

0.000 s: recipe_subset
0.000 s:     Then: it's still easier to perform
0.000 s: And when: it's included again with higher difficulty
0.000 s:     When: the recipe is included with lower difficulty
0.000 s:    Given: a recipe of rum
0.000 s: recipe_subset
Can't display menu options, 0 0 available screen rows are occupied
This is probably a bug.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cata_test is a Catch v1.9.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
charge_handling
  carver
-------------------------------------------------------------------------------
crafting_test.cpp:231
...............................................................................

crafting_test.cpp:231: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  basic_string::_M_create

0.003 s: carver
0.000 s: charge_handling
Can't display menu options, 0 0 available screen rows are occupied
This is probably a bug.

-------------------------------------------------------------------------------
charge_handling
  carver_split_charges
-------------------------------------------------------------------------------
crafting_test.cpp:248
...............................................................................

crafting_test.cpp:248: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  basic_string::_M_create

0.003 s: carver_split_charges
0.000 s: charge_handling
Can't display menu options, 0 0 available screen rows are occupied
This is probably a bug.

-------------------------------------------------------------------------------
charge_handling
  UPS_modded_carver
-------------------------------------------------------------------------------
crafting_test.cpp:267
...............................................................................

crafting_test.cpp:267: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  basic_string::_M_create

0.004 s: UPS_modded_carver
0.000 s: charge_handling

[...]

===============================================================================
test cases:      75 |      74 passed | 1 failed
assertions: 1310535 | 1310532 passed | 3 failed

Test world "Tom" left for inspection.
Ended test at Sat Jul 28 00:37:43 2018
The test took 28.606 seconds

```

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/issues/24133

**Comment by kevingranade** [comment]
#24133 provides a fix, though it requires manual intervention to apply it.
