### ISSUE TITLE
Crash during mapgen while generating burned map extra

### ISSUE THREAD

**Issue by kevingranade** [CleverRaven/Cataclysm-DDA#30939]
# Describe the bug
Occasionally the game will encounter a crash during mapgen, the stack trace points to map extras generation.

# Steps To Reproduce
Run monster speed unit tests, this exercises mapgen a good bit and has a good chance of quickly triggering the bug.

# Expected behavior
No crash.

# Additional context
Stacktrace from gdb
```
#0  item::typeId[abi:cxx11]() const (this=this@entry=0x10) at src/item.cpp:6557
#1  0x0000000000a38127 in item::is_corpse (this=this@entry=0x10) at src/item.cpp:4941
#2  0x0000000000a38167 in item::made_of (this=this@entry=0x10) at src/item.cpp:4727
#3  0x0000000000a3cf3a in item::made_of_types (this=this@entry=0x10) at src/item.cpp:4741
#4  0x0000000000a42ff5 in item::flammable (this=this@entry=0x10, threshold=threshold@entry=0) at src/item.cpp:6520
#5  0x0000000000f25d10 in MapExtras::burned_ground_parser (m=..., loc=...) at src/map_extras.cpp:1350
#6  0x0000000000f25f4f in MapExtras::mx_point_burned_ground (m=..., abs_sub=...) at src/map_extras.cpp:1374
#7  0x0000000000b66dea in map::generate (this=this@entry=0x7fffeca79d40, x=x@entry=0, y=y@entry=4, z=z@entry=0, when=...) at src/mapgen.cpp:162
#8  0x0000000000b25b44 in map::loadn (this=this@entry=0x2f5e710, gridx=gridx@entry=0, gridy=gridy@entry=4, gridz=gridz@entry=0, update_vehicles=update_vehicles@entry=false) at src/map.cpp:6762
#9  0x0000000000b2639c in map::loadn (this=0x2f5e710, gridx=0, gridy=4, update_vehicles=false) at src/map.cpp:6687
#10 0x0000000000b2643d in map::load (this=this@entry=0x2f5e710, wx=<optimized out>, wy=wy@entry=0, wz=wz@entry=0, update_vehicle=update_vehicle@entry=false) at src/map.cpp:6467
#11 0x0000000000878d88 in init_global_game_state (mods=std::vector of length 1, capacity 1 = {...}, option_overrides=std::vector of length 0, capacity 0, user_dir="./") at test_main.cpp:155
#12 0x00000000006f0319 in main (argc=<optimized out>, argv=0x7fffeca7fca8) at test_main.cpp:296
```

This seems to be the source of the problem.
Destroying items while iterating over a map_stack can cause the current iterator to become invalidated. We might have a remove() method here that returns an appropriate iterator, or we might be able to do the iterate-in-reverse trick.
```
    // burn-away flammable items                                                                                                                                                                                                  
    while( m.flammable_items_at( loc ) ) {
        for( auto it = m.i_at( loc ).begin(); it != m.i_at( loc ).end(); ++it ) {
            if( it->flammable() ) {
                m.i_rem( loc, it );
                m.create_burnproducts( loc, *it, it->weight() );
            }
        }
    }
```

**Comment by mark7** [comment]
> Run monster speed unit tests, this exercises mapgen a good bit and has a good chance of quickly triggering the bug.

Might make sense to have a test that runs worldgen with a specifiable RNG seed.  That way, world generation crashes can be reported via "run worldgentest on git hashref XXX with seed Y".
