### ISSUE TITLE
Crash in item::is_tool after trying to pick the same one available ingredient for two different components of the vegetable soup

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#32554]
# Describe the bug

```
#3  <signal handler called>
#4  0x0000556aff1d2e23 in item::is_tool (this=this@entry=0x556b19d58630) at src/item.cpp:5452
#5  0x0000556affa78d08 in <lambda(const item*)>::operator() (e=0x556b19d58630, this=0x556b0a60e0d0) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#6  std::_Function_handler<VisitResponse(const item*), charges_of_internal(const T&, const itype_id&, int, const std::function<bool(const item&)>&) [with T = item; itype_id = std::__cxx11::basic_string<char>]::<lambda(const item*)> >::_M_invoke(const std::_Any_data &, const item *&&) (__functor=..., __args#0=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:282
#7  0x0000556affa7d1be in std::function<VisitResponse (item const*)>::operator()(item const*) const (__args#0=<optimized out>, this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#8  std::_Function_handler<VisitResponse (item*), std::function<VisitResponse (item const*)> >::_M_invoke(std::_Any_data const&, item*&&) (__functor=..., __args#0=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:282
#9  0x0000556affa7d26e in std::function<VisitResponse (item*)>::operator()(item*) const (__args#0=<optimized out>, this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#10 visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}::operator()(item*, item*) const (this=<optimized out>, it=<optimized out>) at src/visitable.cpp:347
#11 std::_Function_handler<VisitResponse (item*, item*), visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}>::_M_invoke(std::_Any_data const&, item*&&, std::_Any_data const&) (
    __functor=..., __args#0=<optimized out>, __args#1=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:282
#12 0x0000556affa76e44 in std::function<VisitResponse (item*, item*)>::operator()(item*, item*) const (__args#1=<optimized out>, __args#0=<optimized out>, this=0x7fff5d663290)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#13 visit_internal(const std::function<VisitResponse(item*, item*)> &, item *, item *) (func=..., node=0x556b19d58630, parent=<optimized out>) at src/visitable.cpp:356
#14 0x0000556affa7de12 in visitable<item>::visit_items(std::function<VisitResponse (item*, item*)> const&) (func=..., this=<optimized out>) at src/visitable.cpp:387
#15 visitable<item>::visit_items(std::function<VisitResponse (item*)> const&) (this=this@entry=0x556b19d58630, func=...) at src/visitable.cpp:348
#16 0x0000556affa7e791 in visitable<item>::visit_items(std::function<VisitResponse (item const*)> const&) const (this=this@entry=0x556b19d58630, func=...) at src/visitable.cpp:336
#17 0x0000556affa791a2 in charges_of_internal<item> (filter=..., limit=<optimized out>, id=..., self=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:87
#18 visitable<inventory>::charges_of(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::function<bool (item const&)> const&) const (this=<optimized out>, what=..., limit=1, filter=...)
    at src/visitable.cpp:823
#19 0x0000556aff8d6eb8 in requirement_data::<lambda(std::vector<item_comp, std::allocator<item_comp> >&)>::operator()(std::vector<item_comp, std::allocator<item_comp> > &) (comps=..., __closure=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/new:169
#20 0x0000556aff8d7f64 in __gnu_cxx::__ops::_Iter_pred<requirement_data::continue_requirements(const std::vector<item_comp>&, const std::__cxx11::list<item>&)::<lambda(std::vector<item_comp, std::allocator<item_comp> >&)> >::operator()<__gnu_cxx::__normal_iterator<std::vector<item_comp>*, std::vector<std::vector<item_comp> > > > (__it=..., this=0x7fff5d663538) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/predefined_ops.h:282
#21 std::__remove_if<__gnu_cxx::__normal_iterator<std::vector<item_comp>*, std::vector<std::vector<item_comp> > >, __gnu_cxx::__ops::_Iter_pred<requirement_data::continue_requirements(const std::vector<item_comp>&, const std::__cxx11::list<item>&)::<lambda(std::vector<item_comp>&)> > > (__pred=..., __last=..., __first=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_algo.h:869
#22 std::remove_if<__gnu_cxx::__normal_iterator<std::vector<item_comp>*, std::vector<std::vector<item_comp> > >, requirement_data::continue_requirements(const std::vector<item_comp>&, const std::__cxx11::list<item>&)::<lambda(std::vector<item_comp>&)> > (__pred=..., __last=..., __first=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_algo.h:939
#23 requirement_data::continue_requirements (required_comps=..., remaining_comps=...) at src/requirements.cpp:1018
#24 0x0000556afef6bf03 in item::get_continue_reqs (this=0x556b0ddaabf0) at src/crafting.cpp:1055
#25 0x0000556afef770e8 in player::can_continue_craft (this=this@entry=0x556b00d20b90, craft=...) at src/crafting.cpp:1221
#26 0x0000556afed9e00d in activity_handlers::craft_do_turn (act=0x556b00d23a70, p=0x556b00d20b90) at src/activity_handlers.cpp:3272
#27 0x0000556afede0b2b in std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const (__args#1=<optimized out>, __args#0=<optimized out>, this=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#28 activity_type::call_do_turn (this=0x556b01177508, act=act@entry=0x556b00d23a70, p=p@entry=0x556b00d20b90) at src/activity_type.cpp:111
#29 0x0000556aff854992 in player_activity::do_turn (this=0x556b00d23a70, p=...) at src/string_id.h:128
#30 0x0000556aff0a2490 in game::process_activity (this=0x556b00cc6ae0) at src/game.cpp:1620
#31 game::process_activity (this=0x556b00cc6ae0) at src/game.cpp:1608
#32 0x0000556aff0ec390 in game::do_turn (this=0x556b00cc6ae0) at src/game.cpp:1399
#33 0x0000556afed2b119 in main (argc=<optimized out>, argv=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/unique_ptr.h:342
```

0.D-5752-ge348498b04-dirty

**Comment by l29ah** [comment]
It's interesting that it doesn't always reproduce, and when it does, it succeeds at cooking the soup.
My repro save: [2019.07.20-32554.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3419106/2019.07.20-32554.zip)
Pick `wild vegetables` twice when prompted.

**Comment by ipcyborg** [comment]
I can confirm that there is no crash, but there is still an issue here:

How to reproduce:
1. Load the provided save.
2. Press & to craft.
3. Select "vegetable soup".
4. Choose "1. broth (1/4 nearby)".
5. Choose "2. wild vegetables (1/1 nearby)".
6. Again choose "2. wild vegetables (1/1 nearby)" (Observer that there is one more choice here "3. wild vegetables (1/1 nearby)" - which is obviously incorrect). 

Result: the soup is crafted. 
The issue is that there should not be enough ingredients for this craft: the player has only 1 wild vegetables, but the recipe requires 2 of them.

First: the recipe is incorrect. It has a duplicate in the list (easy to fix):

>data/json/requirements/cooking_components.json
"id": "veggy_any_uncooked",
... 
[ "veggy", 1 ],
[ "veggy_wild", 1 ],

Second: the logic of using of player::select_item_component:
It is used for a single group of components, combined by "OR", so any one of this group could be used.
And usually the selected component is immediately used by consume_items function.

However in craft_command.cpp (craft_command::execute), which is used from crafting menu (&), the function select_item_component is used differently.
It is called multiple times and the results are accumulated in item_selections and consumed later.
This usage leads to searching for one ingredient ("wild vegetables") twice. And it can always be found (1 wild vegetables nearby). 
But during the second search the function does not recognize this vegetable as "used already" in the first search. 

I could possibly rewrite it: if this component was searched before in this craft, then add the count required to the previous search and do the search again. 
There will be some complications, like the recipe looks like available from the crafting menu. But after some player's selections from the menu it could become impossible to craft this recipe from this specifically selected components.

Does anyone know how to fix this better?

**Comment by KorGgenT** [comment]
![image](https://user-images.githubusercontent.com/30208401/71184625-0bd94700-2248-11ea-8008-3b190d63da41.png)
![image](https://user-images.githubusercontent.com/30208401/71184637-11369180-2248-11ea-9fa8-610cec681025.png)
Following the instructions above, these are the debug messages. It's not a crash anymore, but it is obviously not a desirable outcome.

**Comment by dragonlotion** [comment]
Seems the problem still exists in 0.D-10610-g8761541 (tiles)
![image](https://user-images.githubusercontent.com/59143787/71327035-131b8180-24e2-11ea-9ce6-f56f4a7b6578.png)

**Comment by jbytheway** [comment]
Related to #32311.  I've posted some discussion of potential solutions there.
