### ISSUE TITLE
OpenBSD build SIGBUS crash when walking around

### ISSUE THREAD

**Issue by fossforus** [CleverRaven/Cataclysm-DDA#33135]
# Describe the bug

Processes dies with SIGBUS on OpenBSD builds after walking around

# Steps To Reproduce

1. Be using OpenBSD/OpenBSD's malloc implementation
2. Walk in a direction for 30 seconds to a minute

# Expected behavior

To not crash :>
OpenBSD's malloc implementation sets to top of each page to 0xdf after each free, which you can see in the trace below, this indicates something is being referenced after it was freed

Relevant Issues:
https://github.com/CleverRaven/Cataclysm-DDA/issues/21293
https://github.com/CleverRaven/Cataclysm-DDA/pull/21549

# Versions and configuration

- OS: Unix (OpenBSD)
    - OS Version: <unknown> (OpenBSD 6.5-current)
- Game Version: 0.D [64-bit] (I'm on tag jenkins-b9446, not sure why it's reporting this)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations]
]

# Additional context

```
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-openbsd6.5".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cataclysm-tiles...done.
[New process 402155]
Core was generated by `cataclysm-tiles'.
Program terminated with signal SIGBUS, Bus error.
#0  _libc_memcmp (s1=0xdfdfdfdfdfdfdfdf, s2=0x7f7ffffee9c1, n=<optimized out>) at /usr/src/lib/libc/string/memcmp.c:46
46                              if (*p1++ != *p2++)
(gdb) bt
#0  _libc_memcmp (s1=0xdfdfdfdfdfdfdfdf, s2=0x7f7ffffee9c1, n=<optimized out>) at /usr/src/lib/libc/string/memcmp.c:46
#1  0x0000092d8039cff0 in std::__1::char_traits<char>::compare (__s1=0xdfdfdfdfdfdfdfdf <error: Cannot access memory at address 0xdfdfdfdfdfdfdfdf>, __s2=<optimized out>, __n=<optimized out>) at /usr/include/c++/v1/__string:250
#2  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare<std::__1::basic_string_view<char, std::__1::char_traits<char> > > (this=<optimized out>, __t=...) at /usr/include/c++/v1/string:3693
#3  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare (this=<optimized out>, __str=...) at /usr/include/c++/v1/string:3709
#4  std::__1::operator< <char, std::__1::char_traits<char>, std::__1::allocator<char> > (__lhs=..., __rhs=...) at /usr/include/c++/v1/string:3934
#5  std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::operator() (__x=..., this=<optimized out>, __y=...) at /usr/include/c++/v1/__functional_base:55
#6  std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>::operator() (__x=..., this=<optimized out>,
    __y=...) at /usr/include/c++/v1/map:517
#7  std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::__lower_bound<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > (this=<optimized out>, __v=..., __root=0x92fc468ff80, __result=0x92d813123c0 <FILENAMES+8>) at /usr/include/c++/v1/__tree:2670
#8  std::__1::__tree<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::__map_value_compare<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::find<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > (this=<optimized out>, __v=...) at /usr/include/c++/v1/__tree:2599
#9  0x0000092d804c39ac in std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >::find (this=0x92d813123b8 <FILENAMES>, __k=...) at /usr/include/c++/v1/map:1375
#10 get_crash_log_file_name () at src/crash.cpp:232
#11 log_crash (type=0x92d80024de5 "Signal", msg=0x92d8002011f "SIGSEGV: Segmentation fault") at src/crash.cpp:247
#12 0x0000092d804c384a in signal_handler (sig=<optimized out>) at src/crash.cpp:291
#13 0x0000092fade21005 in ?? ()
#14 0x0000093067c08100 in ?? ()
#15 0x0000000000000000 in ?? ()
(gdb)
```

**Comment by fossforus** [comment]
Another trace after wandering around for a while
```
>egdb cataclysm-tiles
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-openbsd6.5".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cataclysm-tiles...done.
(gdb) run
Starting program: /usr/local/bin/cataclysm-tiles
[New process 88670]
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: /home/stan/.config/cataclysm-dda/crash.log
VERSION: 0.D
TYPE: St9bad_alloc
MESSAGE: std::bad_alloc
STACK TRACE:

        0x30e81a64eb8 <_Z21debug_write_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE+56> at /usr/local/bin/cataclysm-tiles
        0x30e81a43c65 <_Z19init_crash_handlersv+1269> at /usr/local/bin/cataclysm-tiles
        0x30e81a438fe <_Z19init_crash_handlersv+398> at /usr/local/bin/cataclysm-tiles
        0x3108ca9a91f <_ZSt13get_terminatev+63> at /usr/lib/libc++abi.so.1.0
        0x3108ca7b3dc <__cxa_throw+284> at /usr/lib/libc++abi.so.1.0
        0x3108ca7b33b <__cxa_throw+123> at /usr/lib/libc++abi.so.1.0
        0x3110f81e250 <_Znwm+128> at /usr/lib/libc++.so.3.0
        0x30e81f3329f <_ZN3map9add_roofsEiii+1743> at /usr/local/bin/cataclysm-tiles
        0x30e81f32052 <_ZN3map5loadnEiiib+866> at /usr/local/bin/cataclysm-tiles
        0x30e81f31657 <_ZN3map5shiftEii+1591> at /usr/local/bin/cataclysm-tiles
        0x30e81bce9ac <_ZN4game10update_mapERiS0_+268> at /usr/local/bin/cataclysm-tiles
        0x30e81bc882a <_ZN4game12place_playerERK8tripoint+2122> at /usr/local/bin/cataclysm-tiles
        0x30e81bc75d8 <_ZN4game9walk_moveERK8tripoint+6536> at /usr/local/bin/cataclysm-tiles
        0x30e818987c4 <_ZN13avatar_action4moveER6avatarR3mapiii+5412> at /usr/local/bin/cataclysm-tiles
        0x30e81c2a4a4 <_ZN4game13handle_actionEv+19700> at /usr/local/bin/cataclysm-tiles
        0x30e81b85168 <_ZN4game7do_turnEv+2632> at /usr/local/bin/cataclysm-tiles
        0x30e81eefae9 <main+5929> at /usr/local/bin/cataclysm-tiles
        0x30e8176e13b <__start+315> at /usr/local/bin/cataclysm-tiles

        Attempting to repeat stack trace using debug symbols...
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line
        backtrace: Could not extract binary name from line

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000310bb965287 in SDL_DestroyTexture_REAL () from /usr/local/lib/libSDL2.so.0.6
(gdb) bt
#0  0x00000310bb965287 in SDL_DestroyTexture_REAL () from /usr/local/lib/libSDL2.so.0.6
#1  0x0000030e8259bbeb in SDL_Texture_deleter::operator() (ptr=0x3110a7a6180, this=<optimized out>) at src/sdl_wrappers.h:42
#2  std::__1::unique_ptr<SDL_Texture, SDL_Texture_deleter>::reset (this=<optimized out>, __p=0x0) at /usr/include/c++/v1/memory:2652
#3  std::__1::unique_ptr<SDL_Texture, SDL_Texture_deleter>::~unique_ptr (this=<optimized out>) at /usr/include/c++/v1/memory:2606
#4  CachedTTFFont::cached_t::~cached_t (this=<optimized out>) at src/sdltiles.cpp:158
#5  std::__1::pair<CachedTTFFont::key_t const, CachedTTFFont::cached_t>::~pair (this=<optimized out>) at /usr/include/c++/v1/utility:316
#6  std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, void*> > >::__destroy<std::__1::pair<CachedTTFFont::key_t const, CachedTTFFont::cached_t> > (
    __p=<optimized out>) at /usr/include/c++/v1/memory:1748
#7  std::__1::allocator_traits<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, void*> > >::destroy<std::__1::pair<CachedTTFFont::key_t const, CachedTTFFont::cached_t> > (
    __p=<optimized out>, __a=...) at /usr/include/c++/v1/memory:1596
#8  std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::destroy (this=0x310ef268898, __nd=0x3114ee3c000) at /usr/include/c++/v1/__tree:1854
#9  0x0000030e8259bbd5 in std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::destroy (this=0x310ef268898, __nd=0x3110e3dad00) at /usr/include/c++/v1/__tree:1852
#10 0x0000030e8259bbc9 in std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::destroy (this=0x310ef268898, __nd=0x310d88f4400) at /usr/include/c++/v1/__tree:1851
#11 0x0000030e8259bbc9 in std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::destroy (this=0x310ef268898, __nd=0x31144c48e00) at /usr/include/c++/v1/__tree:1851
#12 0x0000030e8259bbd5 in std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::destroy (this=0x310ef268898, __nd=0x31130352780) at /usr/include/c++/v1/__tree:1852
#13 0x0000030e8259bbd5 in std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::destroy (this=0x310ef268898, __nd=0x3116089aa00) at /usr/include/c++/v1/__tree:1852
#14 0x0000030e8259bbc9 in std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::destroy (this=0x310ef268898, __nd=0x3114c874d00) at /usr/include/c++/v1/__tree:1851
#15 0x0000030e8259bbc9 in std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::destroy (this=0x310ef268898, __nd=0x311138f7080) at /usr/include/c++/v1/__tree:1851
#16 0x0000030e8259bbc9 in std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::destroy (this=0x310ef268898, __nd=0x31145bc9600) at /usr/include/c++/v1/__tree:1851
#17 0x0000030e8259ac71 in std::__1::__tree<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::__map_value_compare<CachedTTFFont::key_t, std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t>, std::__1::less<CachedTTFFont::key_t>, true>, std::__1::allocator<std::__1::__value_type<CachedTTFFont::key_t, CachedTTFFont::cached_t> > >::~__tree (this=0x3110a7a6180) at /usr/include/c++/v1/__tree:1842
#18 std::__1::map<CachedTTFFont::key_t, CachedTTFFont::cached_t, std::__1::less<CachedTTFFont::key_t>, std::__1::allocator<std::__1::pair<CachedTTFFont::key_t const, CachedTTFFont::cached_t> > >::~map (this=<optimized out>)
    at /usr/include/c++/v1/map:899
#19 CachedTTFFont::~CachedTTFFont (this=0x310ef268880) at src/sdltiles.cpp:139
#20 CachedTTFFont::~CachedTTFFont (this=0x310ef268880) at src/sdltiles.cpp:139
#21 0x00000311252375dd in _libc___cxa_finalize (dso=<optimized out>) at /usr/src/lib/libc/stdlib/atexit.c:177
#22 0x00000311251f6c11 in _libc_exit (status=1) at /usr/src/lib/libc/stdlib/exit.c:54
#23 0x0000030e81a43908 in crash_terminate_handler () at src/crash.cpp:327
#24 0x000003108ca9a91f in std::__terminate (func=0x3110a7a6180) at /usr/src/lib/libcxxabi/src/cxa_handlers.cpp:60
#25 0x000003108ca7b3dc in __cxxabiv1::failed_throw (exception_header=0x3109e6f8600) at /usr/src/lib/libcxxabi/src/cxa_exception.cpp:153
#26 0x000003108ca7b33b in __cxa_throw (thrown_object=0x3109e6f8680, tinfo=0x3108caa1cb8 <typeinfo for std::bad_alloc>, dest=<optimized out>) at /usr/src/lib/libcxxabi/src/cxa_exception.cpp:285
#27 0x000003110f81e250 in operator new (size=<optimized out>) at /usr/src/lib/libcxx/src/new.cpp:81
#28 0x0000030e81f3329f in generate_uniform (p=..., terrain_type=...) at src/map.cpp:6744
---Type <return> to continue, or q <return> to quit---
#29 0x0000030e81f32052 in map::loadn (this=0x310a207c400, gridx=10, gridy=10, gridz=-9, update_vehicles=<optimized out>) at src/map.cpp:6788
#30 0x0000030e81f31657 in map::shift (this=0x310a207c400, sx=<optimized out>, sy=-1) at src/map.cpp:6602
#31 0x0000030e81bce9ac in game::update_map (this=0x310a2082800, x=@0x7f7ffffeeb20: 60, y=@0x7f7ffffeeb50: 71) at src/game.cpp:10587
#32 0x0000030e81bc882a in game::update_map (this=0x310a2082800, p=...) at src/game.cpp:10554
#33 game::place_player (this=0x310a2082800, dest_loc=...) at src/game.cpp:9323
#34 0x0000030e81bc75d8 in game::walk_move (this=0x310a2082800, dest_loc=...) at src/game.cpp:9155
#35 0x0000030e818987c4 in avatar_action::move (you=..., m=..., dx=<optimized out>, dy=<optimized out>, dz=<optimized out>) at src/avatar_action.cpp:364
#36 0x0000030e81c2a4a4 in avatar_action::move (you=..., m=..., d=...) at src/avatar_action.h:22
#37 avatar_action::move (you=..., m=..., d=...) at src/avatar_action.h:26
#38 game::handle_action (this=0x310a2082800) at src/handle_action.cpp:2371
#39 0x0000030e81b85168 in game::do_turn (this=0x310a2082800) at src/game.cpp:1434
#40 0x0000030e81eefae9 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:688
(gdb)
```

**Comment by fossforus** [comment]
Another trace identical to the first, I actually managed to play for over an hour until I hit a crash this time, no clue as to why it took that long; no idea if this is actually multiple problems or one.

**Comment by Maleclypse** [comment]
Irwss said unable to repro
