### ISSUE TITLE
Read past the end of buffer in item::simulate_burn for materials without burn_data

### ISSUE THREAD

**Issue by hexagonrecursion** [CleverRaven/Cataclysm-DDA#36441]
# Describe the bug

Read past the end of buffer in item::simulate_burn for materials without burn_data

# Steps To Reproduce

1. Compile with clang and AddressSanitizer
2. Set a bench in the starting shelter on fire
3. Wait for a couple of in-game hours

# Expected behavior

The game does not crash.

# Actual behavior

AddressSanitizer terminates the game with the following message:
```
==3786==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030002408c4 at pc 0x0000039970c3 bp 0x7ffd323a9530 sp 0x7ffd323a9528
READ of size 1 at 0x6030002408c4 thread T0
    #0 0x39970c2 in item::simulate_burn(fire_data&) const /home/user/cdda/src/item.cpp:7348:16
    #1 0x3997200 in item::burn(fire_data&) /home/user/cdda/src/item.cpp:7393:24
    #2 0x43546d5 in map::process_fields_in_submap(submap*, tripoint const&) /home/user/cdda/src/map_field.cpp:530:52
    #3 0x4350d67 in map::process_fields() /home/user/cdda/src/map_field.cpp:138:44
    #4 0x3372a7b in game::do_turn() /home/user/cdda/src/game.cpp:1534:7
    #5 0x414d59f in main /home/user/cdda/src/main.cpp:688:20
    #6 0x72b064b8cf42 in __libc_start_main (/lib64/libc.so.6+0x23f42)
    #7 0x202eebd in _start (/home/user/cdda/cataclysm-tiles+0x202eebd)

0x6030002408c4 is located 0 bytes to the right of 20-byte region [0x6030002408b0,0x6030002408c4)
allocated by thread T0 here:
    #0 0x214868f in operator new(unsigned long) (/home/user/cdda/cataclysm-tiles+0x214868f)
    #1 0x37926d6 in std::_Vector_base<mat_burn_data, std::allocator<mat_burn_data> >::_M_create_storage(unsigned long) /usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_vector.h:358:33
    #2 0x3786f54 in material_type::material_type(material_type const&) /home/user/cdda/src/material.h:28:7

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/user/cdda/src/item.cpp:7348:16 in item::simulate_burn(fire_data&) const
Shadow bytes around the buggy address:
  0x0c06800400c0: fa fa 00 00 04 fa fa fa 00 00 04 fa fa fa 00 00
  0x0c06800400d0: 04 fa fa fa 00 00 05 fa fa fa 00 00 03 fa fa fa
  0x0c06800400e0: 00 00 04 fa fa fa 00 00 03 fa fa fa 00 00 04 fa
  0x0c06800400f0: fa fa 00 00 00 00 fa fa 00 00 04 fa fa fa 00 00
  0x0c0680040100: 05 fa fa fa 00 00 03 fa fa fa 00 00 03 fa fa fa
=>0x0c0680040110: 00 00 05 fa fa fa 00 00[04]fa fa fa 00 00 03 fa
  0x0c0680040120: fa fa 00 00 04 fa fa fa 00 00 04 fa fa fa 00 00
  0x0c0680040130: 04 fa fa fa 00 00 00 00 fa fa 00 00 03 fa fa fa
  0x0c0680040140: 00 00 03 fa fa fa 00 00 04 fa fa fa 00 00 03 fa
  0x0c0680040150: fa fa 00 00 04 fa fa fa 00 00 03 fa fa fa 00 00
  0x0c0680040160: 03 fa fa fa 00 00 04 fa fa fa 00 00 03 fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3786==ABORTING
```

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-10692-gb7329f6ab7-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Currently the fire field-effect can have intensity up to 3, but if no burn_data is specified for a material it will only have 1 entry in _burn_data
https://github.com/CleverRaven/Cataclysm-DDA/blob/b7329f6ab70cb8a589fcf58b2b4a7a5a635f542f/src/material.cpp#L92-L103

Which result in this creating a bad reference (if intensity >= 2)
https://github.com/CleverRaven/Cataclysm-DDA/blob/b7329f6ab70cb8a589fcf58b2b4a7a5a635f542f/src/material.cpp#L256-L259

Which is later dereferenced here
https://github.com/CleverRaven/Cataclysm-DDA/blob/b7329f6ab70cb8a589fcf58b2b4a7a5a635f542f/src/item.cpp#L7346-L7348

# PS

It may also be technically possible for burn_data json array to have less than three elements, which would also trigger this.

**Comment by hexagonrecursion** [comment]
I'm not sure what is different about the [Fedora build](https://bodhi.fedoraproject.org/updates/FEDORA-2019-5fe5b3454c), but the crash is almost 100% reproducible there without a sanitizer.
