### ISSUE TITLE
[Nested Containers] Segfault when examining loaded ranged weapons

### ISSUE THREAD

**Issue by Sesnii** [CleverRaven/Cataclysm-DDA#40779]
Excuse me if I mess up with formatting or what have you, as I made a github account just to write this.
# Describe the bug

Whenever I select a loaded ranged weapon (be it an m4a1, slingshot, composite crossbow, just to name a few I tested) in my inventory or (e)xamine them when they are dropped on the floor the game handed me a segfault. Based on my somewhat-limited testing, anything you do that would normally give you the stats of the weapon will crash the game. However, that may be a simplification of the cause of the segfault.

The crash does not occur if the weapon is unloaded.

# Steps To Reproduce

Obtain a ranged weapon
Load ranged weapon
Select the ranged weapon in your inventory as shown in the screenshot
Press the enter button
The game has now segfaulted.

Alternatively, drop the ranged weapon onto the floor and then (e)xamine it.

# Expected behavior

The game does not crash, and I am able to view the weapon and its stats.

# Screenshots

![image](https://user-images.githubusercontent.com/65820538/82734234-9fc3a900-9ce7-11ea-8e3b-9484549fa2f7.png)

# Versions and configuration

11:24:42.062 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2411-g7fcce2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language (english)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4672026/crash.log)

**Comment by anothersimulacrum** [comment]
This is because `curammo` is nullptr:
(frame 3, item::gun_info)
```
#0  std::__uniq_ptr_impl<islot_ammo, std::default_delete<islot_ammo> >::_M_ptr (this=0x80) at /usr/include/c++/10.1.0/bits/unique_ptr.h:172
#1  0x0000555556fd962c in std::unique_ptr<islot_ammo, std::default_delete<islot_ammo> >::get (this=0x80) at /usr/include/c++/10.1.0/bits/unique_ptr.h:421
#2  0x0000555556fd1b8a in std::unique_ptr<islot_ammo, std::default_delete<islot_ammo> >::operator-> (this=0x80) at /usr/include/c++/10.1.0/bits/unique_ptr.h:415
#3  0x000055555791fb0c in item::gun_info (this=0x555559b7fe90, mod=0x555559b7fe90, info=std::vector of length 20, capacity 32 = {...}, parts=0x5555593cd0e0 <iteminfo_query::all>) at src/item.cpp:2036
#4  0x0000555557939702 in item::info[abi:cxx11](std::vector<iteminfo, std::allocator<iteminfo> >&, iteminfo_query const*, int) const (this=0x555559b7fe90, info=std::vector of length 20, capacity 32 = {...}, parts=0x5555593cd0e0 <iteminfo_query::all>, batch=1) at src/item.cpp:3823
#5  0x0000555557914818 in item::info[abi:cxx11](bool, std::vector<iteminfo, std::allocator<iteminfo> >&, int) const (this=0x555559b7fe90, showtext=true, iteminfo=std::vector of length 20, capacity 32 = {...}, batch=1) at src/item.cpp:1134
#6  0x00005555579147a2 in item::info[abi:cxx11](bool, std::vector<iteminfo, std::allocator<iteminfo> >&) const (this=0x555559b7fe90, showtext=true, iteminfo=std::vector of length 20, capacity 32 = {...}) at src/item.cpp:1129
#7  0x00005555576f3c2b in game::inventory_item_menu(item_location, std::function<int ()> const&, std::function<int ()> const&, game::inventory_item_menu_positon) (this=0x555559b48cd0, locThisItem=..., iStartX=..., iWidth=..., position=game::RIGHT_OF_INFO) at src/game.cpp:2167
#8  0x00005555577ade85 in game_menus::inv::common (you=...) at src/game_inventory.cpp:239
#9  0x000055555780f071 in game::handle_action (this=0x555559b48cd0) at src/handle_action.cpp:1967
#10 0x00005555576ef3ec in game::do_turn (this=0x555559b48cd0) at src/game.cpp:1535
#11 0x0000555557c4fbeb in main (argc=0, argv=0x7fffffffe890) at src/main.cpp:697
```
Here's the path it takes:
```
Thread 1 "cataclysm-tiles" hit Breakpoint 3, item::gun_info (this=0x555559b81150, mod=0x555559b81150, info=std::vector of length 18, capacity 32 = {...}, parts=0x5555593cd0e0 <iteminfo_query::all>) at src/item.cpp:1981
1981        const std::string space = "  ";
1982        const islot_gun &gun = *mod->type->gun;
1983        const Skill &skill = *mod->gun_skill();
1987        const item *loaded_mod = mod;
1988        item tmp;
1989        const itype *curammo = nullptr;
1990        if( mod->ammo_required() && !mod->ammo_remaining() ) {
2027        if( parts->test( iteminfo_parts::GUN_DAMAGE ) ) {
2028            insert_separation_line( info );
2029            info.push_back( iteminfo( "GUN", _( "<bold>Ranged damage</bold>: " ), "", iteminfo::no_newline,
2030                                      mod->gun_damage( false ).total_damage() ) );
2033       if( mod->ammo_required() ) {
2035            float dmg_mult = 1.0f;
2036            for( const damage_unit &dmg : curammo->ammo->damage.damage_units ) {
```
`mod->ammo_required()` is 1, `mod->ammo_remaining()` is 20
