### ISSUE TITLE
Crash in item_pocket::is_type when trying to reload a gun via AIM

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#41663]
# Describe the bug

```
#0  0x00007f1b04d25c91 in raise () from /lib64/libc.so.6
#1  0x00007f1b04d0f53d in abort () from /lib64/libc.so.6
#2  0x0000555c768f39b9 in signal_handler (sig=11) at src/crash.cpp:119
#3  <signal handler called>
#4  item_pocket::is_type (this=this@entry=0x10, ptype=ptype@entry=item_pocket::MOD) at src/item_pocket.cpp:1313
#5  0x0000555c76c97859 in item_contents::gunmods (this=0x555c8a85e418, this@entry=0x13b0a921bce97a08) at src/item_contents.cpp:986
#6  0x0000555c76c00ef5 in item::gunmods (this=<optimized out>) at src/item.cpp:7380
#7  item::find_armor_data (this=this@entry=0x555c8a85e410) at src/item.cpp:6421
#8  0x0000555c76c0d2ae in item::find_armor_data (this=0x555c8a85e410) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/unique_ptr.h:374
#9  item::is_armor (this=0x555c8a85e410) at src/item.cpp:6437
#10 0x0000555c76c11f9f in item::color_in_inventory (this=this@entry=0x555c8a85e410) at src/item.cpp:3989
#11 0x0000555c76642389 in advanced_inventory::print_items (this=0x7ffe51129dc0, pane=..., active=true) at src/advanced_inv.cpp:317
#12 0x0000555c76644b99 in advanced_inventory::redraw_pane (this=0x7ffe51129dc0, p=advanced_inventory::right) at src/advanced_inv.cpp:632
#13 0x0000555c76646138 in advanced_inventory::<lambda(const ui_adaptor&)>::operator() (__closure=<optimized out>, __closure=<optimized out>) at src/advanced_inv.cpp:1436
#14 std::_Function_handler<void(const ui_adaptor&), advanced_inventory::display()::<lambda(const ui_adaptor&)> >::_M_invoke(const std::_Any_data &, const ui_adaptor &) (__functor=..., __args#0=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/std_function.h:300
#15 0x0000555c77617a44 in std::function<void (ui_adaptor const&)>::operator()(ui_adaptor const&) const (__args#0=..., this=0x555c8a9d5b60) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/std_function.h:683
#16 ui_adaptor::redraw_invalidated () at src/ui_manager.cpp:224
#17 0x0000555c7760e86b in uilist::query (this=this@entry=0x7ffe51128e90, loop=loop@entry=true, timeout=timeout@entry=-1) at src/ui.cpp:804
#18 0x0000555c773fab71 in player::select_ammo (this=0x555c78974f60, base=..., opts=std::vector of length 2, capacity 2 = {...}) at src/player.cpp:2203
#19 0x0000555c773fbce6 in player::select_ammo (this=0x555c78974f60, base=..., prompt=prompt@entry=false, empty=empty@entry=true) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/stl_vector.h:99
#20 0x0000555c76a8c617 in game::reload (this=0x555c78920550, loc=..., prompt=<optimized out>, empty=<optimized out>) at src/game.cpp:8841
#21 0x0000555c76a8eb50 in game::inventory_item_menu(item_location, std::function<int ()> const&, std::function<int ()> const&, game::inventory_item_menu_positon) (this=0x555c78920550, locThisItem=..., iStartX=..., iWidth=..., position=<optimized out>) at src/game.cpp:2316
#22 0x0000555c76636d91 in advanced_inventory::action_examine (this=0x7ffe51129dc0, sitem=<optimized out>, spane=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/ext/atomicity.h:96
#23 0x0000555c76640f2c in advanced_inventory::display (this=0x7ffe51129dc0) at src/advanced_inv.cpp:1553
#24 0x0000555c7664126c in create_advanced_inv () at src/advanced_inv.cpp:70
#25 0x0000555c76b518f4 in game::handle_action (this=this@entry=0x555c78920550) at src/handle_action.cpp:1897
#26 0x0000555c76acace5 in game::do_turn (this=0x555c78920550) at src/game.cpp:1475
#27 0x0000555c764fc8d1 in main (argc=<optimized out>, argv=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/unique_ptr.h:360
```

# Steps To Reproduce

Open your inventory in AIM.
`e`xamine your gun.
`r`

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by l29ah** [comment]
Repro save: 
[2020.04.14.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4843079/2020.04.14.zip)
