### ISSUE TITLE
Segfault/crash when attempting to repair a PR-24 (retracted) with a soldering iron+1 (UPS)

### ISSUE THREAD

**Issue by Nhatorama** [CleverRaven/Cataclysm-DDA#42463]
# Describe the bug
Segfault/crash when attempting to repair a PR-24 (retracted) with a soldering iron+1 (UPS)
I do have a UPS with a heavy battery that has enough charge.

# Steps To Reproduce
1. Open the advanced inventory management screen.
2. Select the soldering iron+1 (UPS)
3. Press e
4. Press a
5. Select the PR-24 (retracted) in the inventory
6. Press enter

# Expected behavior
A segfault should not happen when repairing a PR-24 (retracted).

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.0.3; Codename: Lysia; 
- Game Version: 0.E-4405-ge092a04d93 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
[debugandcrashlogs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4977785/debugandcrashlogs.zip)
[Alta Vista.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4977786/Alta.Vista.zip) this is a "save file that occurs in the right conditions, just before the crash happens."

**Comment by anothersimulacrum** [comment]
```
Thread 1 "cataclysm-tiles" received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=this@entry=0x7fffffffda20, 
    __str=<error reading variable: Cannot access memory at address 0x28>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:259
259     /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc: No such file or directory.
(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=this@entry=0x7fffffffda20, 
    __str=<error reading variable: Cannot access memory at address 0x28>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:259
#1  0x00007ffff7d5638f in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__str=..., this=0x7fffffffda20)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:1335
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (this=0x7fffffffda20, __str=...)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:667
#3  0x0000555556edc67f in string_id<ammunition_type>::operator= (this=0x7fffffffda20) at src/string_id.h:44
#4  0x0000555556eccf93 in activity_handlers::repair_item_finish (act=<optimized out>, p=0x5555599e3630) at src/activity_handlers.cpp:2699
#5  0x0000555556edf0df in std::__invoke_impl<void, void (*&)(player_activity*, player*), player_activity*, player*> (__f=<optimized out>, 
    __args=<optimized out>, __args=<optimized out>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/bits/invoke.h:60
#6  0x0000555556edf074 in std::__invoke_r<void, void (*&)(player_activity*, player*), player_activity*, player*> (__fn=<optimized out>, 
    __args=<optimized out>, __args=<optimized out>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/bits/invoke.h:153
#7  0x0000555556edefb4 in std::_Function_handler<void (player_activity*, player*), void (*)(player_activity*, player*)>::_M_invoke(std::_Any_data const&, player_activity*&&, player*&&) (__functor=..., __args=<optimized out>, __args=<optimized out>)
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/bits/std_function.h:291
#8  0x0000555556f2b5e4 in std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const (this=0x555558d03718, 
    __args=0x5555599e3630, __args=0x5555599e3630) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../include/c++/10.1.0/bits/std_function.h:622
#9  0x0000555556f2a90d in activity_type::call_finish (this=<optimized out>, act=0x5555599e3bc8, p=0x5555599e3630) at src/activity_type.cpp:127
#10 0x0000555557ca12a0 in player_activity::do_turn (this=0x5555599e3bc8, p=...) at src/player_activity.cpp:296
#11 0x00005555573b9ed0 in game::process_activity (this=0x555559944a60) at src/game.cpp:1660
#12 0x00005555573b88d0 in game::do_turn (this=<optimized out>) at src/game.cpp:1485
#13 0x0000555557780d50 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:704
(gdb) f 4
#4  0x0000555556eccf93 in activity_handlers::repair_item_finish (act=<optimized out>, p=0x5555599e3630) at src/activity_handlers.cpp:2699
2699                    current_ammo = item_controller->find_template( used_tool->ammo_default() )->ammo->type;
```

**Comment by andrei8l** [comment]
I have a pretty hacky fix and atm no time to develop it further. The commit above fixes the crash and UPS use but I still need to fix:
1) UPS charges remaining in the repair UI
2) tool list in the action menu ( ^ )

Anyone can feel free to take over
