### ISSUE TITLE
Crash after getting the refugee center achievement

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#44621]
# Describe the bug
```
#0  0x00007f7610843fd1 in raise () from /lib64/libc.so.6
#1  0x00007f761082d538 in abort () from /lib64/libc.so.6
#2  0x000055c1551bc159 in signal_handler (sig=11) at src/crash.cpp:119
#3  <signal handler called>
#4  0x000055c155503532 in std::vector<string_id<itype>, std::allocator<string_id<itype> > >::size (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/move.h:49
#5  std::vector<string_id<itype>, std::allocator<string_id<itype> > >::vector (__x=..., this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_vector.h:555
#6  cata::flat_set<string_id<itype>, cata::transparent_less_than, std::vector<string_id<itype>, std::allocator<string_id<itype> > > >::flat_set (this=<optimized out>) at src/flat_set.h:29
#7  item_pocket::favorite_settings::favorite_settings (this=<optimized out>) at src/item_pocket.h:75
#8  item_pocket::item_pocket (this=<optimized out>) at src/item_pocket.h:38
#9  __gnu_cxx::new_allocator<std::_List_node<item_pocket> >::construct<item_pocket, item_pocket const&> (__p=<optimized out>, this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/ext/new_allocator.h:150
#10 std::allocator_traits<std::allocator<std::_List_node<item_pocket> > >::construct<item_pocket, item_pocket const&> (__p=<optimized out>, __a=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/alloc_traits.h:512
#11 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_create_node<item_pocket const&> (this=0x55c1bc253d38) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:637
#12 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_insert<item_pocket const&> (__position=..., this=0x55c1bc253d38) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:1911
#13 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::emplace_back<item_pocket const&> (this=0x55c1bc253d38) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:1227
#14 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_initialize_dispatch<std::_List_const_iterator<item_pocket> > (__last=..., __first=<error reading variable: Cannot access memory at address 0x55c1bd063>, this=0x55c1bc253d38) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:1840
#15 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::list (__x=std::__cxx11::list = {...}, this=0x55c1bc253d38) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:738
#16 item_contents::item_contents (this=0x55c1bc253d38) at src/item_contents.h:35
#17 item::item (this=0x55c1bc253d30) at src/item.cpp:489
#18 0x000055c1555494c7 in __gnu_cxx::new_allocator<std::_List_node<item> >::construct<item, item const&> (__p=0x55c1bc253d30, this=0x55c1bd0515c8) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/new:175
#19 std::allocator_traits<std::allocator<std::_List_node<item> > >::construct<item, item const&> (__p=0x55c1bc253d30, __a=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/alloc_traits.h:512
#20 std::__cxx11::list<item, std::allocator<item> >::_M_create_node<item const&> (this=0x55c1bd0515c8) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:637
#21 std::__cxx11::list<item, std::allocator<item> >::_M_insert<item const&> (__position=..., this=0x55c1bd0515c8) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:1911
#22 std::__cxx11::list<item, std::allocator<item> >::emplace_back<item const&> (this=0x55c1bd0515c8) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:1227
#23 std::__cxx11::list<item, std::allocator<item> >::_M_initialize_dispatch<std::_List_const_iterator<item> > (__last=..., __first={
  <visitable<item>> = {<No data fields>}, 
  members of item:
  static INFINITE_CHARGES = 2147483647,
  type = 0x55c15b35b658,
  contents = {
    contents = std::__cxx11::list = {
      [0] = {
        settings = {
          priority_rating = 0,
          item_whitelist = {
            <cata::transparent_less_than> = {<No data fields>}, 
            <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity 0, <No data fields>},
          item_blacklist = {
            <cata::transparent_less_than> = {<No data fields>}, 
            <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity 0, <No data fields>},
          category_whitelist = {
            <cata::transparent_less_than> = {<No data fields>}, 
            <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity 0, <No data fields>},
          category_blacklist = {
            <cata::transparent_less_than> = {<No data fields>}, 
            <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity 0, <No data fields>}
        },
        _saved_type = item_pocket::pocket_type::LAST,
        _saved_sealed = false,
        data = 0x55c15b35bf00,
        contents = empty std::__cxx11::list,
        _sealed = false
      }<error reading variable: Cannot access memory at address 0x55c1bd063>
      ...
    }
  },
  components = empty std::__cxx11::list,
  faults = std::set with 0 elements,
  item_tags = {
    <cata::transparent_less_than> = {<No data fields>}, 
    <std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = std::vector of length 0, capacity 0, <No data fields>},
  anchor = {
    impl = std::shared_ptr<safe_reference_anchor::empty> (use count 1466216464, weak count 21952) = {
      get() = 0x55c1b813f890
    }
  },
  curammo = 0x0,
  item_vars = std::map with 1 element = {
    [<error: Cannot access memory at address 0x6978655f65707974>] = <error: Cannot access memory at address 0x6349676e69727473>
  },
  corpse = 0x0,
  corpse_name = "",
  techniques = std::set with 0 elements,
  craft_data_ = {
    <std::unique_ptr<item::craft_data, std::default_delete<item::craft_data> >> = std::unique_ptr<item::craft_data> = {
      get() = 0x0
    }, <No data fields>},
  relic_data = {
    <std::unique_ptr<relic, std::default_delete<relic> >> = std::unique_ptr<relic> = {
      get() = 0x0
    }, <No data fields>},
  charges = 0,
  energy = {
    value_ = 0
  },
  recipe_charges = 1,
  burnt = 0,
  poison = 0,
  frequency = 0,
  snip_id = {
    _id = "null",
    _cid = -1,
    _version = -1
  },
  irradiation = 0,
  item_counter = 0,
  specific_energy = -10,
  temperature = 0,
  mission_id = -1,
  player_id = -1,
  ethereal = false,
  encumbrance_update_ = false,
  rot = {
    turns_ = 0,
    static units = {
      <std::_Vector_base<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, time_duration>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, time_duration> > >> = {
        _M_impl = {
          <std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, time_duration> >> = {
            <__gnu_cxx::new_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, time_duration> >> = {<No data fields>}, <No data fields>}, 
          <std::_Vector_base<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, time_duration>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, time_duration> > >::_Vector_impl_data> = {
            _M_start = 0x55c157687000,
            _M_finish = 0x55c157687258,
            _M_end_of_storage = 0x55c157687258
          }, <No data fields>}
      }, <No data fields>}
  },
  last_temp_check = {
    turn_ = 0
  },
  bday = {
    turn_ = 23622476
  },
  current_phase = phase_id::SOLID,
  owner = {
    _id = "free_merchants",
    _cid = -1,
    _version = -1
  },
  old_owner = {
    _id = "NULL",
    _cid = -1,
    _version = -1
  },
  damage_ = 0,
  light = {
    luminance = 0,
    width = 0,
    direction = 0
  },
  cached_relative_encumbrance = {
    {
      dummy = 0 '\000',
      data = 0
    },
    full = false
  },
  invlet = 0 '\000',
  active = false,
  is_favorite = false
}, this=0x55c1bd0515c8) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:1840
#24 std::__cxx11::list<item, std::allocator<item> >::list (__x=std::__cxx11::list<error reading variable: Cannot access memory at address 0x5f6e6f6974617265>, this=0x55c1bd0515c8) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:738
#25 item_pocket::item_pocket (this=0x55c1bd051550) at src/item_pocket.h:38
#26 __gnu_cxx::new_allocator<std::_List_node<item_pocket> >::construct<item_pocket, item_pocket const&> (__p=0x55c1bd051550, this=0x7fffc125bb80) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/ext/new_allocator.h:150
#27 std::allocator_traits<std::allocator<std::_List_node<item_pocket> > >::construct<item_pocket, item_pocket const&> (__p=0x55c1bd051550, __a=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/alloc_traits.h:512
#28 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_create_node<item_pocket const&> (this=0x7fffc125bb80) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:637
#29 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_insert<item_pocket const&> (__position=..., this=0x7fffc125bb80) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:1911
#30 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::emplace_back<item_pocket const&> (this=0x7fffc125bb80) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:1227
#31 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_initialize_dispatch<std::_List_const_iterator<item_pocket> > (__last={
  settings = {
    priority_rating = 4,
    item_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity -1964387257342, <No data fields>},
    item_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity 0, <No data fields>},
    category_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity -1964387257342, <No data fields>},
    category_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity 0, <No data fields>}
  },
  _saved_type = -1794192208,
  _saved_sealed = 193,
  data = 0x55c1950ecca0,
  contents = std::__cxx11::list = {
    [0] = <error reading variable>, __first={
  settings = {
    priority_rating = 1595954976,
    item_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 5993506689873130, capacity -6917588041802 = {[0] = <error reading variable>,
    item_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 4239573390865999, capacity 28647315458440074 = {[0] = <error reading variable>,
    category_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 97578268154834884, capacity 50765549054302863 = {[0] = <error reading variable>,
    category_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length -93074296540929862, capacity -31694934131452608 = {[0] = <error reading variable>
  },
  _saved_type = 1397048645,
  _saved_sealed = 54,
  data = 0x6d756e6533325f54,
  contents = std::__cxx11::list<error reading variable: Cannot access memory at address 0x5f6e6f6974617265>,
  _sealed = 73
}, this=0x7fffc125bb80) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:1840
#32 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::list<std::_List_const_iterator<item_pocket>, void> (__a=..., __last={
  settings = {
    priority_rating = 4,
    item_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity -1964387257342, <No data fields>},
    item_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity 0, <No data fields>},
    category_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity -1964387257342, <No data fields>},
    category_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity 0, <No data fields>}
  },
  _saved_type = -1794192208,
  _saved_sealed = 193,
  data = 0x55c1950ecca0,
  contents = std::__cxx11::list = {
    [0] = <error reading variable>, __first=..., this=0x7fffc125bb80) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:806
#33 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::insert<std::_List_const_iterator<item_pocket>, void> (this=this@entry=0x55c1bd056c30, __position=..., __position@entry={
  settings = {
    priority_rating = 0,
    item_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity -1964387256214, <No data fields>},
    item_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity 0, <No data fields>},
    category_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity -1964387256215, <No data fields>},
    category_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity 0, <No data fields>}
  },
  _saved_type = -1123664848,
  _saved_sealed = 193,
  data = 0x55c1bd063c20,
  contents = std::__cxx11::list = {
    [0] = <error reading variable>, __first=..., __last=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/list.tcc:137
#34 0x000055c155504b14 in std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_M_assign_dispatch<std::_List_const_iterator<item_pocket> > (this=this@entry=0x55c1bd056c30, __first2=..., __last2=..., __last2@entry={
  settings = {
    priority_rating = 4,
    item_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity -1964387257342, <No data fields>},
    item_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<itype>, std::allocator<string_id<itype> > >> = std::vector of length 0, capacity 0, <No data fields>},
    category_whitelist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity -1964387257342, <No data fields>},
    category_blacklist = {
      <cata::transparent_less_than> = {<No data fields>}, 
      <std::vector<string_id<item_category>, std::allocator<string_id<item_category> > >> = std::vector of length 0, capacity 0, <No data fields>}
  },
  _saved_type = -1794192208,
  _saved_sealed = 193,
  data = 0x55c1950ecca0,
  contents = std::__cxx11::list = {
    [0] = <error reading variable>) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:286
#35 0x000055c155504b5f in std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::operator= (__x=std::__cxx11::list = {...}, this=0x55c1bd056c30) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/stl_list.h:972
#36 std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::operator= (__x=std::__cxx11::list = {...}, this=0x55c1bd056c30) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/list.tcc:267
#37 item_contents::operator= (this=<optimized out>) at src/item_contents.h:35
#38 item::operator= (this=this@entry=0x55c1bd056c28) at src/item.cpp:492
#39 0x000055c155afc8f4 in npc::wield (this=0x55c1bd056520, it=...) at src/npc.cpp:1161
#40 0x000055c155b327ce in npc::wield_better_weapon (this=0x55c1bd056520) at src/npcmove.cpp:3442
#41 0x000055c155b32ac6 in npc::move_pause (this=0x55c1bd056520) at src/npcmove.cpp:2699
#42 0x000055c155b3d64a in npc::execute_action (this=0x55c1bd056520, action=<optimized out>) at src/npcmove.cpp:1313
#43 0x000055c155b417e1 in npc::move (this=0x55c1bd056520) at src/npcmove.cpp:976
#44 0x000055c15537fca6 in game::monmove (this=0x55c1579f61c0) at src/game.cpp:4600
#45 0x000055c15539b4e4 in game::do_turn (this=0x55c1579f61c0) at src/game.cpp:1578
#46 0x000055c154d59770 in main (argc=<optimized out>, argv=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include/g++-v10/bits/unique_ptr.h:421
```

# Steps To Reproduce
dunno

# Expected behavior

# Screenshots

# Versions and configuration
```
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-6482-g2cb9acdb40-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

# Additional context

**Comment by l29ah** [comment]
Probably a dupe of https://github.com/CleverRaven/Cataclysm-DDA/issues/44196 though with a better backtrace.
