### ISSUE TITLE
Json errors during mod info loading cause segfault if there is a pending window resize event.

### ISSUE THREAD

**Issue by shacknetisp** [CleverRaven/Cataclysm-DDA#46129]
# Describe the bug

Json errors (such as the "did not visit" error from #45635) during mod info loading cause a crash if there is a pending window resize event.
I believe this is because displaying the error message handles window events, but the window resizes event ends up trying to call `g->init_ui()` before `g` is actually set, the call actually happens during the `game` constructor.

# Steps To Reproduce

On commit 838ce8c564179b6e7aa0f173494038a343fe64a2 compiled debug for SDL tiles, use  a blank config, with one additional single-file mod, with its modinfo.json being:
```
[
  {
    "type": "MOD_INFO",
    "ident": "shacknetisp_test_mod",
    "name": "Shacknetisp Test Mod",
    "category": "misc_additions",
    "doesnotexist": "this one doesn't exist, to cause an error"
  }
]
```

1. Load `cataclysm-tiles` into a debugger.
2. Set a breakpoint at `sdltiles.cpp:3011`, which is immediately after the call to `WinCreate()`.
3. Run CDDA.
4. Once the breakpoint is hit, resize the newly created window to put a resize event in the event queue.
5. Continue running, there will be a crash while handling SDL events during display of the JSON mod error message.

Alternatively, use a window manager that sends a resize event when a new window is created.

# Expected behavior

No crash occurs, and ideally the error message is still displayed graphically.

# Versions and configuration

`make -j4 cataclysm-tiles RELEASE=0 SOUND=1 LTO=1 TILES=1 USE_HOME_DIR=1 ASTYLE=0 CCACHE=1 PCH=1`

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.5 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.E-8298-g838ce8c564 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

My GDB session:
```
Thread 1 "cataclysm-tiles" hit Breakpoint 1, catacurses::init_interface () at src/sdltiles.cpp:3011
3011	    dbg( D_INFO ) << "Initializing SDL Tiles context";
(gdb) c
Continuing.

Thread 1 "cataclysm-tiles" received signal SIGSEGV, Segmentation fault.
0x0000555557abb6ad in game::init_ui (this=0x0, resized=true) at src/game.cpp:505
505	        pixel_minimap_option = get_option<bool>( "PIXEL_MINIMAP" );
(gdb) bt
#0  0x0000555557abb6ad in game::init_ui (this=0x0, resized=true) at src/game.cpp:505
#1  0x0000555557b2db91 in game_ui::init_ui () at src/game.cpp:12358
#2  0x0000555558c50658 in handle_resize (w=1916, h=1009) at src/sdltiles.cpp:1356
#3  0x0000555558c50c50 in CheckMessages () at src/sdltiles.cpp:2492
#4  0x0000555558c5338c in input_manager::get_input_event (this=0x555559ef2b20 <inp_mngr>, preferred_keyboard_mode=keyboard_mode::keycode) at src/sdltiles.cpp:3113
#5  0x000055555786c33d in debug_error_prompt (filename=0x5555590a4484 "src/json.cpp", line=0x5555590a4480 "120", 
    funcname=0x5555590a4e80 <JsonObject::report_unvisited() const::__PRETTY_FUNCTION__> "void JsonObject::report_unvisited() const", 
    text=0x55555a45d480 "(json-error)\nJson error: /home/user/.cataclysm-dda/mods//test/modinfo.json:7:20: Failed to visit member doesnotexist in JsonObject\n\n    \"name\": \"Shacknetisp Test Mod\",\n    \"category\": \"misc_additions\""...) at src/debug.cpp:249
#6  0x000055555786c936 in realDebugmsg (filename=0x5555590a4484 "src/json.cpp", line=0x5555590a4480 "120", funcname=0x5555590a4e80 <JsonObject::report_unvisited() const::__PRETTY_FUNCTION__> "void JsonObject::report_unvisited() const", 
    text="(json-error)\nJson error: /home/user/.cataclysm-dda/mods//test/modinfo.json:7:20: Failed to visit member doesnotexist in JsonObject\n\n    \"name\": \"Shacknetisp Test Mod\",\n    \"category\": \"misc_additions\""...)
    at src/debug.cpp:306
#7  0x000055555723c3be in realDebugmsg<char const*> (filename=0x5555590a4484 "src/json.cpp", line=0x5555590a4480 "120", 
    funcname=0x5555590a4e80 <JsonObject::report_unvisited() const::__PRETTY_FUNCTION__> "void JsonObject::report_unvisited() const", mes=0x5555590a4470 "(json-error)\n%s") at src/debug.h:80
#8  0x0000555558063743 in JsonObject::report_unvisited (this=0x7fffffffcf30) at src/json.cpp:120
#9  0x0000555558063796 in JsonObject::finish (this=0x7fffffffcf30) at src/json.cpp:130
#10 0x000055555847d8a6 in mod_manager::<lambda(JsonIn&)>::operator()(JsonIn &) const (__closure=0x7fffffffd450, jsin=...) at src/mod_manager.cpp:369
#11 0x000055555847f20c in std::_Function_handler<void(JsonIn&), mod_manager::load_mod_info(const string&)::<lambda(JsonIn&)> >::_M_invoke(const std::_Any_data &, JsonIn &) (__functor=..., __args#0=...)
    at /usr/include/c++/7/bits/std_function.h:316
#12 0x0000555557582367 in std::function<void (JsonIn&)>::operator()(JsonIn&) const (this=0x7fffffffd450, __args#0=...) at /usr/include/c++/7/bits/std_function.h:706
#13 0x000055555757fa45 in <lambda(std::istream&)>::operator()(std::istream &) const (__closure=0x7fffffffd3d0, fin=...) at src/cata_utility.cpp:390
#14 0x0000555557580d11 in std::_Function_handler<void(std::basic_istream<char, std::char_traits<char> >&), read_from_file_optional_json(const string&, const std::function<void(JsonIn&)>&)::<lambda(std::istream&)> >::_M_invoke(const std::_Any_data &, std::basic_istream<char, std::char_traits<char> > &) (__functor=..., __args#0=...) at /usr/include/c++/7/bits/std_function.h:316
#15 0x0000555557582315 in std::function<void (std::istream&)>::operator()(std::istream&) const (this=0x7fffffffd3d0, __args#0=...) at /usr/include/c++/7/bits/std_function.h:706
#16 0x000055555757f62b in read_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)> const&) (path="/home/user/.cataclysm-dda/mods//test/modinfo.json", 
    reader=...) at src/cata_utility.cpp:349
#17 0x000055555757f9e1 in read_from_file_optional(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::istream&)> const&) (
    path="/home/user/.cataclysm-dda/mods//test/modinfo.json", reader=...) at src/cata_utility.cpp:382
#18 0x000055555757fad9 in read_from_file_optional_json(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (JsonIn&)> const&) (
    path="/home/user/.cataclysm-dda/mods//test/modinfo.json", reader=...) at src/cata_utility.cpp:391
#19 0x000055555847da14 in mod_manager::load_mod_info (this=0x55555a503a10, info_file_path="/home/user/.cataclysm-dda/mods//test/modinfo.json") at src/mod_manager.cpp:357
#20 0x000055555847b984 in mod_manager::load_mods_from (this=0x55555a503a10, path="/home/user/.cataclysm-dda/mods/") at src/mod_manager.cpp:198
#21 0x000055555847b22f in mod_manager::refresh_mod_list (this=0x55555a503a10) at src/mod_manager.cpp:144
#22 0x000055555847af5d in mod_manager::mod_manager (this=0x55555a503a10) at src/mod_manager.cpp:110
#23 0x0000555558fa82b0 in pimpl<mod_manager>::pimpl (this=0x55555a31d9e8) at src/pimpl.h:41
#24 0x0000555558f92f1e in worldfactory::worldfactory (this=0x55555a31d970) at src/worldfactory.cpp:107
#25 0x0000555557b4c56c in std::make_unique<worldfactory> () at /usr/include/c++/7/bits/unique_ptr.h:821
#26 0x0000555557aba515 in game::game (this=0x55555b143560) at src/game.cpp:352
#27 0x000055555814e9aa in std::make_unique<game> () at /usr/include/c++/7/bits/unique_ptr.h:821
#28 0x000055555814734a in main (argc=1, argv=0x7fffffffdd98) at src/main.cpp:633
```

**Comment by ZhilkinSerg** [comment]
I know there is no any minigame to play while loading, but why play with CDDA window size?

**Comment by shacknetisp** [comment]
Tiling window managers like to mess with window sizes early. This is actually a very visible/annoying bug in that case.
