### ISSUE TITLE
Mininukes/explosions in general too weak against vehicles

### ISSUE THREAD

**Issue by KittyTac** [CleverRaven/Cataclysm-DDA#46877]
# Describe the bug

In my testing. mininukes, while they heavily damaged vehicles for sure, don't really destroy them as expected. Which is weird since they can destroy many cubic meters of solid rock but a car parked point-blank to the nuke doesn't even get reduced to its frame or vaporized,

# Steps To Reproduce

1. Spawn in a mininuke,
2. Spawn in a car.
3. Place the mininuke inside the car and set the timer.
4. Run to a safe distance then examine the car. It might not get damaged all that much and some parts may even be reinforced due to what I think is overflow (see screenshot below):

# Expected behavior

The vehicle gets completely destroyed.

# Screenshots

![image](https://user-images.githubusercontent.com/52408044/105023032-08347700-5a7d-11eb-9ad2-f289fa77198a.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8740-g618a3be [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP]
]

# Additional context

None.

**Comment by anothersimulacrum** [comment]
You can see that the frame is reinforced there - if this was running a build with UBsan, you'd probably see that it's triggering integer overflow.

**Comment by KittyTac** [comment]
> You can see that the frame is reinforced there - if this was running a build with UBsan, you'd probably see that it's triggering integer overflow.

Sorry for the late reply, but it wasn't reinforced before the explosion. So yeah, overflow.

**Comment by hexagonrecursion** [comment]
Confirmed
```
src/vehicle_part.cpp:595:60: runtime error: signed integer overflow: 4000 * -1199994 cannot be represented in type 'int'
    #0 0x6e34474 in vehicle::mod_hp(vehicle_part&, int, damage_type) /home/user/Cataclysm-DDA/src/vehicle_part.cpp:595:60
    #1 0x6d28cc8 in vehicle::damage_direct(int, int, damage_type) /home/user/Cataclysm-DDA/src/vehicle.cpp:6636:9
    #2 0x6d39f6c in vehicle::damage(int, int, damage_type, bool) /home/user/Cataclysm-DDA/src/vehicle.cpp:6374:24
    #3 0x528fd47 in map::bash_vehicle(tripoint const&, bash_params&) /home/user/Cataclysm-DDA/src/map.cpp:3515:23
    #4 0x52750b9 in map::bash(tripoint const&, int, bool, bool, bool, vehicle const*) /home/user/Cataclysm-DDA/src/map.cpp:3468:9
    #5 0x4309f89 in explosion_handler::do_blast(tripoint const&, float, float, bool) /home/user/Cataclysm-DDA/src/explosion.cpp:171:10
    #6 0x4308f5e in explosion_handler::_make_explosion(tripoint const&, explosion_data const&) /home/user/Cataclysm-DDA/src/explosion.cpp:534:9
    #7 0x43176e2 in explosion_handler::process_explosions() /home/user/Cataclysm-DDA/src/explosion.cpp:884:9
    #8 0x40fbff5 in do_turn() /home/user/Cataclysm-DDA/src/do_turn.cpp:973:5
    #9 0x5218a84 in main /home/user/Cataclysm-DDA/src/main.cpp:710:17
    #10 0x7c897e9421e1 in __libc_start_main (/lib64/libc.so.6+0x281e1)
    #11 0x2ff76fd in _start (/home/user/sanitize-undefined,address/sanitize-undefined,addresscataclysm-tiles+0x2ff76fd)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/vehicle_part.cpp:595:60 in 
```

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 33 (Thirty Three); Release: 33; Codename: ThirtyThree; 
- Game Version: 0.F-2000-g1f102d36db [64-bit] 1f102d36db
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
