### ISSUE TITLE
Item errors and crash when loading save

### ISSUE THREAD

**Issue by matskuman5** [CleverRaven/Cataclysm-DDA#49884]
### Describe the bug

Loading the save produces a bunch of errors about items, then CTD. There is no crash.log file generated (as far as I can tell).

 DEBUG    : Failed to find item_location owner with character_id 1

 FUNCTION : bool item_location::impl::item_on_person::ensure_who_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 290

 DEBUG    : item_location lost its target item during a save/load cycle

 FUNCTION : void item_location::impl::ensure_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 114

 DEBUG    : parent location does not point to valid item

 FUNCTION : void item_location::deserialize(JsonIn&)
 FILE     : src/item_location.cpp
 LINE     : 782

 DEBUG    : item_location lost its target item during a save/load cycle

 FUNCTION : void item_location::impl::ensure_unpacked() const
 FILE     : src/item_location.cpp
 LINE     : 114

The crash occurs when I press spacebar to continue after the last error message

### Steps To Reproduce

1. Load the provided save with Fred "Indigo" Steiner character in Blackstock
2. Press space to skip the errors
3. Crash

### Expected behavior

No crashes

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[Blackstock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6801398/Blackstock.zip)

**Comment by pehamm** [comment]
Can replicate, although I suspect some corruption of the save file. The world has two chracters simultaneously, which is always great fun.

Here is a crash.log with debug symbols:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6803830/crash.log)

**Comment by hexagonrecursion** [comment]
Confirmed 1f102d36db Cataclysm DDA version 0.F-2000-g1f102d36db

UBSan:
```UBSan
src/item_location.cpp:728:12: runtime error: reference binding to null pointer of type 'item'
    #0 0x4d8920f in item_location::operator*() /home/user/Cataclysm-DDA/src/item_location.cpp:728:5
    #1 0x4f94f9c in repair_item_actor::repair(Character&, item&, item_location&) const /home/user/Cataclysm-DDA/src/iuse_actor.cpp:3052:33
    #2 0x32fd243 in activity_handlers::repair_item_finish(player_activity*, Character*) /home/user/Cataclysm-DDA/src/activity_handlers.cpp:2371:64
    #3 0x333ef44 in void std::__invoke_impl<void, void (*&)(player_activity*, Character*), player_activity*, Character*>(std::__invoke_other, void (*&)(player_activity*, Character*), player_activity*&&, Character*&&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60:14
    #4 0x333ee70 in std::enable_if<__and_<std::is_void<void>, std::__is_invocable<void (*&)(player_activity*, Character*), player_activity*, Character*> >::value, void>::type std::__invoke_r<void, void (*&)(player_activity*, Character*), player_activity*, Character*>(void (*&)(player_activity*, Character*), player_activity*&&, Character*&&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:153:7
    #5 0x333ecea in std::_Function_handler<void (player_activity*, Character*), void (*)(player_activity*, Character*)>::_M_invoke(std::_Any_data const&, player_activity*&&, Character*&&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291:9
    #6 0x33fcdbb in std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622:14
    #7 0x33fada6 in activity_type::call_finish(player_activity*, Character*) const /home/user/Cataclysm-DDA/src/activity_type.cpp:117:9
    #8 0x6432039 in player_activity::do_turn(Character&) /home/user/Cataclysm-DDA/src/player_activity.cpp:332:24
    #9 0x40fa6d9 in do_turn() /home/user/Cataclysm-DDA/src/do_turn.cpp:865:20
    #10 0x5218a84 in main /home/user/Cataclysm-DDA/src/main.cpp:710:17
    #11 0x74888688a1e1 in __libc_start_main (/lib64/libc.so.6+0x281e1)
    #12 0x2ff76fd in _start (/home/user/sanitize-undefined,address/sanitize-undefined,addresscataclysm-tiles+0x2ff76fd)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/item_location.cpp:728:12 in 
```

debug.log:
```
-----------------------------------------
10:43:29.084 : Starting log.
10:43:29.092 INFO : Cataclysm DDA version 0.F-2000-g1f102d36db
10:43:29.112 INFO : [main] C locale set to C.UTF-8
10:43:29.112 INFO : [main] C++ locale set to C.UTF-8
10:43:29.112 INFO : SDL version used during compile is 2.0.14
10:43:29.116 INFO : SDL version used during linking and in runtime is 2.0.14
10:43:29.563 WARNING : opendir [lang/mo/] failed with "No such file or directory".
10:43:29.581 INFO : Number of render drivers on your system: 4
10:43:29.581 INFO : Render driver: 0/opengl
10:43:29.581 INFO : Render driver: 1/opengles2
10:43:29.581 INFO : Render driver: 2/opengles
10:43:29.581 INFO : Render driver: 3/software
10:43:29.624 INFO : [options] C locale set to en_US.UTF-8
10:43:29.624 INFO : [options] C++ locale set to en_US.UTF-8
10:43:29.624 INFO : Setting language to: 'en'
10:43:29.624 INFO : Language is set to: 'en'
10:43:29.848 INFO : Active renderer: 3/software
10:43:29.924 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
10:43:30.044 INFO : Setting language to: 'en'
10:43:30.044 INFO : Language is set to: 'en'
10:43:30.405 WARNING : opendir [./mods/] failed with "No such file or directory".
10:43:59.339 WARNING : opendir [./save/Blackstock/mods] failed with "No such file or directory".
10:45:18.513 INFO : Loaded tileset: brownlikebears
10:46:18.453 ERROR : (error message will follow backtrace)
    ./sanitize-undefined,addresscataclysm-tiles() [0x3042d01]
    ./sanitize-undefined,addresscataclysm-tiles(debug_write_backtrace(std::ostream&)+0x13a) [0x3f8cb3a]
    ./sanitize-undefined,addresscataclysm-tiles(DebugLog(DebugLevel, DebugClass)+0x2ed) [0x3f8b57d]
    ./sanitize-undefined,addresscataclysm-tiles(realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x10f) [0x3f8ae7f]
    ./sanitize-undefined,addresscataclysm-tiles(void realDebugmsg<int>(char const*, char const*, char const*, char const*, int&&)+0xdc) [0x3525edc]
    ./sanitize-undefined,addresscataclysm-tiles(item_location::impl::item_on_person::ensure_who_unpacked() const+0x2dd) [0x4d994bd]
    ./sanitize-undefined,addresscataclysm-tiles(item_location::impl::item_on_person::valid() const+0x8c) [0x4d9906c]
    ./sanitize-undefined,addresscataclysm-tiles(item_location::deserialize(JsonIn&)+0x970) [0x4d89ed0]
    ./sanitize-undefined,addresscataclysm-tiles(decltype ((({parm#1}.deserialize)(*this)),(true)) JsonIn::read<item_location>(item_location&, bool)+0x2c) [0x32ac27c]
    ./sanitize-undefined,addresscataclysm-tiles(decltype ((({parm#1}.front)()),(true)) JsonIn::read<std::vector<item_location, std::allocator<item_location> >, (void*)0>(std::vector<item_location, std::allocator<item_location> >&, bool)+0x144) [0x32c2984]
    ./sanitize-undefined,addresscataclysm-tiles(bool JsonObject::read<std::vector<item_location, std::allocator<item_location> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<item_location, std::allocator<item_location> >&, bool) const+0xa7) [0x325a4f7]
    ./sanitize-undefined,addresscataclysm-tiles(player_activity::deserialize(JsonIn&)+0xc5e) [0x67bc74e]
    ./sanitize-undefined,addresscataclysm-tiles(decltype ((({parm#1}.deserialize)(*this)),(true)) JsonIn::read<player_activity>(player_activity&, bool)+0x2c) [0x685e30c]
    ./sanitize-undefined,addresscataclysm-tiles(bool JsonObject::read<player_activity>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, player_activity&, bool) const+0xa7) [0x6835297]
    ./sanitize-undefined,addresscataclysm-tiles(Character::load(JsonObject const&)+0x2e64) [0x67c4754]
    ./sanitize-undefined,addresscataclysm-tiles(avatar::load(JsonObject const&)+0x3a5) [0x67e6e95]
    ./sanitize-undefined,addresscataclysm-tiles(avatar::deserialize(JsonIn&)+0x13b) [0x67e69eb]
    ./sanitize-undefined,addresscataclysm-tiles(decltype ((({parm#1}.deserialize)(*this)),(true)) JsonIn::read<avatar>(avatar&, bool)+0xab) [0x679f24b]
    ./sanitize-undefined,addresscataclysm-tiles(bool JsonObject::read<avatar>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, avatar&, bool) const+0xa7) [0x6794847]
    ./sanitize-undefined,addresscataclysm-tiles(game::unserialize(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1f69) [0x6780669]

    Attempting to repeat stack trace using debug symbols…
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/item_location.cpp:291 [bool item_location::impl::item_on_person::ensure_who_unpacked() const] Failed to find item_location owner with character_id 1
10:46:53.384 ERROR : src/item_location.cpp:291 [bool item_location::impl::item_on_person::ensure_who_unpacked() const] Failed to find item_location owner with character_id 1
10:47:14.537 ERROR : src/item_location.cpp:115 [void item_location::impl::ensure_unpacked() const] item_location lost its target item during a save/load cycle
10:47:15.733 ERROR : src/item_location.cpp:786 [void item_location::deserialize(JsonIn &)] parent location does not point to valid item
10:47:25.025 ERROR : (error message will follow backtrace)
    ./sanitize-undefined,addresscataclysm-tiles() [0x3042d01]
    ./sanitize-undefined,addresscataclysm-tiles(debug_write_backtrace(std::ostream&)+0x13a) [0x3f8cb3a]
    ./sanitize-undefined,addresscataclysm-tiles(DebugLog(DebugLevel, DebugClass)+0x2ed) [0x3f8b57d]
    ./sanitize-undefined,addresscataclysm-tiles(realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x10f) [0x3f8ae7f]
    ./sanitize-undefined,addresscataclysm-tiles(void realDebugmsg<>(char const*, char const*, char const*, char const*)+0xc9) [0x30e29f9]
    ./sanitize-undefined,addresscataclysm-tiles(item_location::impl::ensure_unpacked() const+0x320) [0x4d92c20]
    ./sanitize-undefined,addresscataclysm-tiles(item_location::impl::target() const+0x7c) [0x4d9109c]
    ./sanitize-undefined,addresscataclysm-tiles(item_location::operator*()+0x8d) [0x4d891cd]
    ./sanitize-undefined,addresscataclysm-tiles(repair_item_actor::repair(Character&, item&, item_location&) const+0x22d) [0x4f94f9d]
    ./sanitize-undefined,addresscataclysm-tiles(activity_handlers::repair_item_finish(player_activity*, Character*)+0x784) [0x32fd244]
    ./sanitize-undefined,addresscataclysm-tiles(void std::__invoke_impl<void, void (*&)(player_activity*, Character*), player_activity*, Character*>(std::__invoke_other, void (*&)(player_activity*, Character*), player_activity*&&, Character*&&)+0x85) [0x333ef45]
    ./sanitize-undefined,addresscataclysm-tiles(_ZSt10__invoke_rIvRPFvP15player_activityP9CharacterEJS1_S3_EENSt9enable_ifIXsr6__and_ISt7is_voidIT_ESt14__is_invocableIT0_JDpT1_EEEE5valueES9_E4typeEOSC_DpOSD_+0x41) [0x333ee71]
    ./sanitize-undefined,addresscataclysm-tiles(std::_Function_handler<void (player_activity*, Character*), void (*)(player_activity*, Character*)>::_M_invoke(std::_Any_data const&, player_activity*&&, Character*&&)+0x4b) [0x333eceb]
    ./sanitize-undefined,addresscataclysm-tiles(std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const+0x15c) [0x33fcdbc]
    ./sanitize-undefined,addresscataclysm-tiles(activity_type::call_finish(player_activity*, Character*) const+0x157) [0x33fada7]
    ./sanitize-undefined,addresscataclysm-tiles(player_activity::do_turn(Character&)+0x1a1a) [0x643203a]
    ./sanitize-undefined,addresscataclysm-tiles(do_turn()+0x103a) [0x40fa6da]
    ./sanitize-undefined,addresscataclysm-tiles(main+0xb25) [0x5218a85]
    /lib64/libc.so.6(__libc_start_main+0xf2) [0x74888688a1e2]
    ./sanitize-undefined,addresscataclysm-tiles(_start+0x2e) [0x2ff76fe]

    Attempting to repeat stack trace using debug symbols…
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    backtrace: Binary name not safe
    __libc_start_main
    ??:?
Backtrace emission took 1 seconds.
(continued from above) ERROR : src/item_location.cpp:115 [void item_location::impl::ensure_unpacked() const] item_location lost its target item during a save/load cycle
```
