### ISSUE TITLE
Game crashes generating faction camp recipes when any of the components has_temperature()

### ISSUE THREAD

**Issue by chrispikula** [CleverRaven/Cataclysm-DDA#50493]
### Describe the bug

It turns out that when you desire to eat the choicest pieces of rock on the ground, the world has it's revenge by not allowing your existence.  

10/10, I had a very good existential horror metagame.  Sadly, that's not part of the design doc, so there probably should be a fix.

### Steps To Reproduce

Load the game with the following mod:

Thanks to @anothersimulacrum for the code snippet!
`[
  {
    "type": "MOD_INFO",
    "id": "breaks_everything",
    "name": "Crash the game with this one weird trick!",
    "description": "Contributors hate him!",
    "category": "content"
  },
  {
    "type": "COMESTIBLE",
    "id": "rock",
    "copy-from": "rock",
    "symbol": "*",
    "color": "light_gray",
    "name": { "str": "rock" },
    "description": "a rock the size of a baseball.  makes a decent melee weapon, and is also good for throwing at enemies."
  }
]`

### Expected behavior

Being able to char gen, load the game.

### Versions and configuration

Win 10, tiles, b840294.

[game report.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/6935986/game.report.txt)

**Comment by Hirmuolio** [comment]
It seems like mapgen problem.

Making rock into comestible gives it temperature.
It then tries to get the heat radiation that does not exst before the game properly begins.

**Comment by hexagonrecursion** [comment]
```
src/submap.h:309:24: runtime error: member call on null pointer of type 'submap'
    #0 0x45b0dec in maptile::find_field(int_id<field_type> const&) /home/user/Cataclysm-DDA/src/submap.h:309:24
    #1 0x448244c in maptile_field_intensity(maptile&, int_id<field_type>) /home/user/Cataclysm-DDA/src/game.cpp:1270:39
    #2 0x4481c64 in get_heat_radiation(tripoint const&, bool) /home/user/Cataclysm-DDA/src/game.cpp:1291:21
    #3 0x6ed2726 in weather_manager::get_temperature(tripoint const&) /home/user/Cataclysm-DDA/src/weather.cpp:994:21
    #4 0x4a94e72 in item::process_temperature_rot(float, tripoint const&, Character*, temperature_flag, float) /home/user/Cataclysm-DDA/src/item.cpp:9851:30
    #5 0x4aa5ec7 in item::process_internal(Character*, tripoint const&, float, temperature_flag, float) /home/user/Cataclysm-DDA/src/item.cpp:10771:13
    #6 0x4aa42fe in item::process(Character*, tripoint const&, float, temperature_flag, float) /home/user/Cataclysm-DDA/src/item.cpp:10663:12
    #7 0x529a817 in map::add_item(tripoint const&, item) /home/user/Cataclysm-DDA/src/map.cpp:4347:18
    #8 0x529a19d in map::add_item_or_charges(tripoint const&, item, bool)::$_52::operator()(tripoint const&) const /home/user/Cataclysm-DDA/src/map.cpp:4262:16
    #9 0x524a0d1 in map::add_item_or_charges(tripoint const&, item, bool) /home/user/Cataclysm-DDA/src/map.cpp:4290:16
    #10 0x528e166 in map::spawn_items(tripoint const&, std::vector<item, std::allocator<item> > const&) /home/user/Cataclysm-DDA/src/map.cpp:4147:20
    #11 0x54f9310 in map::put_items_from_loc(string_id<Item_spawn_data> const&, tripoint const&, time_point const&) /home/user/Cataclysm-DDA/src/mapgen.cpp:5902:12
    #12 0x54f5285 in map::place_items(string_id<Item_spawn_data> const&, int, tripoint const&, tripoint const&, bool, time_point const&, int, int) /home/user/Cataclysm-DDA/src/mapgen.cpp:5880:24
    #13 0x539b6cf in map::place_items(string_id<Item_spawn_data> const&, int, point const&, point const&, bool, time_point const&, int, int) /home/user/Cataclysm-DDA/src/map.h:1327:20
    #14 0x565f349 in jmapgen_item_group::apply(mapgendata const&, jmapgen_int const&, jmapgen_int const&) const /home/user/Cataclysm-DDA/src/mapgen.cpp:1912:19
    #15 0x54b6895 in jmapgen_objects::apply(mapgendata const&) const /home/user/Cataclysm-DDA/src/mapgen.cpp:3833:18
    #16 0x54b5b87 in jmapgen_objects::apply(mapgendata const&, point const&) const /home/user/Cataclysm-DDA/src/mapgen.cpp:3842:9
    #17 0x54fda1e in update_mapgen_function_json::update_map(mapgendata const&, point const&, bool) const /home/user/Cataclysm-DDA/src/mapgen.cpp:6968:13
    #18 0x54ff602 in get_changed_ids_from_update(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/user/Cataclysm-DDA/src/mapgen.cpp:7046:37
    #19 0x65affd3 in recipe::finalize() /home/user/Cataclysm-DDA/src/recipe.cpp:365:47
    #20 0x65ddb4f in recipe_dictionary::finalize_internal(std::map<string_id<recipe>, recipe, std::less<string_id<recipe> >, std::allocator<std::pair<string_id<recipe> const, recipe> > >&) /home/user/Cataclysm-DDA/src/recipe_dictionary.cpp:422:21
    #21 0x65ded94 in recipe_dictionary::finalize() /home/user/Cataclysm-DDA/src/recipe_dictionary.cpp:497:5
    #22 0x48a2181 in void std::__invoke_impl<void, void (*&)()>(std::__invoke_other, void (*&)()) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:60:14
    #23 0x48a2118 in std::enable_if<__and_<std::is_void<void>, std::__is_invocable<void (*&)()> >::value, void>::type std::__invoke_r<void, void (*&)()>(void (*&)()) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/invoke.h:153:7
    #24 0x48a1fc1 in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:291:9
    #25 0x344db0b in std::function<void ()>::operator()() const /usr/lib/gcc/x86_64-redhat-linux/10/../../../../include/c++/10/bits/std_function.h:622:14
    #26 0x488a849 in DynamicDataLoader::finalize_loaded_data(loading_ui&) /home/user/Cataclysm-DDA/src/init.cpp:694:9
    #27 0x4472240 in game::load_world_modfiles(loading_ui&) /home/user/Cataclysm-DDA/src/game.cpp:2480:39
    #28 0x44711f6 in game::setup() /home/user/Cataclysm-DDA/src/game.cpp:600:5
    #29 0x52337ba in main_menu::new_character_tab() /home/user/Cataclysm-DDA/src/main_menu.cpp:856:28
    #30 0x5231100 in main_menu::opening_screen() /home/user/Cataclysm-DDA/src/main_menu.cpp:622:37
    #31 0x52189e9 in main /home/user/Cataclysm-DDA/src/main.cpp:704:23
    #32 0x73c9e699a1e1 in __libc_start_main (/lib64/libc.so.6+0x281e1)
    #33 0x2ff76fd in _start (/home/user/QubesIncoming/cdda-cpp/out/cataclysm-tiles+0x2ff76fd)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/submap.h:309:24 in 
```

**Comment by RenechCDDA** [comment]
The given json no longer crashes the game as of https://github.com/CleverRaven/Cataclysm-DDA/commit/c94dc0387513d5bba49eb7d74b2b51a7a4d8c4a0

**Comment by RenechCDDA** [comment]
I forgot to select the mod to load -_-
