### ISSUE TITLE
crash in vehicle::open_or_close

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#58606]
### Describe the bug

```
(gdb) bt
#0  0x00007f19b3200eac in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f19b31b4c72 in raise () from /lib64/libc.so.6
#2  0x00007f19b319f46b in abort () from /lib64/libc.so.6
#3  0x000055c47192dd30 in crash_terminate_handler () at src/crash.cpp:161
#4  0x00007f19b3511528 in __cxxabiv1::__terminate (handler=<optimized out>) at /var/tmp/portage/sys-devel/gcc-11.3.0/work/gcc-11.3.0/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007f19b3511593 in std::terminate () at /var/tmp/portage/sys-devel/gcc-11.3.0/work/gcc-11.3.0/libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007f19b35117d4 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7f19b366b188 <typeinfo for std::out_of_range>, dest=0x7f19b3526cc0 <std::out_of_range::~out_of_range()>)
    at /var/tmp/portage/sys-devel/gcc-11.3.0/work/gcc-11.3.0/libstdc++-v3/libsupc++/eh_throw.cc:95
#7  0x00007f19b35084f3 in std::__throw_out_of_range_fmt (__fmt=__fmt@entry=0x55c4735a13e0 "vector::_M_range_check: __n (which is %zu) >= this->size() (which is %zu)")
    at /var/tmp/portage/sys-devel/gcc-11.3.0/work/gcc-11.3.0/libstdc++-v3/src/c++11/functexcept.cc:100
#8  0x000055c4734e2ac4 in std::vector<vehicle_part, std::allocator<vehicle_part> >::_M_range_check (this=<optimized out>, this=<optimized out>, __n=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/bits/stl_vector.h:1073
#9  std::vector<vehicle_part, std::allocator<vehicle_part> >::at (__n=<optimized out>, this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/bits/stl_vector.h:1094
#10 operator() (opening=true, parti=<optimized out>, __closure=<synthetic pointer>) at src/vehicle_use.cpp:1689
#11 vehicle::open_or_close (this=<optimized out>, part_index=<optimized out>, opening=true) at src/vehicle_use.cpp:1693
#12 0x000055c4734fbd58 in vehicle::open (this=0x55c4deddcb70, part_index=<optimized out>) at src/vehicle_use.cpp:1602
#13 0x000055c4734fc176 in vehicle::open_all_at (this=0x55c4deddcb70, p=p@entry=58) at src/vehicle_use.cpp:1671
#14 0x000055c4729e74bf in map::open_door (this=this@entry=0x55c474d5db50, u=..., p=..., inside=<optimized out>, check_only=check_only@entry=false) at /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/include/g++-v11/bits/refwrap.h:337
#15 0x000055c472cf2c96 in monster::move (this=0x55c4df36e480) at src/monmove.cpp:1064
#16 0x000055c4722e840d in (anonymous namespace)::monmove () at src/do_turn.cpp:457
#17 0x000055c4722ee3f4 in do_turn () at src/do_turn.cpp:783
#18 0x000055c471b7ff0d in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:769
```

### Steps to reproduce

Cannot repro, likely mapgen-related.

### Expected behavior

.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-9239-g765f44250a-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

**Comment by TealcOneill** [comment]
There's no info on what was happening that caused this bug nor any steps to reproduce. I don't see how anyone could even find this issue if they have a similar crash with how little info is here. @GuardianDll I'd recommend closing this.

**Comment by GuardianDll** [comment]
Agreed
