### ISSUE TITLE
Travelling far distances causes a memory leak

### ISSUE THREAD

**Issue by Blueflowerss** [CleverRaven/Cataclysm-DDA#63018]
### Describe the bug

After (auto-)travelling on the overmap through many tiles the game experiences a memory leak issue.

### Steps to reproduce

1. Load up save.
2. Start travelling anywhere, seemingly doesn't matter if the terrain was saved beforehand.
3. See the game consumes way too much memory

### Expected behavior

I expect to be able to travel long distances without the game memory leaking.

### Screenshots

![image](https://user-images.githubusercontent.com/77662682/211053447-a76f7dc2-2ac7-432a-b2d5-f67c59e1d246.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20; Release: 20; Codename: ulyana; 
- Game Version: 28d1538 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Tamable Wildlife [Tamable_Wildlife],
    SpeedyDex [speedydex],
    Xedra Evolved [xedra_evolved],
    No Hope [no_hope],
    Blaze Industries [blazeindustries],
    Bionic Slots [cbm_slots],
    Bee content [bee_content],
    Slime Ranching [slime_ranch]
]

### Additional context

I suspect it's related to the game not unloading the areas I already travelled through.
And it seems to be system specific, as no amount of updating the game or using different installations fixed it.

**Comment by andrei8l** [comment]
> I suspect it's related to the game not unloading the areas I already travelled through.

Probably that. This very old comment here

https://github.com/CleverRaven/Cataclysm-DDA/blob/28d15385bb7756645aa286610a9e6b615ca4b446/src/mapbuffer.cpp#L168-L171

indicates that map buffer should be trimmed every (auto)save but the code below does not do that.

**Comment by andrei8l** [comment]
My comment above was wrong. Map buffer gets trimmed every (auto)save. 

I've also tested by walking around for a couple of overmaps without saving and memory usage dropped back to start value after saving. ASan also did not find any leaks:

<details>
<summary>LeakSanitizer report</summary>

```gcc
==190832==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5323 byte(s) in 255 object(s) allocated from:
    #0 0x55aaddfbfa52 in strdup (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa57ea52) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77c4679a8  (<unknown module>)

Direct leak of 1608 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77c4a0d1f  (<unknown module>)

Direct leak of 768 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffaafa in __interceptor_realloc.part.0 crtstuff.c
    #1 0x7fc78552196b  (/usr/lib/libSDL2-2.0.so.0+0x12196b) (BuildId: fe6102ccfc379dfd750e342fd5f4e7faba75747b)

Direct leak of 264 byte(s) in 3 object(s) allocated from:
    #0 0x55aaddffba69 in malloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5baa69) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc78207477b in pa_xmalloc (/usr/lib/libpulse.so.0+0x3777b) (BuildId: efd412c215ecbba53012aa57c2ec2dfcb7bac2a0)

Direct leak of 216 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77a5fb27b  (<unknown module>)

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffaafa in __interceptor_realloc.part.0 crtstuff.c
    #1 0x7fc77a2c5d1c  (<unknown module>)

Direct leak of 29 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffba69 in malloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5baa69) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc785520e07  (/usr/lib/libSDL2-2.0.so.0+0x120e07) (BuildId: fe6102ccfc379dfd750e342fd5f4e7faba75747b)

Direct leak of 14 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddfbfa52 in strdup (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa57ea52) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77ac66e6d  (<unknown module>)

Indirect leak of 1784 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77c378213  (<unknown module>)
    #2 0x7fc77af26402  (<unknown module>)

Indirect leak of 232 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffb257 in posix_memalign (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5ba257) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77aef2f92  (<unknown module>)

Indirect leak of 208 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77af25470  (<unknown module>)

Indirect leak of 200 byte(s) in 5 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc7855c0d7f  (/usr/lib/libSDL2-2.0.so.0+0x1c0d7f) (BuildId: fe6102ccfc379dfd750e342fd5f4e7faba75747b)

Indirect leak of 160 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77af23f60  (<unknown module>)

Indirect leak of 144 byte(s) in 2 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77af28a61  (<unknown module>)

Indirect leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77c3f97df  (<unknown module>)

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77c376a2f  (<unknown module>)
    #2 0x7fc77af2405c  (<unknown module>)

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77c376a2f  (<unknown module>)
    #2 0x7fc77af2643e  (<unknown module>)

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc782f3b0f0  (<unknown module>)

Indirect leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc782f3d5aa  (<unknown module>)

Indirect leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77aef20e7  (<unknown module>)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77af250dd  (<unknown module>)

Indirect leak of 60 byte(s) in 5 object(s) allocated from:
    #0 0x55aaddffba69 in malloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5baa69) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc7855c0db6  (/usr/lib/libSDL2-2.0.so.0+0x1c0db6) (BuildId: fe6102ccfc379dfd750e342fd5f4e7faba75747b)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77af263b0  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc7855753da  (/usr/lib/libSDL2-2.0.so.0+0x1753da) (BuildId: fe6102ccfc379dfd750e342fd5f4e7faba75747b)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77c37b3d6  (<unknown module>)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc77c4a061b  (<unknown module>)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x55aaddffbdd1 in calloc (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0xa5badd1) (BuildId: 330ca0162a53574d804133bd311e9feecfcc8039)
    #1 0x7fc78557527d  (/usr/lib/libSDL2-2.0.so.0+0x17527d) (BuildId: fe6102ccfc379dfd750e342fd5f4e7faba75747b)

Indirect leak of 24 byte(s) in 3 object(s) allocated from:
    #0 0x55aaddffaafa in __interceptor_realloc.part.0 crtstuff.c
    #1 0x7fc77af291f9  (<unknown module>)

SUMMARY: AddressSanitizer: 11978 byte(s) leaked in 295 allocation(s).
```

All of those are external (from SDL, or GL driver, or other dependency) and not real leaks.
</details>

**Comment by ZhilkinSerg** [comment]
That is not a memory leak - we just do not unload some data unless saving is done (and that actually need to be fixed).

**Comment by Blueflowerss** [comment]
Just tested some stuff, this issue only persists on my laptop, tested on both linux mint and windows 7.
This issue doesn't happen on my PC.
And to clarify, when the game saves on my laptop it doesn't free any memory, while it does on my PC.

**Comment by ZhilkinSerg** [comment]
Use identical game version for testing on different environments.

**Comment by Blueflowerss** [comment]
I believe I managed to workaround the issue by installing another OS, I'll just describe everything I did in case it helps:
-Switched of off legacy mode in bios boot up
-Installed windows 10
-Installed cataclysm and loaded up a save
I noticed that now memory is being freed while saving and exiting to the menu.
This seemingly only happens on Linux Mint 20 and windows 7.
