### ISSUE TITLE
Hard crash on save, quicksave

### ISSUE THREAD

**Issue by bjnation** [CleverRaven/Cataclysm-DDA#66162]
### Describe the bug

Game loads, then throws out error

 DEBUG    : contents index greater than contents size

 FUNCTION : deserialize
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item_location.cpp
 LINE     : 829
 VERSION  : f424b9c

Upon saving, game crashes immediately
Couldn't even use the "generate minimized save archive" function

### Attach save file

[Thorne.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/11728963/Thorne.zip)

### Steps to reproduce

1: Load game
2: Ignore errors
3: Attempt to save or generate minimized save archive

### Expected behavior

Be able to save

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: f424b9c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11728977/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/11728979/crash.log)

**Comment by RenechCDDA** [comment]
It certainly does crash, although I can't tell you immediately why.

As a fun possibly different bug, this creates a new copy of the save(?!) to load after each crash. 
![image](https://github.com/CleverRaven/Cataclysm-DDA/assets/84619419/a721d4ac-8111-4bb8-a119-a891390a42a2)

**Comment by Qrox** [comment]
@RenechCDDA could you provide your crash log for comparison? The OP's crash log seems to be from a different version and seems to be from loading rather than saving, so it's probably not related to this bug.

**Comment by andrei8l** [comment]
<details>
<summary>ASan log</summary>

```gdb
==368506==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f35b2383950 at pc 0x564af2e2d221 bp 0x7fffa95847d0 sp 0x7fffa95847c8
READ of size 8 at 0x7f35b2383950 thread T0
    #0 0x564af2e2d220 in std::__1::shared_ptr<item>::shared_ptr[abi:v15007]<safe_reference_anchor::empty>(std::__1::shared_ptr<safe_reference_anchor::empty> const&, item*) /usr/bin/../include/c++/v1/__memory/shared_ptr.h:585:24
    #1 0x564af2dff3e7 in safe_reference<item> safe_reference_anchor::reference_to<item>(item*) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/safe_reference.h:68:39
    #2 0x564af2c9af6d in item::get_safe_reference() /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/item.cpp:397:19
    #3 0x564af31411aa in item_location::impl::ensure_unpacked() const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/item_location.cpp:117:31
    #4 0x564af313f8a9 in item_location::impl::target() const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/item_location.cpp:104:13
    #5 0x564af3143cb0 in item_location::impl::item_on_map::serialize(JsonOut&) const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/item_location.cpp:205:48
    #6 0x564af0d780fd in decltype(fp.serialize(*this), (void)()) JsonOut::write<item_location>(item_location const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/json.h:786:15
    #7 0x564af0d780fd in void JsonOut::write_as_array<std::__1::vector<item_location, std::__1::allocator<item_location>>>(std::__1::vector<item_location, std::__1::allocator<item_location>> const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/json.h:856:17
    #8 0x564af5342a06 in player_activity::serialize(JsonOut&) const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/savegame_json.cpp:343:14
    #9 0x564af53e58e2 in decltype(fp.serialize(*this), (void)()) JsonOut::write<player_activity>(player_activity const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/json.h:786:15
    #10 0x564af53e58e2 in void JsonOut::write_as_array<std::__1::list<player_activity, std::__1::allocator<player_activity>>>(std::__1::list<player_activity, std::__1::allocator<player_activity>> const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/json.h:856:17
    #11 0x564af5365d4c in Character::store(JsonOut&) const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/savegame_json.cpp:1337:10
    #12 0x564af536b0bb in avatar::store(JsonOut&) const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/savegame_json.cpp:1518:16
    #13 0x564af536af50 in avatar::serialize(JsonOut&) const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/savegame_json.cpp:1511:5
    #14 0x564af52de653 in game::serialize(std::__1::basic_ostream<char, std::__1::char_traits<char>>&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/savegame.cpp:128:10
    #15 0x564af1566d5f in std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char>>&)>::operator()(std::__1::basic_ostream<char, std::__1::char_traits<char>>&) const /usr/bin/../include/c++/v1/__functional/function.h:1197:12
    #16 0x564af1566d5f in write_to_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char>>&)> const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/cata_utility.cpp:287:5
    #17 0x564af1566fb1 in write_to_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::function<void (std::__1::basic_ostream<char, std::__1::char_traits<char>>&)> const&, char const*) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/cata_utility.cpp:295:9
    #18 0x564af2639034 in game::save_player_data() /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/game.cpp:3279:29
    #19 0x564af2639ff6 in game::save() /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/game.cpp:3359:14
    #20 0x564af2923d80 in game::do_regular_action(action_id&, avatar&, std::__1::optional<tripoint> const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/handle_action.cpp:2532:21
    #21 0x564af294e3b2 in game::handle_action() /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/handle_action.cpp:2989:14
    #22 0x564af219bf07 in do_turn() /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/do_turn.cpp:538:24
    #23 0x564af0ae0554 in main /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/main.cpp:829:17
    #24 0x7f35b463d84f  (/usr/lib/libc.so.6+0x2384f) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)
    #25 0x7f35b463d909 in __libc_start_main (/usr/lib/libc.so.6+0x23909) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)
    #26 0x564af09dc6a4 in _start (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0x9b416a4) (BuildId: f6257a9e3921ec32ce97cb55ad34607f055c9b5e)

Address 0x7f35b2383950 is located in stack of thread T0 at offset 336 in frame
    #0 0x564af5d3ed2f in map_cursor::visit_items(std::__1::function<VisitResponse (item*, item*)> const&) const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/visitable.cpp:472

  This frame has 7 object(s):
    [32, 44) 'p' (line 474)
    [64, 96) 'it_id' (line 478)
    [128, 132) 'ref.tmp20' (line 478)
    [144, 704) 'it' (line 480) <== Memory access at offset 336 is inside this variable
    [832, 872) 'ref.tmp79' (line 493)
    [912, 936) '__begin1' (line 493)
    [976, 1000) '__end1' (line 493)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-return /usr/bin/../include/c++/v1/__memory/shared_ptr.h:585:24 in std::__1::shared_ptr<item>::shared_ptr[abi:v15007]<safe_reference_anchor::empty>(std::__1::shared_ptr<safe_reference_anchor::empty> const&, item*)
Shadow bytes around the buggy address:
  0x0fe7364686d0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0fe7364686e0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0fe7364686f0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0fe736468700: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0fe736468710: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x0fe736468720: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5[f5]f5 f5 f5 f5 f5
  0x0fe736468730: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0fe736468740: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0fe736468750: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0fe736468760: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x0fe736468770: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==368506==ABORTING
```

</details>

Probably related to the `contents index greater than content size` deserialization error you get on load.

**Comment by RenechCDDA** [comment]
> @RenechCDDA could you provide your crash log for comparison? The OP's crash log seems to be from a different version and seems to be from loading rather than saving, so it's probably not related to this bug.

Oh yeah I was wondering what was up with that. In my case, it's direct CTD (no crash log).

**Comment by SurFlurer** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/item_location.cpp#L781

Invalid item_location are often the culprit in many of our crashes.
