### ISSUE TITLE
Segmentation fault on trying to build saltwater pipe at camp

### ISSUE THREAD

**Issue by FIM43-Redeye** [CleverRaven/Cataclysm-DDA#67560]
### Describe the bug

When trying to build saltwater pipes from the fabrication workshop version 2, a segmentation fault ensues.

### Attach save file

[Innawood_segfault-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12306991/Innawood_segfault-trimmed.tar.gz)

### Steps to reproduce

1. Find/make an NPC.
2. Boost their skills and set proficiencies to all.
3. Make a camp.
4. Expand a fabrication workshop (variant 2) near a swamp.
5. Try to build the salt water pipe.
6. Segfault.

### Expected behavior

Not a segfault.

### Versions and configuration

OS: Windows 10
Game Version: 80b807a (64-bit)
Graphics Version: Tiles
Ingame language: English
Mods loaded: dda, innawood

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12306994/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12306996/debug.log)

**Comment by andrei8l** [comment]
/confirmed another unsafe reference use

<details>
<summary>ASan log</summary>

```gdb
==1410270==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffff533f5d8 at pc 0x55555f6d2002 bp 0x7fffffffd000 sp 0x7fffffffcff8
READ of size 8 at 0x7ffff533f5d8 thread T0
    #0 0x55555f6d2001 in std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant>>>::size[abi:v15007]() const /usr/bin/../include/c++/v1/__hash_table:935:53
    #1 0x5555626e7ea9 in std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, cata_variant>>>::size[abi:v15007]() const /usr/bin/../include/c++/v1/unordered_map:1187:56
    #2 0x5555626e7ea9 in unsigned long cata::range_hash::operator()<std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, cata_variant>>>>(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const, cata_variant>>> const&) const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/hash_utils.h:81:34
    #3 0x5555626e39cc in std::__1::hash<mapgen_arguments>::operator()(mapgen_arguments const&) const /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/mapgendata.cpp:34:12
    #4 0x55555fb2e49a in std::__1::__unordered_map_hasher<mapgen_arguments, std::__1::__hash_value_type<mapgen_arguments, build_reqs>, std::__1::hash<mapgen_arguments>, std::__1::equal_to<mapgen_arguments>, true>::operator()[abi:v15007](mapgen_arguments const&) const /usr/bin/../include/c++/v1/unordered_map:580:17
    #5 0x55555fb2e49a in std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<mapgen_arguments, build_reqs>, void*>*> std::__1::__hash_table<std::__1::__hash_value_type<mapgen_arguments, build_reqs>, std::__1::__unordered_map_hasher<mapgen_arguments, std::__1::__hash_value_type<mapgen_arguments, build_reqs>, std::__1::hash<mapgen_arguments>, std::__1::equal_to<mapgen_arguments>, true>, std::__1::__unordered_map_equal<mapgen_arguments, std::__1::__hash_value_type<mapgen_arguments, build_reqs>, std::__1::equal_to<mapgen_arguments>, std::__1::hash<mapgen_arguments>, true>, std::__1::allocator<std::__1::__hash_value_type<mapgen_arguments, build_reqs>>>::find<mapgen_arguments>(mapgen_arguments const&) const /usr/bin/../include/c++/v1/__hash_table:2333:21
    #6 0x55555fb14462 in std::__1::unordered_map<mapgen_arguments, build_reqs, std::__1::hash<mapgen_arguments>, std::__1::equal_to<mapgen_arguments>, std::__1::allocator<std::__1::pair<mapgen_arguments const, build_reqs>>>::find[abi:v15007](mapgen_arguments const&) const /usr/bin/../include/c++/v1/unordered_map:1445:69
    #7 0x55555fb14462 in basecamp_action_components::choose_components() /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/basecamp.cpp:856:32
    #8 0x555560e1bd31 in basecamp::common_salt_water_pipe_construction(mission_id const&, expansion_salt_water_pipe*, int) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/faction_camp.cpp:2802:21
    #9 0x555560e1028b in basecamp::start_salt_water_pipe(mission_id const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/faction_camp.cpp:2989:9
    #10 0x555560de8e1a in basecamp::start_upgrade(mission_id const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/faction_camp.cpp:1965:9
    #11 0x555560dc7722 in basecamp::handle_mission(ui_mission_id const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/faction_camp.cpp:1659:17
    #12 0x5555613a9639 in iexamine::bulletin_board(Character&, tripoint const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/iexamine.cpp:1963:24
    #13 0x55556101a013 in game::examine(tripoint const&, bool) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/game.cpp
    #14 0x555561017ddc in game::examine(bool) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/game.cpp:5995:5
    #15 0x5555612c2627 in game::do_regular_action(action_id&, avatar&, std::__1::optional<tripoint> const&) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/handle_action.cpp:2247:17
    #16 0x5555612f09b7 in game::handle_action() /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/handle_action.cpp:3043:14
    #17 0x555560b3f417 in do_turn() /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/do_turn.cpp:531:24
    #18 0x55555f46d504 in main /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/main.cpp:782:17
    #19 0x7ffff7627ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8f3291ff820508330af3a5ccb75de43d474ef19a)
    #20 0x7ffff7627d89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 8f3291ff820508330af3a5ccb75de43d474ef19a)
    #21 0x55555f369894 in _start (/usr/src/cataclysm-dda-git/src/build_asan/cataclysm-tiles+0x9e15894) (BuildId: f64231dace6e51d1d238376f84e45c8f7cd6f41d)

Address 0x7ffff533f5d8 is located in stack of thread T0 at offset 472 in frame
    #0 0x555560e1b9df in basecamp::common_salt_water_pipe_construction(mission_id const&, expansion_salt_water_pipe*, int) /usr/src/cataclysm-dda-git/src/build_asan/../cataclysm-dda-git/src/faction_camp.cpp:2790

  This frame has 15 object(s):
    [32, 40) 'ref.tmp.i2.i'
    [64, 72) 'ref.tmp.i.i'
    [96, 104) 'ref.tmp.i240'
    [128, 136) 'ref.tmp.i216'
    [160, 168) 'ref.tmp.i199'
    [192, 216) 'ref.tmp.i'
    [256, 288) 'ref.tmp' (line 2791)
    [320, 324) 'remaining_segments' (line 2793)
    [336, 416) 'components' (line 2801)
    [448, 488) 'ref.tmp31' (line 2801) <== Memory access at offset 472 is inside this variable
    [528, 552) 'comp' (line 2806)
    [592, 616) 'ref.tmp51' (line 2809)
    [656, 680) 'ref.tmp56' (line 2809)
    [720, 744) 'ref.tmp85' (line 2813)
    [784, 808) 'ref.tmp90' (line 2813)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope /usr/bin/../include/c++/v1/__hash_table:935:53 in std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant>, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant>, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, cata_variant>>>::size[abi:v15007]() const
Shadow bytes around the buggy address:
  0x10007ea5fe60: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007ea5fe70: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007ea5fe80: f1 f1 f1 f1 f8 f2 f2 f2 f8 f2 f2 f2 f8 f2 f2 f2
  0x10007ea5fe90: f8 f2 f2 f2 f8 f2 f2 f2 f8 f8 f8 f2 f2 f2 f2 f2
  0x10007ea5fea0: f8 f8 f8 f8 f2 f2 f2 f2 04 f2 00 00 00 00 00 00
=>0x10007ea5feb0: 00 00 00 00 f2 f2 f2 f2 f8 f8 f8[f8]f8 f2 f2 f2
  0x10007ea5fec0: f2 f2 f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f8 f2 f2 f2
  0x10007ea5fed0: f2 f2 f8 f8 f8 f2 f2 f2 f2 f2 f8 f8 f8 f2 f2 f2
  0x10007ea5fee0: f2 f2 f8 f8 f8 f3 f3 f3 f3 f3 f3 f3 00 00 00 00
  0x10007ea5fef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007ea5ff00: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1410270==ABORTING
```

</details>

<details>
<summary>Potential patch</summary>

```diff
diff --git a/src/faction_camp.cpp b/src/faction_camp.cpp
index 85147d99e4..da6166af29 100644
--- a/src/faction_camp.cpp
+++ b/src/faction_camp.cpp
@@ -2798,7 +2798,8 @@ bool basecamp::common_salt_water_pipe_construction(
         }
     }
 
-    basecamp_action_components components( making, {}, 1, *this );
+    mapgen_arguments blorg;
+    basecamp_action_components components( making, blorg, 1, *this );
     if( !components.choose_components() ) {
         return false;
     }
```

</details>
A couple of other places need the same treatment. Some minor refactoring might be nicer.

**Comment by NetSysFire** [comment]
Duplicate of #66318.
