### ISSUE TITLE
Condom too heavy error

### ISSUE THREAD

**Issue by Nightquaker** [CleverRaven/Cataclysm-DDA#67659]
### Describe the bug

I was surviving, suddenly I get an error that a condom is too heavy, seemingly out of nowhere. Everything else is fine, but condom is too heavy. Magnum condom?

### Attach save file

[East Hills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12332036/East.Hills-trimmed.tar.gz)

### Steps to reproduce

1. Play.
2. Get overloaded (I think). Maybe get tired to the point where you can't lift a finger, so to speak (or lift light objects in practice).
3. Condom is too heavy. Magnum condom.

### Expected behavior

Expected to not get that error. I mean, if the condom IS too heavy, then fair enough, but I shouldn't be getting an error about it. It should be just marked in-game as too heavy, like any other item.

### Screenshots

![ItemTooHeavy](https://github.com/CleverRaven/Cataclysm-DDA/assets/35462952/e1747566-8df8-4034-9024-6e0cf72c2907)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2134 (22H2) This is Win11 actually.
- Game Version: c1de457 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [] English.
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Jackledead Armory [jackledead_armory],
    Magiclysm [magiclysm]
]

### Additional context

I can continue the game after getting the error, as you can see on the screenshot, but the error can appear again in the same save file.

**Comment by sethsimon** [comment]
Confirmed. I was walking through the forest, and right after I took a step, the message came up. The last commit was 6fe185a915dd89ff1df22a057e3b80e29c6144b0 on my vjunk branch, and the commit before that was on master, 5e1841aac1c030fce48640ce8da081a3c4cc9c31. The debug message was identical except for the version and line number of 706.

```
(gdb) bt
#0  0x00007f532a41f1d1 in __GI___libc_read (fd=0, buf=0x7ffc08790e5f, nbytes=1) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x00007f532a8764fe in ?? () from /lib/x86_64-linux-gnu/libncursesw.so.6
#2  0x00007f532a877007 in wgetch () from /lib/x86_64-linux-gnu/libncursesw.so.6
#3  0x000055d593349180 in input_manager::get_input_event (this=0x55d5943dc080 <inp_mngr>) at src/ncurses_def.cpp:376
#4  0x000055d59269a8d4 in debug_error_prompt (filename=<optimized out>, filename@entry=0x55d593d03107 "src/item_contents.cpp", line=<optimized out>, line@entry=0x55d593d33601 "706", 
    funcname=<optimized out>, 
    funcname@entry=0x55d593d03de0 <item_contents::combine(item_contents const&, bool, bool, bool)::__PRETTY_FUNCTION__> "void item_contents::combine(const item_contents&, bool, bool, bool)", 
    text=<optimized out>, force=force@entry=false) at src/debug.cpp:377
#5  0x000055d59269bc70 in realDebugmsg (filename=filename@entry=0x55d593d03107 "src/item_contents.cpp", line=line@entry=0x55d593d33601 "706", 
    funcname=funcname@entry=0x55d593d03de0 <item_contents::combine(item_contents const&, bool, bool, bool)::__PRETTY_FUNCTION__> "void item_contents::combine(const item_contents&, bool, bool, bool)", text="error: item condom cannot fit into pocket while loading: item is too heavy") at /usr/include/c++/8/bits/basic_string.h:2290
#6  0x000055d592c0660c in realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&> (mes=0x55d593d03660 "error: item %s cannot fit into pocket while loading: %s", 
    funcname=0x55d593d03de0 <item_contents::combine(item_contents const&, bool, bool, bool)::__PRETTY_FUNCTION__> "void item_contents::combine(const item_contents&, bool, bool, bool)", 
    line=0x55d593d33601 "706", filename=0x55d593d03107 "src/item_contents.cpp") at /usr/include/c++/8/ext/new_allocator.h:86
#7  item_contents::combine (this=this@entry=0x7ffc08791b88, read_input=..., convert=convert@entry=false, into_bottom=into_bottom@entry=true, restack_charges=restack_charges@entry=false)
    at src/item_contents.cpp:705
#8  0x000055d59381f95d in item::deserialize (this=this@entry=0x7ffc08791b10, data=...) at src/savegame_json.cpp:3225
#9  0x000055d59212eeaa in JsonValue::read<item> (this=<optimized out>, v=..., throw_on_error=<optimized out>) at src/flexbuffer_json-inl.h:315
#10 0x000055d59244b2bd in JsonValue::read<std::__cxx11::list<item, std::allocator<item> >, (void*)0> (this=this@entry=0x7ffc08791f40, Python Exception <class 'ValueError'> Cannot find type class std::__cxx11::list<item, std::allocator<item> >::_Node: 
v=std::__cxx11::list, throw_on_error=throw_on_error@entry=true)
    at src/cata_bitset.h:305
#11 0x000055d59244b7f4 in JsonObject::read<std::__cxx11::list<item, std::allocator<item> > > (this=0x7ffc08792000, name=..., Python Exception <class 'ValueError'> Cannot find type class std::__cxx11::list<item, std::allocator<item> >::_Node: 
t=std::__cxx11::list, throw_on_error=<optimized out>)
    at /usr/include/c++/8/optional:1193
#12 0x000055d59381ff5d in item_pocket::deserialize (this=this@entry=0x7ffc08792140, data=...) at /usr/include/c++/8/bits/char_traits.h:316
#13 0x000055d59384dc2e in JsonValue::read<item_pocket> (this=this@entry=0x7ffc087920b0, v=..., throw_on_error=throw_on_error@entry=true) at src/flexbuffer_json-inl.h:315
#14 0x000055d59384df11 in JsonValue::read<std::__cxx11::list<item_pocket, std::allocator<item_pocket> >, (void*)0> (this=this@entry=0x7ffc08792280, Python Exception <class 'ValueError'> Cannot find type class std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_Node: 
v=empty std::__cxx11::list, 
    throw_on_error=throw_on_error@entry=true) at /usr/include/c++/8/bits/stl_tree.h:211
#15 0x000055d59384e472 in JsonObject::read<std::__cxx11::list<item_pocket, std::allocator<item_pocket> > > (this=this@entry=0x7ffc08792310, name=..., Python Exception <class 'ValueError'> Cannot find type class std::__cxx11::list<item_pocket, std::allocator<item_pocket> >::_Node: 
t=empty std::__cxx11::list, 
    throw_on_error=throw_on_error@entry=true) at /usr/include/c++/8/optional:1193
#16 0x000055d59381f0c3 in item_contents::deserialize (this=this@entry=0x7ffc08792490, data=...) at /usr/include/c++/8/bits/char_traits.h:316
#17 0x000055d59384db22 in JsonValue::read<item_contents> (this=this@entry=0x7ffc087923b0, v=..., throw_on_error=throw_on_error@entry=true) at src/flexbuffer_json-inl.h:315
#18 0x000055d59384dbe2 in JsonObject::read<item_contents> (this=this@entry=0x7ffc08792650, name=..., t=..., throw_on_error=throw_on_error@entry=true) at /usr/include/c++/8/optional:1193
#19 0x000055d59381f921 in item::deserialize (this=this@entry=0x7ffc08792890, data=...) at /usr/include/c++/8/string_view:99
#20 0x000055d59212eeaa in JsonValue::read<item> (this=this@entry=0x7ffc08792740, v=..., throw_on_error=throw_on_error@entry=false) at src/flexbuffer_json-inl.h:315
#21 0x000055d5937ff3ab in JsonValue::read<item, (void*)0> (this=0x7ffc08792e10, v=..., throw_on_error=false) at src/third-party/flatbuffers/flexbuffers.h:406
#22 0x000055d59382e155 in submap::load (this=0x55d5c4b81d20, jv=..., member_name="items", version=version@entry=33) at /usr/include/c++/8/array:185
#23 0x000055d592f30eb9 in mapbuffer::deserialize (this=this@entry=0x55d5944dc380 <MAPBUFFER>, ja=...) at /usr/include/c++/8/bits/unique_ptr.h:342
#24 0x000055d592f31125 in mapbuffer::<lambda(const JsonValue&)>::operator() (jsin=..., __closure=<optimized out>) at src/mapbuffer.cpp:279
#25 std::_Function_handler<void(const JsonValue&), mapbuffer::unserialize_submaps(const tripoint_abs_sm&)::<lambda(const JsonValue&)> >::_M_invoke(const std::_Any_data &, const JsonValue &) (
    __functor=..., __args#0=...) at /usr/include/c++/8/bits/std_function.h:297
#26 0x000055d592383fce in std::function<void (JsonValue const&)>::operator()(JsonValue const&) const (this=this@entry=0x7ffc08793d40, __args#0=...) at /usr/include/c++/8/bits/std_function.h:260
#27 0x000055d5923838f9 in read_from_file_json(cata_path const&, std::function<void (JsonValue const&)> const&) (path=..., reader=...) at src/cata_utility.cpp:559
#28 0x000055d592383ba1 in read_from_file_optional_json(cata_path const&, std::function<void (JsonValue const&)> const&) (path=..., reader=...) at /usr/include/c++/8/bits/fs_path.h:260
#29 0x000055d592f332dd in mapbuffer::unserialize_submaps (this=this@entry=0x55d5944dc380 <MAPBUFFER>, p=...) at src/mapbuffer.cpp:278
#30 0x000055d592f33b44 in mapbuffer::lookup_submap (this=0x55d5944dc380 <MAPBUFFER>, p=...) at src/mapbuffer.cpp:114
#31 0x000055d592eaf705 in map::loadn (this=this@entry=0x55d595e47a30, grid=..., update_vehicles=update_vehicles@entry=true) at src/map.cpp:7871
#32 0x000055d592ed702e in map::shift (this=0x55d595e47a30, sp=...) at src/map.cpp:7723
#33 0x000055d59292a7f6 in game::update_map (this=this@entry=0x55d5960ceec0, x=@0x7ffc087948f0: 71, y=@0x7ffc087948f4: 66, z_level_changed=z_level_changed@entry=false) at src/game.cpp:12335
#34 0x000055d59292bbd2 in game::update_map (this=this@entry=0x55d5960ceec0, p=..., z_level_changed=z_level_changed@entry=false) at src/game.cpp:12293
#35 0x000055d592959456 in game::place_player (this=this@entry=0x55d5960ceec0, dest_loc=..., quick=quick@entry=false) at src/game.cpp:10737
#36 0x000055d592972381 in game::walk_move (this=0x55d5960ceec0, dest_loc=..., via_ramp=via_ramp@entry=false, furniture_move=furniture_move@entry=false) at src/game.cpp:10513
#37 0x000055d592291ba2 in avatar_action::move (you=..., m=..., d=...) at /usr/include/c++/8/bits/unique_ptr.h:342
#38 0x000055d592a00370 in avatar_action::move (d=<synthetic pointer>..., m=..., you=...) at src/point.h:131
#39 game::do_regular_action (this=this@entry=0x55d5960ceec0, act=@0x7ffc0879610c: ACTION_MOVE_FORTH_LEFT, player_character=..., mouse_target=std::optional<struct tripoint> [no contained value])
    at src/handle_action.cpp:2120
#40 0x000055d592a05f98 in game::handle_action (this=0x55d5960ceec0) at src/handle_action.cpp:3043
#41 0x000055d59277d1a6 in do_turn () at /usr/include/c++/8/bits/unique_ptr.h:342
#42 0x000055d592e832c3 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:782
(gdb) 
```
