### ISSUE TITLE
Out of bounds access in ImGui when producing an achievement pop-up

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#73002]
### Describe the bug

```
(gdb) bt
#0  0x00007f4e2f8c503c in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f4e2f875296 in raise () from /lib64/libc.so.6
#2  0x00007f4e2f85d8b7 in abort () from /lib64/libc.so.6
#3  0x0000557cb7d292f9 in signal_handler (sig=<optimized out>) at src/crash.cpp:147
#4  signal_handler (sig=<optimized out>) at src/crash.cpp:108
#5  <signal handler called>
#6  0x00007f4e2f8c503c in __pthread_kill_implementation () from /lib64/libc.so.6
#7  0x00007f4e2f875296 in raise () from /lib64/libc.so.6
#8  0x00007f4e2f85d8b7 in abort () from /lib64/libc.so.6
#9  0x00007f4e2fad9bdf in std::__glibcxx_assert_fail (file=file@entry=0x557cb954c388 "/usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/array", line=line@entry=202, 
    function=function@entry=0x557cb9560d58 "constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = RGBTuple; long unsigned int _Nm = 16; reference = RGBTuple&; size_type = long unsigned int]", 
    condition=condition@entry=0x557cb94f1a42 "__n < this->size()") at /var/tmp/portage/sys-devel/gcc-13.2.1_p20240210/work/gcc-13-20240210/libstdc++-v3/src/c++11/assert_fail.cc:41
#10 0x0000557cb7a6be8f in std::array<RGBTuple, 16ul>::operator[] (this=0x557cb9d6fae0 <rgbPalette>, __n=237) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/array:200
#11 std::array<RGBTuple, 16ul>::operator[] (__n=237, this=0x557cb9d6fae0 <rgbPalette>) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/array:200
#12 cataimgui::window::draw_colored_text (this=this@entry=0x557cf28dd060, text="<color_c_dark_gray>Achievement completion popups can be</color>", color=..., wrap_width=<optimized out>, is_selected=is_selected@entry=0x0, 
    is_focused=is_focused@entry=0x0, is_hovered=is_hovered@entry=0x0) at src/cata_imgui.cpp:408
#13 0x0000557cb8e7e683 in query_popup_impl::draw_controls (this=0x557cf28dd060) at src/popup.cpp:56
#14 0x0000557cb7a6a19a in cataimgui::window::draw (this=0x557cf28dd060) at src/cata_imgui.cpp:579
#15 0x0000557cb7a6d881 in cataimgui::window::draw (this=<optimized out>) at src/cata_imgui.cpp:554
#16 cataimgui::window_impl::window_impl(cataimgui::window*)::{lambda(ui_adaptor&)#1}::operator()(ui_adaptor&) const (__closure=<optimized out>) at src/cata_imgui.cpp:450
#17 std::__invoke_impl<void, cataimgui::window_impl::window_impl(cataimgui::window*)::{lambda(ui_adaptor&)#1}&, ui_adaptor&>(std::__invoke_other, cataimgui::window_impl::window_impl(cataimgui::window*)::{lambda(ui_adaptor&)#1}&, ui_adaptor&) (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:61
#18 std::__invoke_r<void, cataimgui::window_impl::window_impl(cataimgui::window*)::{lambda(ui_adaptor&)#1}&, ui_adaptor&>(cataimgui::window_impl::window_impl(cataimgui::window*)::{lambda(ui_adaptor&)#1}&, ui_adaptor&) (__fn=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:111
#19 std::_Function_handler<void (ui_adaptor&), cataimgui::window_impl::window_impl(cataimgui::window*)::{lambda(ui_adaptor&)#1}>::_M_invoke(std::_Any_data const&, ui_adaptor&) (__functor=..., __args#0=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_function.h:290
#20 0x0000557cb92dc698 in std::function<void (ui_adaptor&)>::operator()(ui_adaptor&) const (__args#0=..., this=0x557cf2f15628) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_function.h:591
#21 ui_adaptor::redraw_invalidated () at src/ui_manager.cpp:440
#22 0x0000557cb92dc9c1 in ui_adaptor::redraw () at src/ui_manager.cpp:345
#23 0x0000557cb8e7ff9d in query_popup::query_once (this=this@entry=0x7ffe28c5bcb0) at src/popup.cpp:285
#24 0x0000557cb8e817cf in query_popup::query (this=this@entry=0x7ffe28c5bcb0) at src/popup.cpp:397
#25 0x0000557cb8cfbf85 in popup (
    text="<color_c_light_green>Achievement completed!</color>\n\n<color_c_light_green>Student Driver</color>\n  <color_c_light_green>Easy on the brakes.</color>\n  <color_c_light_green>Completed Year 1, Spring, day"..., 
    flags=flags@entry=PF_NONE) at src/output.cpp:950
#26 0x0000557cb807a1f3 in achievement_attained (a=0x557cbbae5868, achievements_enabled=<optimized out>) at src/game.cpp:416
#27 0x0000557cb77611a9 in std::function<void (achievement const*, bool)>::operator()(achievement const*, bool) const (__args#1=<optimized out>, __args#0=0x557cbbae5868, this=0x557cbb150e50)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_function.h:591
#28 achievements_tracker::report_achievement (this=0x557cbb150e30, a=0x557cbbae5868, comp=achievement_completion::completed) at src/achievement.cpp:803
#29 0x0000557cb90f920e in watcher_set<stat_watcher>::send_to_all<stat_watcher, cata_variant const&, stats_tracker&, cata_variant const&, stats_tracker&> (mem_fn=&virtual table offset 16, this=<optimized out>) at src/stats_tracker.h:161
#30 stats_tracker::stat_value_changed (this=0x557cbb14f340, id=..., new_value=...) at src/stats_tracker.cpp:322
#31 0x0000557cb90f912e in watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&> (mem_fn=&virtual table offset 16, this=0x557ce9dde2a8)
    at src/stats_tracker.h:161
#32 stats_tracker::transformed_set_changed (this=0x557cbb14f340, id=..., new_element=...) at src/stats_tracker.cpp:304
#33 0x0000557cb7f2b85f in non-virtual thunk to event_transformation_impl::state::event_added(cata::event const&, stats_tracker&) () at src/event_statistics.cpp:469
#34 0x0000557cb90fb6ee in watcher_set<event_multiset_watcher>::send_to_all<event_multiset_watcher, cata::event const&, stats_tracker&, cata::event const&, stats_tracker&> (mem_fn=&virtual table offset 16, this=<optimized out>)
    at src/stats_tracker.h:161
#35 stats_tracker::notify (this=0x557cbb14f340, e=...) at src/stats_tracker.cpp:367
#36 0x0000557cb7ee7e00 in event_bus::send (this=<optimized out>, e=...) at src/event_bus.cpp:73
#37 0x0000557cb7af9de7 in event_bus::send<(event_type)67, character_id, string_id<Skill> const&, int&> (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/allocator.h:184
#38 Character::practice (this=0x557cbb5107f0, id=..., amount=25, amount@entry=1, cap=cap@entry=99, suppress_warning=suppress_warning@entry=false) at src/character.cpp:2731
#39 0x0000557cb940b071 in vehicle::act_on_map (this=0x557ce93e9bd0) at src/vehicle_move.cpp:1918
#40 0x0000557cb8617ebf in map::vehproceed (this=this@entry=0x557cbb15c730, vehicle_list=std::vector of length 1, capacity 1 = {...}) at src/map.cpp:733
#41 0x0000557cb8618227 in map::vehmove (this=0x557cbb15c730) at src/map.cpp:667
#42 0x0000557cb7e687c1 in do_turn () at src/do_turn.cpp:607
#43 0x0000557cb75aa19d in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:868
```
```
(gdb) up
#12 cataimgui::window::draw_colored_text (this=this@entry=0x557cf28dd060, text="<color_c_dark_gray>Achievement completion popups can be</color>", color=..., wrap_width=<optimized out>, is_selected=is_selected@entry=0x0, 
    is_focused=is_focused@entry=0x0, is_hovered=is_hovered@entry=0x0) at src/cata_imgui.cpp:408
408	            RGBTuple &rgbCol = rgbPalette[palette_index];
(gdb) p palette_index
$1 = 237
(gdb) p rgbPalette
$2 = {_M_elems = {{Blue = 0 '\000', Green = 0 '\000', Red = 0 '\000'}, {Blue = 0 '\000', Green = 0 '\000', Red = 255 '\377'}, {Blue = 0 '\000', Green = 110 'n', Red = 0 '\000'}, {Blue = 23 '\027', Green = 51 '3', Red = 92 '\\'}, {
      Blue = 200 '\310', Green = 0 '\000', Red = 0 '\000'}, {Blue = 98 'b', Green = 58 ':', Red = 139 '\213'}, {Blue = 180 '\264', Green = 150 '\226', Red = 0 '\000'}, {Blue = 150 '\226', Green = 150 '\226', Red = 150 '\226'}, {
      Blue = 99 'c', Green = 99 'c', Red = 99 'c'}, {Blue = 150 '\226', Green = 150 '\226', Red = 255 '\377'}, {Blue = 0 '\000', Green = 255 '\377', Red = 0 '\000'}, {Blue = 0 '\000', Green = 255 '\377', Red = 255 '\377'}, {
      Blue = 255 '\377', Green = 100 'd', Red = 100 'd'}, {Blue = 254 '\376', Green = 0 '\000', Red = 254 '\376'}, {Blue = 255 '\377', Green = 240 '\360', Red = 0 '\000'}, {Blue = 255 '\377', Green = 255 '\377', Red = 255 '\377'}}}
```

### Attach save file

See below.

### Steps to reproduce

Load the game, get in the car, move west by the road to reach the mansion.

### Expected behavior

No crashes.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: cdda-experimental-2024-04-12-2052 36578d798b-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by l29ah** [comment]
[2024.04.05.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14968108/2024.04.05.zip)

**Comment by BrettDong** [comment]
Duplicate of #72973?

**Comment by l29ah** [comment]
> Duplicate of #72973?

Oh damn, i don't remember what i already reported, thanks. At least this one has a better repro.
