### ISSUE TITLE
The tool tileset_coverage.py fails

### ISSUE THREAD

**Issue by mdtrooper** [CleverRaven/Cataclysm-DDA#74282]
### Describe the bug

The execution of tools/gfx_tools/tileset_coverage.py to get the csv.

### Attach save file

It is a tool of project, not the game.

### Steps to reproduce

1. `Cataclysm-DDA$ python3 tools/gfx_tools/tileset_coverage.py  all_game_ids.csv all_overlay_ids.csv tileset_ids.csv  tileset_coverage_output.csv`

### Expected behavior

No fails and it mades a csv file.

### Screenshots

```
$ python3 tools/gfx_tools/tileset_coverage.py  all_game_ids.csv all_overlay_ids.csv tileset_ids.csv  tileset_coverage_output.csv
/tmp/Cataclysm-DDA/tools/gfx_tools/tileset_coverage.py:94: FutureWarning: The warn_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  all_game_ids = pandas.read_csv(
/tmp/Cataclysm-DDA/tools/gfx_tools/tileset_coverage.py:98: FutureWarning: The warn_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  overlay_ids = pandas.read_csv(
/tmp/Cataclysm-DDA/tools/gfx_tools/tileset_coverage.py:104: FutureWarning: The warn_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  tileset_ids = pandas.read_csv(
Traceback (most recent call last):
  File "/tmp/Cataclysm-DDA/tools/gfx_tools/tileset_coverage.py", line 216, in <module>
    merge_datasets(
  File "/tmp/Cataclysm-DDA/tools/gfx_tools/tileset_coverage.py", line 168, in merge_datasets
    result = all_game_ids.merge(
  File "/home/panacea/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 10090, in merge
    return merge(
  File "/home/panacea/.local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 110, in merge
    op = _MergeOperation(
  File "/home/panacea/.local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 703, in __init__
    ) = self._get_merge_keys()
  File "/home/panacea/.local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1179, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/home/panacea/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'id'
```

### Versions and configuration

-OS: Linux Mint 21

**Comment by mdtrooper** [comment]
Well it is fixed in the  #74284 (merged) . Thanks :beers:  @Maleclypse to review my code.

Closed this issue.
