### ISSUE TITLE
NPC bandits have an aimbot

### ISSUE THREAD

**Issue by Antrocon** [CleverRaven/Cataclysm-DDA#75331]
### Describe the bug

NPC bandits seems to never (or almost never) miss a shot. They seem to use 100 turns/1sec to aim, both with handguns & rifles, and all shots i've observed did hit
2 bandits (5 marks, 6 rifles, 7 handguns), one with beretta m9, one with m1a rifle, shooting till mag empty, all hits from 12 tiles
PC with same skills, firing same guns from same distance using 100 turns for aim: beretta - 2 misses out 15, m1a 4 misses out 8

### Attach save file

[Gowan-trimmed.tar.gz](https://github.com/user-attachments/files/16432304/Gowan-trimmed.tar.gz)

### Steps to reproduce

1. make player with exoskeleton armor (or any heavy armor as not to die quickly)
2. teleport to regional dump with npc bandits (or spawn an npc with gun & make them angry, though probably need to edit skills/attitude so he wont run)
3. spawn same gun for your char & edit skills to match bandit
4. approach at ~12 tiles & wait for npc to shoot you
5. observe all shots hit you
6. shoot same gun using 100 turns for aim
7. observe some shots missing (more misses with rifles, as usually they need more time for precise aim, which apparently does not apply to npc)

### Expected behavior

npc follow same rules as pc

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: cdda-experimental-2024-07-30-0433 8062226 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks]
]

**Comment by x-qq** [comment]
Confirmed on cdda-linux-tiles-x64-2024-08-03-0533, the bandits are too accurate.

Also while confirming this, received a random segfault while being shot by a bandit, but it does not seem to be reliably reproucible.

```
CRASH LOG FILE: ./config/crash.log
VERSION: cdda-experimental-2024-08-03-0533 1c140ab
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

    0x559,62a,45e,8cf    src/debug.cpp:967    bt_full
    0x559,62a,45e,8cf    src/debug.cpp:1,232    debug_write_backtrace(std::ostream&)
    0x559,62a,435,ada    src/crash.cpp:89    log_crash
    0x559,62a,435,e27    src/crash.cpp:146    signal_handler
    0x7f0,205,058,57f    ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0    [unknown func]
    0x559,62a,bbc,988    src/npcmove.cpp:2,723    npc::wont_hit_friend(tripoint const&, item const&, bool) const
    0x559,62a,ba8,7e0    src/npc_attack.cpp:567    npc_attack_gun::evaluate_tripoint(npc const&, Creature const*, tripoint const&) const
    0x559,62a,ba8,ba1    src/npc_attack.cpp:512    npc_attack_gun::evaluate(npc const&, Creature const*) const
    0x559,62a,bb8,fd2    src/npcmove.cpp:1,989    operator()
    0x559,62a,bca,aa0    src/npcmove.cpp:2,014    operator()
    0x559,62b,06e,9c5    /usr/include/c++/9/bits/std_function.h:688    std::function<VisitResponse (item*, item*)>::operator()(item*, item*) const
    0x559,62b,06e,9c5    src/visitable.cpp:348    visit_internal
    0x559,62b,06f,18a    src/visitable.cpp:453    Character::visit_items(std::function<VisitResponse (item*, item*)> const&) const
    0x559,62a,bc2,332    src/npcmove.cpp:1,998    npc::evaluate_best_attack(Creature const*)
    0x559,62a,bc2,5ac    src/npcmove.cpp:1,972    npc::method_of_attack()
    0x559,62a,bd2,485    src/npcmove.cpp:1,382    npc::move()
    0x559,62a,4c3,aeb    src/do_turn.cpp:359    monmove
    0x559,62a,4c3,aeb    src/do_turn.cpp:657    do_turn()
    0x559,629,fad,a2c    src/main.cpp:873    main
    0x7f0,205,042,c89    ../sysdeps/nptl/libc_start_call_main.h:58    __libc_start_call_main
    0x7f0,205,042,d44    ../csu/libc-start.c:360    __libc_start_main_impl
    0x559,62a,11b,f8d    [unknown src]:0    [unknown func]
    0xf,fff,fff,fff,fff,fff    [unknown src]:0    [unknown func]
```

**Comment by jeffplata** [comment]
Bandits are cheats https://github.com/CleverRaven/Cataclysm-DDA/issues/75416

**Comment by l29ah** [comment]
The segfault reproduces every time (3/3) for me. Backtrace:
```
#0  npc::wont_hit_friend (this=this@entry=0x559baade73e0, tar=..., it=..., throwing=throwing@entry=false) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:199
#1  0x0000559b58f09b13 in npc_attack_gun::evaluate_tripoint (this=this@entry=0x559bafa81d70, source=..., target=target@entry=0x559bb0031880, location=...) at src/npc_attack.cpp:567
#2  0x0000559b58f0a202 in npc_attack_gun::evaluate (this=0x559bafa81d70, source=..., target=0x559bb0031880) at src/npc_attack.cpp:511
#3  0x0000559b58f1ec3f in operator() (__closure=__closure@entry=0x7ffdab957e00, potential_attack=std::shared_ptr<npc_attack> (use count 1, weak count 0) = {...}) at src/npcmove.cpp:1989
#4  0x0000559b58f3711d in operator() (__closure=0x7ffdab957eb0, it=0x559baade7c38) at src/npcmove.cpp:2014
#5  0x0000559b594894d5 in std::function<VisitResponse(item*, item*)>::operator() (__args#1=<optimized out>, __args#0=<optimized out>, this=0x7ffdab957eb0) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_function.h:591
#6  visit_internal (func=..., node=node@entry=0x559baade7c38, parent=parent@entry=0x0) at src/visitable.cpp:348
#7  0x0000559b59489df4 in Character::visit_items (this=0x559baade73e0, func=...) at src/visitable.cpp:453
#8  0x0000559b58f35565 in npc::evaluate_best_attack (this=this@entry=0x559baade73e0, target=<optimized out>, target@entry=0x559bb0031880) at src/npcmove.cpp:1998
#9  0x0000559b58f359ba in npc::method_of_attack (this=this@entry=0x559baade73e0) at src/npcmove.cpp:1972
#10 0x0000559b58f3e9dd in npc::move (this=this@entry=0x559baade73e0) at src/npcmove.cpp:1382
#11 0x0000559b586f6380 in (anonymous namespace)::monmove () at src/do_turn.cpp:359
#12 do_turn () at src/do_turn.cpp:657
#13 0x0000559b580d086c in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:873
```

**Comment by l29ah** [comment]
Segfault repro:
* load [2024.07.20.zip](https://github.com/user-attachments/files/16553899/2024.07.20.zip)
* go south
* kite zombies to the bandits

**Comment by Entity-y** [comment]
Feral zombies also seem to never miss when throwing rocks at our torso.

**Comment by jeffplata** [comment]
can confirm

**Comment by akrieger** [comment]
Crash stack

![image](https://github.com/user-attachments/assets/dad59ed9-e770-43e1-a538-bc83944e6811)

**Comment by x-qq** [comment]
I have created a separate bug report for the segfault - https://github.com/CleverRaven/Cataclysm-DDA/issues/75707
