### ISSUE TITLE
Assertion failure in map::get_cache on EOC on activating a doll in the glass world

### ISSUE THREAD

**Issue by l29ah** [CleverRaven/Cataclysm-DDA#76002]
### Describe the bug

I get teleported back it seems, but then cdda crashes:
```
(gdb) bt
#0  0x00007f09d1ec42dc in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007f09d1e74346 in raise () from /lib64/libc.so.6
#2  0x00007f09d1e5c8f7 in abort () from /lib64/libc.so.6
#3  0x00007f09d20dab8f in std::__glibcxx_assert_fail (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>)
    at /var/tmp/portage/sys-devel/gcc-14.2.1_p20240817/work/gcc-14-20240817/libstdc++-v3/src/c++11/assert_fail.cc:41
#4  0x000055bd2c01558d in std::unique_ptr<level_cache, std::default_delete<level_cache> >::operator* (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:451
#5  std::unique_ptr<level_cache, std::default_delete<level_cache> >::operator* (this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:451
#6  map::get_cache (this=this@entry=0x55bd5ce34620, zlev=zlev@entry=-12) at src/map.h:2614
#7  0x000055bd2c4ed71c in map::generate_lightmap (this=this@entry=0x55bd5ce34620, zlev=<optimized out>, zlev@entry=-12) at src/lightmap.cpp:393
#8  0x000055bd2c57eff7 in map::build_map_cache (this=this@entry=0x55bd5ce34620, zlev=-12, skip_lightmap=skip_lightmap@entry=false) at src/map.cpp:10164
#9  0x000055bd2beb6fb8 in Character::on_move (this=0x55bd5d35e4a0, old_pos=...) at src/character.cpp:3108
#10 0x000055bd2c00140d in Creature::move_to (this=this@entry=0x55bd5d35e4a0, loc=...) at src/creature.cpp:290
#11 0x000055bd2cc612d3 in teleport::teleport_to_point (critter=..., target=..., safe=safe@entry=true, add_teleglow=add_teleglow@entry=false, display_message=display_message@entry=false, force=true) at src/teleport.cpp:193
#12 0x000055bd2c953f59 in operator() (d=..., __closure=0x55bd627529b0) at src/npctalk.cpp:6382
#13 std::__invoke_impl<void, talk_effect_fun::(anonymous namespace)::f_teleport(const JsonObject&, std::string_view, std::string_view, bool)::<lambda(const dialogue&)>&, dialogue&> (__f=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:61
#14 std::__invoke_r<void, talk_effect_fun::(anonymous namespace)::f_teleport(const JsonObject&, std::string_view, std::string_view, bool)::<lambda(const dialogue&)>&, dialogue&> (__fn=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:111
#15 std::_Function_handler<void(dialogue&), talk_effect_fun::(anonymous namespace)::f_teleport(const JsonObject&, std::string_view, std::string_view, bool)::<lambda(const dialogue&)> >::_M_invoke(const std::_Any_data &, dialogue &) (
    __functor=..., __args#0=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_function.h:290
#16 0x000055bd2c915284 in talk_effect_t::apply (this=this@entry=0x55bd626ebda8, d=...) at src/npctalk.cpp:6502
#17 0x000055bd2c0ed392 in effect_on_condition::activate (this=0x55bd626ebd30, d=..., require_callstack_check=require_callstack_check@entry=true) at src/effect_on_condition.cpp:329
#18 0x000055bd2c0edddb in process_eocs (eoc_queue=..., eoc_vector=std::vector of length 17, capacity 32 = {...}, d=...) at src/effect_on_condition.cpp:248
#19 0x000055bd2c0edf64 in effect_on_conditions::process_effect_on_conditions (you=...) at src/effect_on_condition.cpp:275
#20 0x000055bd2c0adbdb in do_turn () at src/do_turn.cpp:676
#21 0x000055bd2ba8786c in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:873
```

### Attach save file

N/A

### Steps to reproduce

* build with `-D_GLIBCXX_ASSERTIONS` as you always should
* activate the worn doll

### Expected behavior

No UB.

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 52d2b5f44b-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by SurFlurer** [comment]
> zlev=-12

Quite abnormal. Did you activate the doll multiple times?

**Comment by l29ah** [comment]
Perhaps? I tried to activate it multiple times but it didn't work at first, i think, lemme try to repro.

**Comment by l29ah** [comment]
Yes, i have worn the doll, activated it three times, then i moved, and it crashed with zlev=-12.

**Comment by SurFlurer** [comment]
> I tried to activate it multiple times but it didn't work at first, i think,

The teleportation EOC is queued to happen in 1 second in the future. Perhaps it should be prevented to queue multiple copies of this EOC. Also the evaluated coordinate should be checked against OVERMAP_DEPTH.

/confirm
